[workspace]
members = [
  "crates/amenable",
  "crates/amenable_core",
  "crates/amenable_std",
  "crates/amenable_kani",
  "crates/amenable_creusot",
  "crates/amenable_verus",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/crumplecup/amenable"
authors = ["Erik Rose <erik.w.rose@gmail.com>"]
homepage = "https://github.com/crumplecup/amenable"
documentation = "https://docs.rs/amenable"

[workspace.dependencies]
amenable = { path = "crates/amenable", version = "0.1.0" }
amenable_core = { path = "crates/amenable_core", version = "0.1.0" }
amenable_std = { path = "crates/amenable_std", version = "0.1.0" }
amenable_kani = { path = "crates/amenable_kani", version = "0.1.0" }
amenable_creusot = { path = "crates/amenable_creusot", version = "0.1.0" }
amenable_verus = { path = "crates/amenable_verus", version = "0.1.0" }
