//! Temporal contract interface: standards-anchored propositions for date,
//! time, offset, and timestamp interchange, expressed in `amenable`'s
//! trait family.
//!
//! Every citation-only contract is a [`Standard`](amenable_core::Standard)
//! carrying a [`TemporalProvenance`] record that cites its normative
//! source (ISO 8601, RFC 3339, RFC 9557, CalConnect, IANA TZDB, SI/BIPM,
//! LoC EDTF). Composed / provable propositions are
//! [`Evidence`](amenable_core::Evidence); trait methods become
//! [`Exchange`](amenable_core::Exchange)s. See `docs/AMENABLE_TIME_PLAN.md`
//! for the full design and the migration phases.
//!
//! This crate carries **no checked-in standards corpus** — the relevant
//! normative clause lives embedded in each contract's provenance
//! metadata, governed by a three-tier redistributability rule (see
//! [`provenance_vocab`]). Nothing paywalled is reproduced.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

#[macro_use]
mod standard_macro;

mod contracts;
mod error;
mod exchange;
mod proof_composition;
mod provenance;
mod provenance_vocab;
mod traits;
mod types;

pub use contracts::{
    ApproximationQualificationDeclared, BasicFormatUsesMinimumComponentsForRequiredAccuracy,
    BeforeOrAfterQualificationIsLevelTwoOnly, BeforeOrOnDateUsesLeadingDoubleDotQualifier,
    BeforeYearOneValueUsesTrailingBSuffix, CalendarDateHasYearMonthDay,
    CalendarDateUsesGregorianCalendar,
    CalendarDayDurationMayBeModifiedByLeapSecondsOrLocalTimeShifts,
    CalendarDayIsIntervalOfSingleCalendarDateAdvance, CalendarDayWithinMonthBounds,
    CalendarMonthInRangeOneToTwelve, CalendarMonthIsNamedIntervalWithinCalendarYear,
    CalendarWeekIsSevenDayIntervalBeginningOnMonday, CalendarWeekNumberUsesFirstThursdayRule,
    CalendarWeekStartsOnMonday, CalendarYearInRangeZeroToNineThousandNineHundredNinetyNine,
    CalendarYearIsIntervalOfSuccessiveCalendarMonths,
    CalendarYearThrough1582RequiresMutualAgreement, CentennialYearDivisibleByOneHundred,
    CenturyOrdinalInRangeZeroToNinetyNine, ColonSeparatesTimeComponents,
    CombinedDateTimeDateComponentMustNotUseReducedAccuracy,
    CombinedDateTimePermitsCalendarDateComponent, CombinedDateTimePermitsOrdinalDateComponent,
    CombinedDateTimePermitsWeekDateComponent,
    CombinedDateTimeUsesSingleFormatAcrossDateAndTimeComponents,
    CombinedDateTimeUsesTimeDesignator, CommonYearHasThreeHundredSixtyFiveCalendarDays,
    CompleteIntervalCalendarDateMayBeSubstitutedByOrdinalDate,
    CompleteIntervalCalendarDateMayBeSubstitutedByWeekDate,
    CompleteIntervalDurationMaySubstituteWeekForm,
    CompleteIntervalLocalTimeMayBeSubstitutedByLocalTimeAndUtcDifference,
    CompleteIntervalLocalTimeMayBeSubstitutedByUtcOfDay,
    CompleteRepresentationCarriesAllRequiredComponents,
    ComponentQualificationAppliesOnlyToMarkedComponent,
    ComponentQualificationUsesImmediateLeftPlacement, ContextDependentDurationSemanticsDeclared,
    ConversionDropsNamedZoneIdentity, ConversionDropsSubsecondPrecision,
    ConversionPreservesRepresentedInstant, ConversionPreservesTemporalOrdering,
    ConversionRequiresExplicitAuthorityWhenLossy, ConversionSourceSemanticKindDeclared,
    ConversionTargetSemanticKindDeclared, CriticalTimeZoneSuffixInconsistencyRequiresAction,
    DateIdentifiesPositionWithinCalendar,
    DateTimeFormatRepresentationDescribesRepresentationFamily,
    DateTimeFormatRepresentationsForbiddenInTelexRepertoire,
    DateTimeFormulaCombinesTemporalValueWithDuration, DateTimeFormulaEvaluationModeDeclared,
    DateTimeFormulaTruncatesAtComponentBoundaries, DateTimeFormulaUsesCarryOverSemantics,
    DateTimeRepresentationIdentifiesPointIntervalOrRecurrence,
    DayDurationMaySpanSameTimeOfDayOnAdjacentCalendarDays, DayEqualsTwentyFourHours,
    DecadeOrdinalInRangeZeroToNineHundredNinetyNine,
    DecimalRepresentationUsesLowestOrderComponentFraction,
    DurationAlternativeFormCarriesCompleteCalendarAndClockComponents,
    DurationAlternativeFormRequiresPartnerAgreement,
    DurationAlternativeFormUsesDateAndTimeComponentSlots,
    DurationEqualsDifferenceBetweenIntervalEndpoints, DurationTimeComponentsFollowTimeDesignator,
    DurationUsesPeriodDesignator, DurationWeekFormNotMixedWithCalendarOrClockUnits,
    DurationWeekFormUsesSingleWeekUnit, ElectiveTimeZoneSuffixInconsistencyMayBeHandled,
    EndOfDayTwentyFourHourAllowedOnlyWithinIntervalOrRecurrence,
    EndOfDayTwentyFourHourForbiddenForSingleTimePoint,
    EnhancedIntervalLevelOnePermitsTerminalBoundaryQualification,
    EnhancedIntervalLevelTwoPermitsBeforeOrAfterBoundaryQualification,
    EnhancedIntervalLevelTwoPermitsInternalBoundaryQualification,
    EnhancedIntervalLevelTwoPermitsInternalBoundaryUnspecifiedDigits,
    ExactDurationSemanticsDeclared, ExpandedRepresentationRequiresAdditionalAgreement,
    ExplicitDateTimeTimePortionMayBeReducedPrecision,
    ExplicitDateTimeUsesDateThenTimeConcatenation,
    ExplicitDateTimeWithShiftUsesDateTimeThenShiftConcatenation,
    ExplicitDateWithShiftUsesDateThenShiftConcatenation,
    ExplicitDurationCompositeRepresentationDeclared, ExplicitDurationMayBeNegative,
    ExplicitDurationMayUseFractionalLowestOrderUnit,
    ExplicitDurationPrecedenceRepresentationCarriesEvaluationOrder,
    ExplicitDurationRepresentationKindDeclared, ExplicitDurationUsesDurationalUnitDesignators,
    ExplicitTemporalFormMayOmitZeroValuedComponents, ExplicitTemporalFormUsesDesignatorSymbols,
    ExplicitTemporalPrecisionUsesLowestDenotedComponent,
    ExplicitTimeIntervalDurationSubstitutionInfersMissingBoundary,
    ExplicitTimeIntervalLeadingShiftAppliesToTrailingComponentUnlessOverridden,
    ExplicitTimeIntervalTrailingEndMayInheritHigherOrderComponents,
    ExplicitTimeIntervalUsesDateTimeEndpointFamily, ExplicitTimeOfDayForbidsEndOfDayRepresentation,
    ExplicitTimeOfDayUsesHourMinuteSecondUnitDesignators, ExplicitTimeOfDayUsesTimeDesignator,
    ExplicitTimeOfDayWithShiftUsesTimeThenShiftConcatenation,
    ExplicitTimeShiftBareZuluRepresentsUtcZero, ExplicitTimeShiftPayloadUsesExplicitTimeOfDay,
    ExplicitTimeShiftUsesLeadingMinusOnlyWhenBehindUtc, ExplicitTimeShiftUsesZuluDesignator,
    ExplicitUtcRelationshipUsesZuluOrSignedShift, ExponentialYearExponentIsPositiveInteger,
    ExponentialYearUsesPowerOfTenNotation, FixedWidthComponentsRequireLeadingZeros,
    FormatRepresentationUsesPlaceholderCharactersForDigitsAndSigns,
    FractionAppliesToLowestOrderComponent, FractionUsesDecimalSign,
    FractionalSecondDigitsAreContiguous, FractionalSecondPrecisionDeclared,
    GregorianLeapYearUsesDivisibleByFourAndFourHundredException,
    GroupQualificationAppliesToMarkedAndMoreSignificantComponents,
    GroupQualificationUsesImmediateRightPlacement,
    GroupedTimeScaleUnitCarriesOneOrMoreDurationUnits, GroupedTimeScaleUnitConvertsToTimeInterval,
    GroupedTimeScaleUnitDateTimeMayCarryExplicitTimeShift,
    GroupedTimeScaleUnitDefinitionIsContinuous,
    GroupedTimeScaleUnitLowerOrderUnitsRemainWithinGroupBounds,
    GroupedTimeScaleUnitTruncatesOutOfBoundsRemainder, GroupedTimeScaleUnitUsesGroupingDesignators,
    GroupedTimeScaleUnitValueCarriesExplicitCoefficient, HourEqualsSixtyMinutes,
    HourInRangeZeroToTwentyFour, HyphenSeparatesDateComponents, InstantIsPointOnTimeAxis,
    IntervalDurationIsNonNegative, IntervalEndOmittedHigherOrderComponentsInheritFromStart,
    IntervalStartPrecedesEnd,
    IntervalTrailingComponentInheritsZoneOrUtcFromLeadingComponentWhenOmitted,
    Iso8601BasicFormUsesCompactRepresentation, Iso8601ExtendedFormUsesSeparators,
    IxdtfCalendarAnnotationDeclaresPreferredPresentationCalendar, IxdtfCalendarAnnotationPresent,
    IxdtfCalendarKeyUsesUCa, IxdtfCalendarValueUsesUnicodeCalendarIdentifier,
    IxdtfCriticalFlagIsLeadingExclamationWhenPresent,
    IxdtfCriticalSuffixTagsRequireProcessingOrErrorHandling,
    IxdtfDuplicateElectiveSuffixUsesFirstOccurrence,
    IxdtfExperimentalSuffixKeysAreNotForInterchange, IxdtfExperimentalSuffixKeysCannotBeRegistered,
    IxdtfExperimentalSuffixKeysUseLeadingUnderscore,
    IxdtfExpertReviewAscertainsBasicSpecificationExists,
    IxdtfExpertReviewReservesConciseGenerallyApplicableKeys,
    IxdtfExpertsMayInitiateRegistrationToAvoidFutureCollisions, IxdtfGeneratorsMayOmitSuffixTags,
    IxdtfPermanentEntriesUseSpecificationRequiredPolicy,
    IxdtfPermanentRegisteredSuffixKeyRequiresFullSpecificationReference,
    IxdtfProvisionalEntriesUseExpertReviewPolicy,
    IxdtfProvisionalRegisteredSuffixKeyReferenceExpectedToImproveOverTime,
    IxdtfProvisionalRegisteredSuffixKeyRequiresReferenceInformation,
    IxdtfRecipientsMayIgnoreElectiveSuffixTags,
    IxdtfRecipientsMustRejectUnconfiguredExperimentalSuffixKeys,
    IxdtfRegisteredSuffixKeyCarriesChangeController, IxdtfRegisteredSuffixKeyCarriesDescription,
    IxdtfRegisteredSuffixKeyCarriesKeyIdentifier, IxdtfRegisteredSuffixKeyCarriesReference,
    IxdtfRegisteredSuffixKeyCarriesRegistrationStatus,
    IxdtfRegisteredSuffixKeyStatusIsProvisionalOrPermanent, IxdtfRegistryInitiallyContainsUCaEntry,
    IxdtfSerializationCarriesNamedZoneAnnotation, IxdtfSuffixFollowsRfc3339Timestamp,
    IxdtfSuffixKeysAreLowercase, IxdtfSuffixTagsUseBracketedKeyValueForm,
    IxdtfSuffixValuesAreCaseSensitiveUnlessOtherwiseSpecified,
    IxdtfSuffixValuesUseHyphenDelimitedItems, IxdtfTimeZoneSuffixUsesBracketedNameOrOffset,
    IxdtfUCaRegistryEntryIsPermanent, IxdtfUCaRegistryEntryReferencesSectionFive,
    IxdtfUCaRegistryEntryUsesIetfChangeController,
    IxdtfUCaRegistryEntryUsesPreferredCalendarForPresentationDescription,
    LeapDayOccursOnlyInLeapYear, LeapSecondOccursOnlyAtUtcBoundary,
    LeapYearHasThreeHundredSixtySixCalendarDays,
    LetterPrefixedCalendarYearMagnitudeExceedsFourDigits,
    LetterPrefixedCalendarYearUsesLeadingYDesignator,
    LevelOneUnspecifiedDigitsOccupyRightmostPositions,
    LevelTwoUnspecifiedDigitsMayAppearWithinComponent,
    LiteralFormatCharactersCopyIntoRepresentations, LocalDateTimeMayBeAmbiguousAtZoneTransition,
    LocalDateTimeMayFallInZoneTransitionGap, LocalDateTimeRequiresZoneOrOffsetForInstant,
    LocalTimeHasHourMinuteSecond, LocalTimeRequiresTimeDesignatorWhenContextAmbiguous,
    LocalTimeScaleMayBeStandardOrNonUtcBased, LocalTimeUsesLocallyApplicableTimeScale,
    MinuteEqualsSixtySeconds, MinuteInRangeZeroToFiftyNine,
    MonthDurationInRangeTwentyEightToThirtyOneCalendarDays,
    MonthDurationMayRequireAgreedEndingCalendarDay,
    MonthMayBeConsideredThirtyCalendarDaysInCertainApplications, NamedTimeZoneAnnotationPresent,
    NamedTimeZoneIdentifierExcludesDotSegments, NamedTimeZoneIdentifierIsCaseSensitive,
    NamedTimeZoneIsNotNumericOffsetAlias, NamedTimeZoneMeaningUsesCurrentTzdbRules,
    NamedTimeZoneRetainsCivilRuleIdentity, NamedTimeZoneUsesIanaIdentifier,
    NegativeCalendarYearUsesLeadingMinusSign, NominalDayDurationMayDifferFromExactElapsedTime,
    NominalDurationDependsOnCalendarContext, NominalMonthDurationDependsOnCalendarContext,
    NominalWeekDurationIsDistinctFromExactElapsedTime, NominalYearDurationDependsOnCalendarContext,
    NumericOffsetDoesNotIdentifyNamedZone, OffsetDateTimeIdentifiesSingleInstant,
    OffsetTimeZoneAnnotationPresent, OffsetTimeZoneMustNotBeSynthesizedFromTimestampOffset,
    OffsetTimeZoneRepeatsTimestampOffset, OffsetTimeZoneUseIsStronglyDiscouraged,
    OnOrAfterDateUsesTrailingDoubleDotQualifier, OpenIntervalBoundaryDeclared,
    OrdinalDateHasYearAndDayOfYear, OrdinalDayInRangeOneToThreeHundredSixtySix,
    OrdinalDayOfYearUsesThreeDigits, PrecisionReductionDeclared,
    ProlepticGregorianDatesBefore1583RequireMutualAgreement, QualificationScopeDeclared,
    RecurringIntervalCarriesIntervalComponent, RecurringIntervalCountIsNonNegativeWhenBounded,
    RecurringIntervalOmittedCountDenotesUnboundedOccurrences,
    RecurringIntervalUsesCompleteTimeIntervalRepresentation,
    RecurringIntervalUsesOtherThanCompleteTimeIntervalRepresentation,
    RecurringIntervalUsesRepeatDesignator,
    RecurringIntervalWithRepeatRuleUsesCompleteRepresentation,
    ReducedAccuracyLocalTimeUsesHourMinuteRepresentation,
    ReducedAccuracyLocalTimeUsesHourOnlyRepresentation,
    ReducedAccuracyRepresentationOmitsLowerOrderComponents,
    ReducedAccuracyWeekDateOmitsWeekdayComponent, ReducedCalendarDateHasYearComponent,
    ReducedCalendarDateOmitsLowerOrderDigitsFromExtremeRight,
    ReducedCalendarDateUsesYearMonthRepresentation, ReducedCalendarDateUsesYearOnlyRepresentation,
    RepeatRuleDeclaresEligibleTimeIntervals,
    RepeatRuleEvaluationInheritsInitialStartComponentInformation,
    RepeatRuleSelectionAppliesWithinEligibleIntervals, RepeatRuleUsesFrequencyDesignator,
    Rfc3339ApplicationsMayAllowSpaceDateTimeSeparator,
    Rfc3339ClientsShouldTransformDatesForLocalityDisplay, Rfc3339FractionUsesDotSeparator,
    Rfc3339FractionalSecondsAreOnlyRarelyUsedOption, Rfc3339GeneratorsShouldUseUppercaseTAndZ,
    Rfc3339LeapSecondGenerationRequiresPriorAnnouncement,
    Rfc3339LexicalOrderingRequiresUniformFractionalSecondDigits,
    Rfc3339LexicalOrderingRequiresUniformUtcRelationshipEncoding, Rfc3339LocalOffsetNotUnknown,
    Rfc3339LocalityDisplayMayTranslateUtcToLocalTime, Rfc3339OffsetIsUtcOrNumeric,
    Rfc3339PositiveZeroOffsetDeclaresPreferredUtcReferencePoint,
    Rfc3339ProfileMakesMostFieldsAndPunctuationMandatory, Rfc3339RequiresUtcRelationship,
    Rfc3339TimestampExcludesRedundantWeekdayInformation,
    Rfc3339UnknownLocalOffsetUsesZuluDesignator, Rfc3339UnqualifiedLocalTimeForbidden,
    Rfc3339UsesExtendedCalendarDate, Rfc3339UsesFourDigitYear, Rfc3339UsesFullTime,
    RoundingModeDeclared, SeasonCodeDeclaresNamedSeason, SeasonCodeDeclaresSeasonScope,
    SeasonalExpressionUsesSeasonCodeInMonthSlot, SeasonalExpressionUsesYearAndSeasonForm,
    SecondInRangeZeroToSixty, SecondIsBaseUnitForExpressingDuration, SecondIsSiBaseUnitOfTime,
    SelectionExpressionMaySelectSingleInstance,
    SelectionExpressionUsesRecognizedSelectionRuleVocabulary,
    SelectionExpressionUsesSelectionDelimiters, SelectionRuleDayOfMonthUsesDayExpression,
    SelectionRuleHourUsesHourExpression, SelectionRuleMinuteUsesMinuteExpression,
    SelectionRuleMonthUsesMonthExpression, SelectionRuleOrdinalDayOfYearUsesOrdinalDayExpression,
    SelectionRulePositionAppliesLast, SelectionRulePositionUsesInstanceDesignatorSuffix,
    SelectionRuleSecondUsesSecondExpression, SelectionRuleWeekDayUsesDayOfWeekExpression,
    SelectionRuleWeekUsesWeekExpression, SelectionRulesApplyWithinSelectedResults,
    SelectionWithDurationUsesDurationSuffix, SerializationCarriesExplicitUtcRelationship,
    SerializationProfileDeclared, SignificantDigitYearCountIsPositiveInteger,
    SignificantDigitYearUsesTrailingSSuffix, SpaceForbiddenUnlessExplicitlyPermitted,
    SpeculativeDurationSemanticsDeclared, StandardTimeDerivedFromUtcByLocalShift,
    StandardTimeOfDayUsesStandardTimeScale, SubYearGroupingCodeDeclaresQuadrimester,
    SubYearGroupingCodeDeclaresQuarter, SubYearGroupingCodeDeclaresSemestral,
    SubYearGroupingExpressionUsesGroupingCodeInMonthSlot,
    SubYearGroupingExpressionUsesYearAndGroupingForm, SubsecondDigitsPreserved,
    TemporalChoiceSetUsesSquareBrackets, TemporalInclusiveSetUsesCurlyBraces,
    TemporalSetCarriesMultipleMembers, TemporalSetDeclaresAlternativeSemantics,
    TemporalSetDeclaresInclusiveMemberSemantics, TemporalSetForbidsInternalWhitespace,
    TemporalSetMemberSeparatorDeclared, TemporalSetOpenRangeUsesBoundaryDoubleDot,
    TemporalSetRangeNeighborhoodSharesPrecision, TemporalSetRangeUsesInclusiveDoubleDotSemantics,
    TimeAxisOrdersTimePointsByTemporalPosition, TimeIntervalBoundaryOrDurationFormDeclared,
    TimeIntervalHasTwoComponents, TimeIntervalUsesSolidusSeparator, TimeIsMarkOnSpecifiedTimeScale,
    TimeOfDayOccursWithinCalendarDay, TimeScaleAssociatesTimePointsWithOrderedMeasure,
    TimeShiftIsConstantDurationBetweenTimeScales, TimestampHasExplicitUtcOffset,
    TwentyFourHourRequiresZeroMinuteSecondAndFraction, TwentyFourHourReservedForEndOfDay,
    UncertaintyAndApproximationMayBeCombined, UncertaintyQualificationDeclared,
    UnderlineFallbackPrecedesQualifiedFormatCharacter,
    UnderlinedFormatPlaceholderRepresentsZeroOrMoreDigits, UnknownIntervalBoundaryDeclared,
    UnknownNamedTimeZoneIdentifierTreatedAsInconsistency,
    UnspecifiedDigitUsesUppercaseXPlaceholder, UnspecifiedDigitsDeclareUnknownValue,
    UtcDesignatorIsUppercaseZ, UtcDifferenceAppendedImmediatelyWithoutSpace,
    UtcDifferenceExpressionIsNotSelfStanding,
    UtcDifferenceMinutesOmittedOnlyForIntegralHourOffsets,
    UtcDifferenceSignEncodesDirectionRelativeToUtc, UtcIsReferenceTimeScale,
    UtcOfDayIdentifiesTimeWithinUtcCalendarDay, UtcOfDayUsesTrailingZuluDesignatorImmediately,
    UtcOffsetCarriesSignHourAndOptionalMinute, UtcOffsetHourInRangeZeroToTwentyThree,
    UtcOffsetMinuteInRangeZeroToFiftyNine, UtcTimelineOrderingAppliesToFixedInstants,
    WeekDateHasWeekYearWeekAndWeekday, WeekDateUsesWeekDesignator,
    WeekDurationMaySpanSameTimeOfDayInNextCalendarWeek, WeekNumberInRangeOneToFiftyThree,
    WeekdayInRangeOneToSeven,
    YearDurationInRangeThreeHundredSixtyFiveToThreeHundredSixtySixCalendarDays,
    YearDurationMayRequireAgreedEndingCalendarDate, ZoneOffsetResolvedForRepresentedInstant,
    ZoneTransitionAmbiguityDeclared, ZoneTransitionDisambiguationAuthorityDeclared,
    ZoneTransitionGapDeclared, ZoneTransitionGapHandlingAuthorityDeclared,
    ZuluTimeZoneSuffixAvoidsOffsetInconsistency,
};
pub use error::{TemporalError, TemporalErrorKind, TemporalResult};
pub use exchange::{
    CalendarDateValidToken, ParsedCalendarDate, RawInput, RawTemporalText, TemporalInputReceived,
    TemporalInputToken,
};
pub use proof_composition::{
    BackendConversionSemanticsValid, CalendarDateValid, CenturyValid, CombinedDateTimeDateEvidence,
    CompleteDateEvidence, CompleteDurationEndIntervalSubstitutionEvidence,
    CompleteIntervalDurationRepresentationEvidence, CompleteIntervalSubstitutionProofBranch,
    CompleteIntervalSubstitutionSemanticsValid,
    CompleteRecurringIntervalRepresentationSemanticsValid,
    CompleteStartDurationIntervalSubstitutionEvidence,
    CompleteStartEndIntervalSubstitutionEvidence, CompleteTimePointDateRepresentationEvidence,
    CompleteTimePointRepresentationEvidence, CompleteTimePointTimeRepresentationEvidence,
    ConversionLossless, ConversionTruncatesSubseconds, CriticalTimeZoneInconsistencyHandlingValid,
    DateTimeFormulaEvaluationResultValid, DateTimeFormulaEvaluationSemanticsValid,
    DateTimeFormulaValid, DateValid, DateWithShiftValid, DecadeValid,
    DurationAlternativeFormEvidence, DurationDesignatorRepresentationEvidence, DurationFormValid,
    DurationRepresentationProofBranch, DurationRepresentationSemanticsValid,
    DurationWeekFormEvidence, ElectiveTimeZoneInconsistencyHandlingValid,
    EnhancedIntervalLevelOneSemanticsValid, EnhancedIntervalLevelTwoSemanticsValid,
    ExplicitDateTimeValid, ExplicitDateTimeWithShiftValid, ExplicitDurationRepresentationEvidence,
    ExplicitDurationSemanticEvidence, ExplicitDurationValid,
    ExplicitIntervalDurationSubstitutionProofBranch,
    ExplicitIntervalDurationSubstitutionSemanticsValid,
    ExplicitIntervalEndComponentInheritanceProofBranch,
    ExplicitIntervalEndComponentInheritanceSemanticsValid,
    ExplicitIntervalShiftPropagationProofBranch, ExplicitIntervalShiftPropagationSemanticsValid,
    ExplicitTemporalFormValid, ExplicitTimeIntervalValid, ExplicitTimeOfDayValid,
    ExplicitTimeShiftValid, ExtendedIntervalBoundarySemanticsValid, ExtendedYearBaseEvidence,
    ExtendedYearSignificantDigitsEvidence, ExtendedYearValid, GroupedTimeScaleUnitValid,
    InheritedIntervalEndComponentsSemanticsValid, InheritedIntervalZoneSemanticsValid,
    IntervalEndComponentInheritanceProofBranch, IntervalEndpointsOrdered,
    IntervalZoneInheritanceProofBranch, IxdtfAdditionalInformationProofBranch,
    IxdtfAdditionalInformationSemanticsValid, IxdtfCalendarAnnotationProofBranch,
    IxdtfCalendarKeyRegistrySemanticsValid, IxdtfPermanentSuffixKeyRegistrationSemanticsValid,
    IxdtfProvisionalSuffixKeyRegistrationSemanticsValid, IxdtfSuffixKeyRegistryEntryValid,
    IxdtfSuffixKeyRegistryPolicySemanticsValid, IxdtfTimeZoneAnnotationProofBranch,
    IxdtfTimestampHasPreferredPresentationCalendar, IxdtfTimestampValid,
    LocalDateTimeDoesNotIdentifyFixedInstant, LocalDateTimeValid, LocalTimeScaleValid,
    LocalTimeSemanticsValid, LocalTimeValid, LocalTimeZoneResolutionProofBranch,
    LossyConversionAuthorityValid, MutualAgreementAuthorityScopeEvidence,
    MutualAgreementAuthorityValid, NamedTimeZoneIdentityValid,
    NamedTimeZoneInterpretationTracksTzdbRevision, NamedZoneAttachmentEvidence,
    OffsetConsistentWithNamedZone, OffsetDateTimeValid, OffsetOnlyZoneSemanticsLimited,
    OffsetTimeZoneAnnotationConsistentWithTimestamp, OrdinalDateValid,
    OtherThanCompleteRecurringIntervalRepresentationSemanticsValid, PrecisionPreserved,
    QualificationPlacementEvidence, QualifiedTemporalExpressionValid, QualifiedTemporalValueValid,
    RecurringIntervalFormValid, RecurringIntervalRepresentationProofBranch,
    RecurringIntervalWithRepeatRuleIntervalProofBranch, RecurringIntervalWithRepeatRuleValid,
    ReducedCalendarDatePrecisionEvidence, ReducedCalendarDateValid,
    ReducedLocalTimePrecisionEvidence, ReducedLocalTimeValid, RepeatRuleValid,
    Rfc3339DisplayGuidanceValid, Rfc3339GenerationGuidanceValid,
    Rfc3339LexicalOrderingSemanticsValid, Rfc3339TimestampValid, SeasonalTemporalExpressionValid,
    SelectionExpressionValid, StandardTimeOfDayValid, StandardTimeValid,
    SubYearGroupingExpressionValid, SubYearGroupingKindEvidence, TemporalOrderingPreserved,
    TemporalSetExpressionValid, TemporalSetRangeSemanticsValid, TimeIntervalValid,
    TimeOfDayWithShiftValid, TimeValid, TimestampRepresentsFixedInstant,
    UnspecifiedComponentExpressionValid, UtcOfDayValid, UtcOffsetKnown, UtcOffsetPrecisionEvidence,
    UtcOffsetValid, UtcTimeScaleValid, WeekDateValid, ZoneTransitionAmbiguitySemanticsValid,
    ZoneTransitionGapSemanticsValid, ZoneTransitionResolutionAuthorityValid,
    ZonedDateTimeHasNamedZone, ZonedTimestampEvidence, ZuluTimeZoneInconsistencyAvoidanceValid,
};
pub use provenance::TemporalProvenance;
pub use provenance_vocab::{
    CrossCheck, NormativeDocument, NormativeQuotation, NormativeSection, NormativeStatus,
    StandardsBody,
};
pub use traits::{TemporalParser, TemporalReporter};
pub use types::{
    CalendarDateDescriptor, CenturyDescriptor, CenturyDescriptorBuilder, CompleteDateDescriptor,
    DateDescriptor, DateTimeFormulaDescriptor, DateTimeFormulaEvaluationKindDescriptor,
    DateWithShiftDescriptor, DateWithShiftDescriptorBuilder, DecadeDescriptor,
    DecadeDescriptorBuilder, DurationDescriptor, DurationDescriptorBuilder,
    DurationFractionDescriptor, EligibleTimeIntervalsDescriptor,
    EligibleTimeIntervalsDescriptorBuilder, ExplicitDateTimeDescriptor,
    ExplicitDateTimeDescriptorBuilder, ExplicitDateTimeWithShiftDescriptor,
    ExplicitDateTimeWithShiftDescriptorBuilder, ExplicitDurationDescriptor,
    ExplicitDurationDescriptorBuilder, ExplicitDurationRepresentationKindDescriptor,
    ExplicitDurationSemanticKindDescriptor, ExplicitDurationSignDescriptor,
    ExplicitTemporalFormDescriptor, ExplicitTemporalFormDescriptorBuilder,
    ExplicitTemporalValueDescriptor, ExplicitTimeIntervalDescriptor,
    ExplicitTimeIntervalEndpointDescriptor, ExplicitTimeIntervalRepresentation,
    ExplicitTimeOfDayDescriptor, ExplicitTimeOfDayDescriptorBuilder, ExplicitTimeShiftDescriptor,
    ExplicitTimeShiftDescriptorBuilder, ExtendedYearBaseDescriptor, ExtendedYearDescriptor,
    ExtendedYearDescriptorBuilder, FractionalSecondDescriptor, GroupedTimeScaleUnitDescriptor,
    GroupedTimeScaleUnitDescriptorBuilder, IxdtfAnnotationDescriptor,
    IxdtfAnnotationDescriptorBuilder, IxdtfCalendarAnnotationDescriptor,
    IxdtfCalendarAnnotationDescriptorBuilder, IxdtfTimeZoneAnnotationDescriptor,
    IxdtfTimestampDescriptor, IxdtfTimestampDescriptorBuilder, LocalDateTimeDescriptor,
    LocalDateTimeDescriptorBuilder, LocalTimeDescriptor, LocalTimeDescriptorBuilder,
    LocalTimeScaleDescriptor, LocalTimeZoneResolutionAuthorityDescriptor,
    MaskedNumericComponentDescriptor, MaskedNumericComponentDescriptorBuilder,
    NamedSeasonDescriptor, NamedTimeZoneDescriptor, NamedTimeZoneDescriptorBuilder,
    OffsetDateTimeDescriptor, OffsetDateTimeDescriptorBuilder, OrdinalDateDescriptor,
    PrecisionDescriptor, PrecisionDescriptorBuilder, QuadrimesterOfYearDescriptor,
    QualificationPlacementDescriptor, QualificationScopeDescriptor,
    QualifiedOrBareTemporalValueDescriptor, QualifiedTemporalExpressionDescriptor,
    QualifiedTemporalValueDescriptor, QuarterOfYearDescriptor, RecurringIntervalDescriptor,
    RecurringIntervalDescriptorBuilder, RecurringIntervalWithRepeatRuleDescriptor,
    RecurringIntervalWithRepeatRuleDescriptorBuilder,
    RecurringIntervalWithRepeatRuleIntervalDescriptor, ReducedCalendarDateDescriptor,
    ReducedLocalTimeDescriptor, RepeatRuleDescriptor, RoundingModeDescriptor,
    SeasonScopeDescriptor, SeasonalTemporalExpressionDescriptor,
    SeasonalTemporalExpressionDescriptorBuilder, SelectionExpressionDescriptor,
    SelectionExpressionDescriptorBuilder, SelectionRuleDescriptor, SemestralHalfDescriptor,
    SerializationProfile, StandardTimeDescriptor, StandardTimeOfDayDescriptor,
    SubYearGroupingDescriptor, SubYearGroupingExpressionDescriptor,
    SubYearGroupingExpressionDescriptorBuilder, TemporalComponent, TemporalSerializationDescriptor,
    TemporalSerializationDescriptorBuilder, TemporalSetDescriptor, TemporalSetDescriptorBuilder,
    TemporalSetMemberDescriptor, TemporalSetSemanticsDescriptor, TemporalValueDescriptor,
    TimeDescriptor, TimeIntervalDescriptor, TimeIntervalEndpoint, TimeIntervalRepresentation,
    TimeOfDayWithShiftDescriptor, TimeOfDayWithShiftDescriptorBuilder, TimeScaleUnitDescriptor,
    TimeScaleUnitFractionDescriptor, TimeScaleUnitValueDescriptor,
    UnspecifiedComponentExpressionDescriptor, UnspecifiedComponentExpressionDescriptorBuilder,
    UnspecifiedDigitDescriptor, UnspecifiedPrecisionProfileDescriptor,
    UnspecifiedTemporalShapeDescriptor, UtcOfDayDescriptor, UtcOffsetDescriptor,
    UtcOffsetDescriptorBuilder, UtcOffsetRelationship, UtcOffsetSign, UtcTimeScaleDescriptor,
    WeekDateDescriptor, ZoneAmbiguityResolutionDescriptor, ZoneGapResolutionDescriptor,
    ZonedDateTimeDescriptor, ZonedDateTimeDescriptorBuilder,
};
