//! Blanket trusted/trivial `Witness` for the citation-only structural
//! temporal contracts.
//!
//! Every `temporal_standard!` contract that is *not* machine-checked (see
//! `amenable_kani::time` / `amenable_creusot::time` /
//! `amenable_time::verus_witness` for the ones that are) rests on its
//! normative citation alone. This module gives each such contract a
//! verifier-generic `Witness<V>` whose `support()` classifies that
//! citation — never `Checked`, always `Trivial` or `Trusted` — plus the
//! `ClassifiedWitness<V>` marker `#[derive(Witness)]` propagates through
//! the `proof_composition` aggregates. With these in place a `*Valid`
//! composite's derived proof is a real product: its machine-checked
//! members contribute `checked` support, its structural members
//! `trivial`/`trusted`, and the composite's `WitnessSupportSummary`
//! reports the honest breakdown.
//!
//! Classification is keyed on citation tier (coarse, refinable per
//! contract without changing the checked-vs-not distinction):
//! `OpenTextCrossCheck` cross-checks against the open-access
//! ISO/WD 8601-1:2016 draft (paraphrase-only, mostly structural shape
//! facts) are `Trivial`; `Normative` rules a standards body states
//! authoritatively are `Trusted`.

use amenable_core::{ClassifiedWitness, Standard, Verifier, Witness, WitnessSupportSummary};

use crate::TemporalProvenance;

/// Emit a verifier-generic trusted/trivial `Witness` + `ClassifiedWitness`
/// for each named structural contract. `$support` is the
/// `WitnessSupportSummary` constructor (`trivial_leaf` or `trusted_leaf`).
macro_rules! trusted_temporal_witness {
    ($support:ident: $($ty:ty),+ $(,)?) => {
        $(
            impl<V: Verifier> Witness<V> for $ty {
                type SupportingEvidence = Self;
                type ProofArtifact = TemporalProvenance;

                #[cfg_attr(not(kani), tracing::instrument(level = "trace"))]
                fn proof() -> Self::ProofArtifact {
                    <Self as Standard>::provenance(
                        &<Self as ::std::default::Default>::default(),
                    )
                }

                #[cfg_attr(not(kani), tracing::instrument(level = "trace"))]
                fn support() -> WitnessSupportSummary {
                    WitnessSupportSummary::$support()
                }
            }

            impl<V: Verifier> ClassifiedWitness<V> for $ty {}
        )+
    };
}

trusted_temporal_witness! {
    trivial_leaf:
    crate::BasicFormatUsesMinimumComponentsForRequiredAccuracy,
    crate::CalendarDateHasYearMonthDay,
    crate::CalendarDateUsesGregorianCalendar,
    crate::CalendarDayIsIntervalOfSingleCalendarDateAdvance,
    crate::CalendarMonthIsNamedIntervalWithinCalendarYear,
    crate::CalendarWeekIsSevenDayIntervalBeginningOnMonday,
    crate::CalendarWeekStartsOnMonday,
    crate::CalendarYearIsIntervalOfSuccessiveCalendarMonths,
    crate::CalendarYearThrough1582RequiresMutualAgreement,
    crate::ColonSeparatesTimeComponents,
    crate::CombinedDateTimeDateComponentMustNotUseReducedAccuracy,
    crate::CombinedDateTimePermitsCalendarDateComponent,
    crate::CombinedDateTimePermitsOrdinalDateComponent,
    crate::CombinedDateTimePermitsWeekDateComponent,
    crate::CombinedDateTimeUsesSingleFormatAcrossDateAndTimeComponents,
    crate::CombinedDateTimeUsesTimeDesignator,
    crate::CompleteRepresentationCarriesAllRequiredComponents,
    crate::DateTimeFormatRepresentationDescribesRepresentationFamily,
    crate::DateTimeFormatRepresentationsForbiddenInTelexRepertoire,
    crate::DateTimeRepresentationIdentifiesPointIntervalOrRecurrence,
    crate::DecimalRepresentationUsesLowestOrderComponentFraction,
    crate::ExpandedRepresentationRequiresAdditionalAgreement,
    crate::FixedWidthComponentsRequireLeadingZeros,
    crate::FormatRepresentationUsesPlaceholderCharactersForDigitsAndSigns,
    crate::FractionAppliesToLowestOrderComponent,
    crate::FractionUsesDecimalSign,
    crate::HyphenSeparatesDateComponents,
    crate::LeapSecondOccursOnlyAtUtcBoundary,
    crate::LiteralFormatCharactersCopyIntoRepresentations,
    crate::LocalTimeHasHourMinuteSecond,
    crate::LocalTimeRequiresTimeDesignatorWhenContextAmbiguous,
    crate::OrdinalDateHasYearAndDayOfYear,
    crate::OrdinalDayOfYearUsesThreeDigits,
    crate::ProlepticGregorianDatesBefore1583RequireMutualAgreement,
    crate::ReducedAccuracyLocalTimeUsesHourMinuteRepresentation,
    crate::ReducedAccuracyLocalTimeUsesHourOnlyRepresentation,
    crate::ReducedAccuracyRepresentationOmitsLowerOrderComponents,
    crate::ReducedAccuracyWeekDateOmitsWeekdayComponent,
    crate::ReducedCalendarDateHasYearComponent,
    crate::ReducedCalendarDateOmitsLowerOrderDigitsFromExtremeRight,
    crate::ReducedCalendarDateUsesYearMonthRepresentation,
    crate::ReducedCalendarDateUsesYearOnlyRepresentation,
    crate::SpaceForbiddenUnlessExplicitlyPermitted,
    crate::StandardTimeOfDayUsesStandardTimeScale,
    crate::UnderlineFallbackPrecedesQualifiedFormatCharacter,
    crate::UnderlinedFormatPlaceholderRepresentsZeroOrMoreDigits,
    crate::UtcDesignatorIsUppercaseZ,
    crate::UtcDifferenceAppendedImmediatelyWithoutSpace,
    crate::UtcDifferenceExpressionIsNotSelfStanding,
    crate::UtcDifferenceMinutesOmittedOnlyForIntegralHourOffsets,
    crate::UtcDifferenceSignEncodesDirectionRelativeToUtc,
    crate::UtcOffsetCarriesSignHourAndOptionalMinute,
    crate::WeekDateHasWeekYearWeekAndWeekday,
    crate::WeekDateUsesWeekDesignator,
}

trusted_temporal_witness! {
    trusted_leaf:
    crate::ApproximationQualificationDeclared,
    crate::BeforeOrAfterQualificationIsLevelTwoOnly,
    crate::BeforeOrOnDateUsesLeadingDoubleDotQualifier,
    crate::BeforeYearOneValueUsesTrailingBSuffix,
    crate::CalendarDayDurationMayBeModifiedByLeapSecondsOrLocalTimeShifts,
    crate::CalendarWeekNumberUsesFirstThursdayRule,
    crate::CompleteIntervalCalendarDateMayBeSubstitutedByOrdinalDate,
    crate::CompleteIntervalCalendarDateMayBeSubstitutedByWeekDate,
    crate::CompleteIntervalDurationMaySubstituteWeekForm,
    crate::CompleteIntervalLocalTimeMayBeSubstitutedByLocalTimeAndUtcDifference,
    crate::CompleteIntervalLocalTimeMayBeSubstitutedByUtcOfDay,
    crate::ComponentQualificationAppliesOnlyToMarkedComponent,
    crate::ComponentQualificationUsesImmediateLeftPlacement,
    crate::ContextDependentDurationSemanticsDeclared,
    crate::ConversionDropsNamedZoneIdentity,
    crate::ConversionDropsSubsecondPrecision,
    crate::ConversionPreservesRepresentedInstant,
    crate::ConversionPreservesTemporalOrdering,
    crate::ConversionRequiresExplicitAuthorityWhenLossy,
    crate::ConversionSourceSemanticKindDeclared,
    crate::ConversionTargetSemanticKindDeclared,
    crate::CriticalTimeZoneSuffixInconsistencyRequiresAction,
    crate::DateIdentifiesPositionWithinCalendar,
    crate::DateTimeFormulaCombinesTemporalValueWithDuration,
    crate::DateTimeFormulaEvaluationModeDeclared,
    crate::DateTimeFormulaTruncatesAtComponentBoundaries,
    crate::DateTimeFormulaUsesCarryOverSemantics,
    crate::DayDurationMaySpanSameTimeOfDayOnAdjacentCalendarDays,
    crate::DayEqualsTwentyFourHours,
    crate::DurationAlternativeFormCarriesCompleteCalendarAndClockComponents,
    crate::DurationAlternativeFormRequiresPartnerAgreement,
    crate::DurationAlternativeFormUsesDateAndTimeComponentSlots,
    crate::DurationEqualsDifferenceBetweenIntervalEndpoints,
    crate::DurationTimeComponentsFollowTimeDesignator,
    crate::DurationUsesPeriodDesignator,
    crate::DurationWeekFormNotMixedWithCalendarOrClockUnits,
    crate::DurationWeekFormUsesSingleWeekUnit,
    crate::ElectiveTimeZoneSuffixInconsistencyMayBeHandled,
    crate::EndOfDayTwentyFourHourAllowedOnlyWithinIntervalOrRecurrence,
    crate::EndOfDayTwentyFourHourForbiddenForSingleTimePoint,
    crate::EnhancedIntervalLevelOnePermitsTerminalBoundaryQualification,
    crate::EnhancedIntervalLevelTwoPermitsBeforeOrAfterBoundaryQualification,
    crate::EnhancedIntervalLevelTwoPermitsInternalBoundaryQualification,
    crate::EnhancedIntervalLevelTwoPermitsInternalBoundaryUnspecifiedDigits,
    crate::ExactDurationSemanticsDeclared,
    crate::ExplicitDateTimeTimePortionMayBeReducedPrecision,
    crate::ExplicitDateTimeUsesDateThenTimeConcatenation,
    crate::ExplicitDateTimeWithShiftUsesDateTimeThenShiftConcatenation,
    crate::ExplicitDateWithShiftUsesDateThenShiftConcatenation,
    crate::ExplicitDurationCompositeRepresentationDeclared,
    crate::ExplicitDurationMayBeNegative,
    crate::ExplicitDurationMayUseFractionalLowestOrderUnit,
    crate::ExplicitDurationPrecedenceRepresentationCarriesEvaluationOrder,
    crate::ExplicitDurationRepresentationKindDeclared,
    crate::ExplicitDurationUsesDurationalUnitDesignators,
    crate::ExplicitTemporalFormMayOmitZeroValuedComponents,
    crate::ExplicitTemporalFormUsesDesignatorSymbols,
    crate::ExplicitTemporalPrecisionUsesLowestDenotedComponent,
    crate::ExplicitTimeIntervalDurationSubstitutionInfersMissingBoundary,
    crate::ExplicitTimeIntervalLeadingShiftAppliesToTrailingComponentUnlessOverridden,
    crate::ExplicitTimeIntervalTrailingEndMayInheritHigherOrderComponents,
    crate::ExplicitTimeIntervalUsesDateTimeEndpointFamily,
    crate::ExplicitTimeOfDayForbidsEndOfDayRepresentation,
    crate::ExplicitTimeOfDayUsesHourMinuteSecondUnitDesignators,
    crate::ExplicitTimeOfDayUsesTimeDesignator,
    crate::ExplicitTimeOfDayWithShiftUsesTimeThenShiftConcatenation,
    crate::ExplicitTimeShiftBareZuluRepresentsUtcZero,
    crate::ExplicitTimeShiftPayloadUsesExplicitTimeOfDay,
    crate::ExplicitTimeShiftUsesLeadingMinusOnlyWhenBehindUtc,
    crate::ExplicitTimeShiftUsesZuluDesignator,
    crate::ExplicitUtcRelationshipUsesZuluOrSignedShift,
    crate::ExponentialYearExponentIsPositiveInteger,
    crate::ExponentialYearUsesPowerOfTenNotation,
    crate::FractionalSecondDigitsAreContiguous,
    crate::FractionalSecondPrecisionDeclared,
    crate::GroupQualificationAppliesToMarkedAndMoreSignificantComponents,
    crate::GroupQualificationUsesImmediateRightPlacement,
    crate::GroupedTimeScaleUnitCarriesOneOrMoreDurationUnits,
    crate::GroupedTimeScaleUnitConvertsToTimeInterval,
    crate::GroupedTimeScaleUnitDateTimeMayCarryExplicitTimeShift,
    crate::GroupedTimeScaleUnitDefinitionIsContinuous,
    crate::GroupedTimeScaleUnitLowerOrderUnitsRemainWithinGroupBounds,
    crate::GroupedTimeScaleUnitTruncatesOutOfBoundsRemainder,
    crate::GroupedTimeScaleUnitUsesGroupingDesignators,
    crate::GroupedTimeScaleUnitValueCarriesExplicitCoefficient,
    crate::HourEqualsSixtyMinutes,
    crate::InstantIsPointOnTimeAxis,
    crate::IntervalEndOmittedHigherOrderComponentsInheritFromStart,
    crate::IntervalTrailingComponentInheritsZoneOrUtcFromLeadingComponentWhenOmitted,
    crate::Iso8601BasicFormUsesCompactRepresentation,
    crate::Iso8601ExtendedFormUsesSeparators,
    crate::IxdtfCalendarAnnotationDeclaresPreferredPresentationCalendar,
    crate::IxdtfCalendarAnnotationPresent,
    crate::IxdtfCalendarKeyUsesUCa,
    crate::IxdtfCalendarValueUsesUnicodeCalendarIdentifier,
    crate::IxdtfCriticalFlagIsLeadingExclamationWhenPresent,
    crate::IxdtfCriticalSuffixTagsRequireProcessingOrErrorHandling,
    crate::IxdtfDuplicateElectiveSuffixUsesFirstOccurrence,
    crate::IxdtfExperimentalSuffixKeysAreNotForInterchange,
    crate::IxdtfExperimentalSuffixKeysCannotBeRegistered,
    crate::IxdtfExperimentalSuffixKeysUseLeadingUnderscore,
    crate::IxdtfExpertReviewAscertainsBasicSpecificationExists,
    crate::IxdtfExpertReviewReservesConciseGenerallyApplicableKeys,
    crate::IxdtfExpertsMayInitiateRegistrationToAvoidFutureCollisions,
    crate::IxdtfGeneratorsMayOmitSuffixTags,
    crate::IxdtfPermanentEntriesUseSpecificationRequiredPolicy,
    crate::IxdtfPermanentRegisteredSuffixKeyRequiresFullSpecificationReference,
    crate::IxdtfProvisionalEntriesUseExpertReviewPolicy,
    crate::IxdtfProvisionalRegisteredSuffixKeyReferenceExpectedToImproveOverTime,
    crate::IxdtfProvisionalRegisteredSuffixKeyRequiresReferenceInformation,
    crate::IxdtfRecipientsMayIgnoreElectiveSuffixTags,
    crate::IxdtfRecipientsMustRejectUnconfiguredExperimentalSuffixKeys,
    crate::IxdtfRegisteredSuffixKeyCarriesChangeController,
    crate::IxdtfRegisteredSuffixKeyCarriesDescription,
    crate::IxdtfRegisteredSuffixKeyCarriesKeyIdentifier,
    crate::IxdtfRegisteredSuffixKeyCarriesReference,
    crate::IxdtfRegisteredSuffixKeyCarriesRegistrationStatus,
    crate::IxdtfRegisteredSuffixKeyStatusIsProvisionalOrPermanent,
    crate::IxdtfRegistryInitiallyContainsUCaEntry,
    crate::IxdtfSerializationCarriesNamedZoneAnnotation,
    crate::IxdtfSuffixFollowsRfc3339Timestamp,
    crate::IxdtfSuffixKeysAreLowercase,
    crate::IxdtfSuffixTagsUseBracketedKeyValueForm,
    crate::IxdtfSuffixValuesAreCaseSensitiveUnlessOtherwiseSpecified,
    crate::IxdtfSuffixValuesUseHyphenDelimitedItems,
    crate::IxdtfTimeZoneSuffixUsesBracketedNameOrOffset,
    crate::IxdtfUCaRegistryEntryIsPermanent,
    crate::IxdtfUCaRegistryEntryReferencesSectionFive,
    crate::IxdtfUCaRegistryEntryUsesIetfChangeController,
    crate::IxdtfUCaRegistryEntryUsesPreferredCalendarForPresentationDescription,
    crate::LetterPrefixedCalendarYearMagnitudeExceedsFourDigits,
    crate::LetterPrefixedCalendarYearUsesLeadingYDesignator,
    crate::LevelOneUnspecifiedDigitsOccupyRightmostPositions,
    crate::LevelTwoUnspecifiedDigitsMayAppearWithinComponent,
    crate::LocalDateTimeMayBeAmbiguousAtZoneTransition,
    crate::LocalDateTimeMayFallInZoneTransitionGap,
    crate::LocalDateTimeRequiresZoneOrOffsetForInstant,
    crate::LocalTimeScaleMayBeStandardOrNonUtcBased,
    crate::LocalTimeUsesLocallyApplicableTimeScale,
    crate::MinuteEqualsSixtySeconds,
    crate::MonthDurationMayRequireAgreedEndingCalendarDay,
    crate::MonthMayBeConsideredThirtyCalendarDaysInCertainApplications,
    crate::NamedTimeZoneAnnotationPresent,
    crate::NamedTimeZoneIdentifierExcludesDotSegments,
    crate::NamedTimeZoneIdentifierIsCaseSensitive,
    crate::NamedTimeZoneIsNotNumericOffsetAlias,
    crate::NamedTimeZoneMeaningUsesCurrentTzdbRules,
    crate::NamedTimeZoneRetainsCivilRuleIdentity,
    crate::NamedTimeZoneUsesIanaIdentifier,
    crate::NegativeCalendarYearUsesLeadingMinusSign,
    crate::NominalDayDurationMayDifferFromExactElapsedTime,
    crate::NominalDurationDependsOnCalendarContext,
    crate::NominalMonthDurationDependsOnCalendarContext,
    crate::NominalWeekDurationIsDistinctFromExactElapsedTime,
    crate::NominalYearDurationDependsOnCalendarContext,
    crate::NumericOffsetDoesNotIdentifyNamedZone,
    crate::OffsetDateTimeIdentifiesSingleInstant,
    crate::OffsetTimeZoneAnnotationPresent,
    crate::OffsetTimeZoneMustNotBeSynthesizedFromTimestampOffset,
    crate::OffsetTimeZoneRepeatsTimestampOffset,
    crate::OffsetTimeZoneUseIsStronglyDiscouraged,
    crate::OnOrAfterDateUsesTrailingDoubleDotQualifier,
    crate::OpenIntervalBoundaryDeclared,
    crate::PrecisionReductionDeclared,
    crate::QualificationScopeDeclared,
    crate::RecurringIntervalCarriesIntervalComponent,
    crate::RecurringIntervalCountIsNonNegativeWhenBounded,
    crate::RecurringIntervalOmittedCountDenotesUnboundedOccurrences,
    crate::RecurringIntervalUsesCompleteTimeIntervalRepresentation,
    crate::RecurringIntervalUsesOtherThanCompleteTimeIntervalRepresentation,
    crate::RecurringIntervalUsesRepeatDesignator,
    crate::RecurringIntervalWithRepeatRuleUsesCompleteRepresentation,
    crate::RepeatRuleDeclaresEligibleTimeIntervals,
    crate::RepeatRuleEvaluationInheritsInitialStartComponentInformation,
    crate::RepeatRuleSelectionAppliesWithinEligibleIntervals,
    crate::RepeatRuleUsesFrequencyDesignator,
    crate::Rfc3339ApplicationsMayAllowSpaceDateTimeSeparator,
    crate::Rfc3339ClientsShouldTransformDatesForLocalityDisplay,
    crate::Rfc3339FractionUsesDotSeparator,
    crate::Rfc3339FractionalSecondsAreOnlyRarelyUsedOption,
    crate::Rfc3339GeneratorsShouldUseUppercaseTAndZ,
    crate::Rfc3339LeapSecondGenerationRequiresPriorAnnouncement,
    crate::Rfc3339LexicalOrderingRequiresUniformFractionalSecondDigits,
    crate::Rfc3339LexicalOrderingRequiresUniformUtcRelationshipEncoding,
    crate::Rfc3339LocalOffsetNotUnknown,
    crate::Rfc3339LocalityDisplayMayTranslateUtcToLocalTime,
    crate::Rfc3339OffsetIsUtcOrNumeric,
    crate::Rfc3339PositiveZeroOffsetDeclaresPreferredUtcReferencePoint,
    crate::Rfc3339ProfileMakesMostFieldsAndPunctuationMandatory,
    crate::Rfc3339RequiresUtcRelationship,
    crate::Rfc3339TimestampExcludesRedundantWeekdayInformation,
    crate::Rfc3339UnknownLocalOffsetUsesZuluDesignator,
    crate::Rfc3339UnqualifiedLocalTimeForbidden,
    crate::Rfc3339UsesExtendedCalendarDate,
    crate::Rfc3339UsesFourDigitYear,
    crate::Rfc3339UsesFullTime,
    crate::RoundingModeDeclared,
    crate::SeasonCodeDeclaresNamedSeason,
    crate::SeasonCodeDeclaresSeasonScope,
    crate::SeasonalExpressionUsesSeasonCodeInMonthSlot,
    crate::SeasonalExpressionUsesYearAndSeasonForm,
    crate::SecondIsBaseUnitForExpressingDuration,
    crate::SecondIsSiBaseUnitOfTime,
    crate::SelectionExpressionMaySelectSingleInstance,
    crate::SelectionExpressionUsesRecognizedSelectionRuleVocabulary,
    crate::SelectionExpressionUsesSelectionDelimiters,
    crate::SelectionRuleDayOfMonthUsesDayExpression,
    crate::SelectionRuleHourUsesHourExpression,
    crate::SelectionRuleMinuteUsesMinuteExpression,
    crate::SelectionRuleMonthUsesMonthExpression,
    crate::SelectionRuleOrdinalDayOfYearUsesOrdinalDayExpression,
    crate::SelectionRulePositionAppliesLast,
    crate::SelectionRulePositionUsesInstanceDesignatorSuffix,
    crate::SelectionRuleSecondUsesSecondExpression,
    crate::SelectionRuleWeekDayUsesDayOfWeekExpression,
    crate::SelectionRuleWeekUsesWeekExpression,
    crate::SelectionRulesApplyWithinSelectedResults,
    crate::SelectionWithDurationUsesDurationSuffix,
    crate::SerializationCarriesExplicitUtcRelationship,
    crate::SerializationProfileDeclared,
    crate::SignificantDigitYearCountIsPositiveInteger,
    crate::SignificantDigitYearUsesTrailingSSuffix,
    crate::SpeculativeDurationSemanticsDeclared,
    crate::StandardTimeDerivedFromUtcByLocalShift,
    crate::SubYearGroupingCodeDeclaresQuadrimester,
    crate::SubYearGroupingCodeDeclaresQuarter,
    crate::SubYearGroupingCodeDeclaresSemestral,
    crate::SubYearGroupingExpressionUsesGroupingCodeInMonthSlot,
    crate::SubYearGroupingExpressionUsesYearAndGroupingForm,
    crate::SubsecondDigitsPreserved,
    crate::TemporalChoiceSetUsesSquareBrackets,
    crate::TemporalInclusiveSetUsesCurlyBraces,
    crate::TemporalSetCarriesMultipleMembers,
    crate::TemporalSetDeclaresAlternativeSemantics,
    crate::TemporalSetDeclaresInclusiveMemberSemantics,
    crate::TemporalSetForbidsInternalWhitespace,
    crate::TemporalSetMemberSeparatorDeclared,
    crate::TemporalSetOpenRangeUsesBoundaryDoubleDot,
    crate::TemporalSetRangeNeighborhoodSharesPrecision,
    crate::TemporalSetRangeUsesInclusiveDoubleDotSemantics,
    crate::TimeAxisOrdersTimePointsByTemporalPosition,
    crate::TimeIntervalBoundaryOrDurationFormDeclared,
    crate::TimeIntervalHasTwoComponents,
    crate::TimeIntervalUsesSolidusSeparator,
    crate::TimeIsMarkOnSpecifiedTimeScale,
    crate::TimeOfDayOccursWithinCalendarDay,
    crate::TimeScaleAssociatesTimePointsWithOrderedMeasure,
    crate::TimeShiftIsConstantDurationBetweenTimeScales,
    crate::TimestampHasExplicitUtcOffset,
    crate::TwentyFourHourRequiresZeroMinuteSecondAndFraction,
    crate::TwentyFourHourReservedForEndOfDay,
    crate::UncertaintyAndApproximationMayBeCombined,
    crate::UncertaintyQualificationDeclared,
    crate::UnknownIntervalBoundaryDeclared,
    crate::UnknownNamedTimeZoneIdentifierTreatedAsInconsistency,
    crate::UnspecifiedDigitUsesUppercaseXPlaceholder,
    crate::UnspecifiedDigitsDeclareUnknownValue,
    crate::UtcIsReferenceTimeScale,
    crate::UtcOfDayIdentifiesTimeWithinUtcCalendarDay,
    crate::UtcOfDayUsesTrailingZuluDesignatorImmediately,
    crate::WeekDurationMaySpanSameTimeOfDayInNextCalendarWeek,
    crate::YearDurationMayRequireAgreedEndingCalendarDate,
    crate::ZoneOffsetResolvedForRepresentedInstant,
    crate::ZoneTransitionAmbiguityDeclared,
    crate::ZoneTransitionDisambiguationAuthorityDeclared,
    crate::ZoneTransitionGapDeclared,
    crate::ZoneTransitionGapHandlingAuthorityDeclared,
    crate::ZuluTimeZoneSuffixAvoidsOffsetInconsistency,
}
