[package]
name = "amenable_verus"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"

description = "Verus verifier backend for the amenable constitutional trait family"
keywords = ["formal-verification", "verus", "proof"]
categories = ["development-tools"]

[dependencies]
derive-getters = { workspace = true }
derive-new = { workspace = true }
verus_builtin_macros = { workspace = true }
vstd = { workspace = true }

[lints]
workspace = true
