//! Exercises `Stoplight`'s `amenable_core::StateMachine<KaniVerifier>`
//! impl -- generated by `#[derive(amenable_derive::StateMachine)]` from
//! the real `#[state_machine(..)]` declarations on `Stoplight` itself
//! (`docs/STATE_MACHINE_DERIVATION_PLAN.md`'s Step 2), replacing the old
//! hand-written `impl Amenable for Stoplight` this file used to exercise.
//! `states()`/`transitions()` echo the declarations directly;
//! `audit_surface()` queries the real `ExchangeEdgeRecord` registry, so
//! this file also carries the declared-vs-registered cross-check the
//! plan doc calls for -- confirming every declared edge has a matching
//! real registration, and every real registration for `Stoplight` was
//! declared, in both directions.

use amenable_core::{ExchangeEdgeRecord, StateMachine, Transition};
use amenable_kani::{KaniVerifier, Stoplight};

#[test]
fn states_reports_all_three_declared_states_in_declaration_order() {
    assert_eq!(
        <Stoplight as StateMachine<KaniVerifier>>::states(),
        &["Green", "Yellow", "Red"]
    );
}

#[test]
fn transitions_reports_all_three_declared_edges_in_declaration_order() {
    assert_eq!(
        <Stoplight as StateMachine<KaniVerifier>>::transitions(),
        &[
            Transition {
                from: "Green",
                to: "Yellow"
            },
            Transition {
                from: "Yellow",
                to: "Red"
            },
            Transition {
                from: "Red",
                to: "Green"
            },
        ]
    );
}

#[test]
fn audit_surface_reports_real_captured_bodies_for_every_declared_edge() {
    let surface = <Stoplight as StateMachine<KaniVerifier>>::audit_surface();

    assert_eq!(surface.len(), 3);

    let yellow = surface
        .iter()
        .find(|audit| audit.to == "Yellow")
        .expect("Green -> Yellow edge missing from audit surface");
    assert_eq!(yellow.method_name, "green_to_yellow");
    assert!(yellow.body.contains("Yellow::establish"));

    let red = surface
        .iter()
        .find(|audit| audit.to == "Red")
        .expect("Yellow -> Red edge missing from audit surface");
    assert_eq!(red.method_name, "yellow_to_red");
    assert!(red.body.contains("Red::establish"));

    let green = surface
        .iter()
        .find(|audit| audit.to == "Green")
        .expect("Red -> Green edge missing from audit surface");
    assert_eq!(green.method_name, "red_to_green");
    assert!(green.body.contains("Green::establish"));
}

#[test]
fn declared_transitions_match_real_exchange_edge_registrations_exactly() {
    let mut declared: Vec<&str> = <Stoplight as StateMachine<KaniVerifier>>::transitions()
        .iter()
        .map(|transition| transition.to)
        .collect();
    declared.sort_unstable();

    let mut registered: Vec<&str> = inventory::iter::<ExchangeEdgeRecord>()
        .filter(|record| record.self_ty == "Stoplight")
        .map(|record| record.evidence)
        .collect();
    registered.sort_unstable();

    assert_eq!(
        declared, registered,
        "declared Stoplight edges and real ExchangeEdgeRecord registrations diverged"
    );
}
