//! Creusot proof-function content for Rust standard-library carriers.
//!
//! This crate contains *only* what `cargo creusot -- -p amenable_creusot`
//! needs to translate: the harness functions themselves and the trusted
//! logic wrappers they depend on. Nothing here references
//! `RustStdStandard`, registers a `ProofRecord`, or implements
//! `CreusotWitness` -- that machinery moved to
//! `amenable_std::creusot_witness`, which imports the `&'static str`
//! constants below rather than duplicating the contract text. See that
//! module's doc comment for why: creusot-rustc's translator sweeps every
//! local item in a `creusot-std`-dependent crate, `#[cfg(creusot)]`-gated
//! or not, and chokes on ordinary Rust infrastructure (a return-position
//! `impl Trait` panicked its intrinsics pass outright; the `static` item
//! `::inventory::submit!` expands to hits "unsupported definition kind").
//!
//! Some carriers here admit real machine-checked postconditions (`char`,
//! `String`, slices, enums, etc.). Others still need explicit trusted
//! semantic boundaries because the relevant std implementation or external
//! contract surface remains opaque to Creusot (`HashMap`, `HashSet`,
//! `DefaultHasher`, `RandomState`, platform/runtime-backed types, and so
//! on). Either way, the witness layer in `amenable_std` imports these
//! source strings verbatim so the reported claim cannot drift from the
//! actual harness.
//!
//! Split by the real std module each file covers, mirroring
//! `amenable_creusot::rust_std_witness`'s own family names (no
//! `trusted_leaf_types`/`iter_flatten` here: a carrier with no real
//! Creusot contract has no harness function to hold): [`alloc_system`],
//! [`array_and_slice`], [`backtrace`], [`binary_heap`], [`boxed_carrier`],
//! [`btree`], [`c_str`], [`char_carrier`], [`cmp_carriers`],
//! [`cow_carrier`], [`duration_carrier`], [`env_carriers`], [`hash`],
//! [`io_seek_from`], [`linked_list`], [`mem_carrier`], [`net_shutdown`],
//! [`num`], [`ops_range_and_bound`], [`option_and_result`], [`os_str`],
//! [`os_windows_carrier`], [`panic_assert_unwind_safe`],
//! [`reference_carriers`], [`str_carriers`], [`string_carrier`],
//! [`sync_atomic`], [`task_carriers`], [`tuple_fn_raw_pointer`], and
//! [`vec_deque`].

mod alloc_system;
mod array_and_slice;
mod backtrace;
mod binary_heap;
mod boxed_carrier;
mod btree;
mod c_str;
mod char_carrier;
mod cmp_carriers;
mod cow_carrier;
mod duration_carrier;
mod env_carriers;
mod hash;
mod io_seek_from;
mod linked_list;
mod mem_carrier;
mod net_shutdown;
mod num;
mod ops_range_and_bound;
mod option_and_result;
mod os_str;
mod os_windows_carrier;
mod panic_assert_unwind_safe;
mod reference_carriers;
mod str_carriers;
mod string_carrier;
mod sync_atomic;
mod task_carriers;
mod tuple_fn_raw_pointer;
mod vec_deque;

pub use alloc_system::{
    SYSTEM_ALLOCATION_ROUND_TRIPS_SRC, VERIFY_SYSTEM_ALLOCATES_AND_DEALLOCATES_A_LAYOUT_SRC,
};
pub use array_and_slice::{
    INDEXING_AND_LENGTH_HOLDS_SRC, SLICE_ITER_MUT_YIELDS_MUTABLE_REFERENCES_THAT_WRITE_THROUGH_SRC,
    SLICE_ITER_YIELDS_SHARED_REFERENCES_IN_ORDER_SRC, VERIFY_ARRAY_INDEXING_AND_LENGTH_SRC,
    VERIFY_SLICE_INDEXING_AND_LENGTH_SRC,
    VERIFY_SLICE_ITER_MUT_YIELDS_MUTABLE_REFERENCES_THAT_WRITE_THROUGH_SRC,
    VERIFY_SLICE_ITER_YIELDS_SHARED_REFERENCES_IN_ORDER_SRC,
};
pub use backtrace::{
    VERIFY_BACKTRACE_FORCE_CAPTURE_ALWAYS_ACTUALLY_CAPTURES_SRC,
    VERIFY_BACKTRACE_STATUS_REPORTS_CAPTURED_AFTER_FORCE_CAPTURE_SRC,
};
pub use binary_heap::{
    BINARY_HEAP_DRAIN_YIELDS_EVERY_PUSHED_ELEMENT_ONCE_HOLDS_SRC,
    BINARY_HEAP_INTO_ITER_YIELDS_EVERY_PUSHED_ELEMENT_ONCE_HOLDS_SRC,
    BINARY_HEAP_ITER_YIELDS_EVERY_PUSHED_ELEMENT_ONCE_HOLDS_SRC,
    BINARY_HEAP_PEEK_MUT_EXPOSES_THE_MAXIMUM_HOLDS_SRC,
    BINARY_HEAP_POP_YIELDS_THE_MAXIMUM_FIRST_HOLDS_SRC,
    VERIFY_BINARY_HEAP_DRAIN_YIELDS_EVERY_PUSHED_ELEMENT_ONCE_SRC,
    VERIFY_BINARY_HEAP_INTO_ITER_YIELDS_EVERY_PUSHED_ELEMENT_ONCE_SRC,
    VERIFY_BINARY_HEAP_ITER_YIELDS_EVERY_PUSHED_ELEMENT_ONCE_SRC,
    VERIFY_BINARY_HEAP_PEEK_MUT_EXPOSES_THE_MAXIMUM_SRC,
    VERIFY_BINARY_HEAP_POP_YIELDS_THE_MAXIMUM_FIRST_SRC,
};
pub use boxed_carrier::{
    BOX_NEW_PRESERVES_THE_WRAPPED_VALUE_SRC, VERIFY_BOX_NEW_PRESERVES_THE_WRAPPED_VALUE_SRC,
};
pub use btree::{
    A_LESS_THAN_B_HOLDS_SRC, BTREE_MAP_ITERATES_IN_KEY_ORDER_HOLDS_SRC,
    BTREE_SET_ITERATES_IN_SORTED_ORDER_HOLDS_SRC, K1_LESS_THAN_K2_HOLDS_SRC,
    VERIFY_BTREE_MAP_ITERATES_IN_KEY_ORDER_SRC, VERIFY_BTREE_SET_ITERATES_IN_SORTED_ORDER_SRC,
};
pub use c_str::{
    CSTR_EXCLUDES_THE_TERMINATING_NUL_FROM_TO_BYTES_HOLDS_SRC,
    CSTRING_EXCLUDES_THE_TERMINATOR_AND_REJECTS_INTERIOR_NUL_HOLDS_SRC,
    FROM_BYTES_UNTIL_NUL_REQUIRES_A_NUL_BYTE_SOMEWHERE_HOLDS_SRC,
    INTO_STRING_ERROR_RECOVERS_THE_ORIGINAL_CSTRING_HOLDS_SRC, NON_NUL_BYTE_HOLDS_SRC,
    NUL_ERROR_REPORTS_THE_INTERIOR_NULS_POSITION_HOLDS_SRC, NUL_ONLY_AT_THE_END_VALIDATES_SRC,
    VERIFY_CSTR_EXCLUDES_THE_TERMINATING_NUL_FROM_TO_BYTES_SRC,
    VERIFY_CSTRING_EXCLUDES_THE_TERMINATOR_AND_REJECTS_INTERIOR_NUL_SRC,
    VERIFY_FROM_BYTES_UNTIL_NUL_REQUIRES_A_NUL_BYTE_SOMEWHERE_SRC,
    VERIFY_FROM_BYTES_WITH_NUL_REQUIRES_THE_NUL_ONLY_AT_THE_END_SRC,
    VERIFY_FROM_VEC_WITH_NUL_REQUIRES_THE_NUL_ONLY_AT_THE_END_SRC,
    VERIFY_INTO_STRING_ERROR_RECOVERS_THE_ORIGINAL_CSTRING_SRC,
    VERIFY_NUL_ERROR_REPORTS_THE_INTERIOR_NULS_POSITION_SRC,
};
pub use char_carrier::{
    CHAR_ROUNDTRIPS_SRC, VALID_UNICODE_SCALAR_HOLDS_SRC, VERIFY_CHAR_ROUNDTRIP_SRC,
};
pub use cmp_carriers::{
    ORDERING_REVERSE_SWAPS_LESS_AND_GREATER_HOLDS_SRC, REVERSE_INVERTS_COMPARISON_HOLDS_SRC,
    VERIFY_ORDERING_REVERSE_SWAPS_LESS_AND_GREATER_SRC, VERIFY_REVERSE_INVERTS_COMPARISON_SRC,
};
pub use cow_carrier::{
    COW_DESTRUCTURE_RECOVERS_THE_WRAPPED_VALUE_SRC,
    VERIFY_COW_DESTRUCTURE_RECOVERS_THE_WRAPPED_VALUE_SRC,
};
pub use duration_carrier::{
    DURATION_NEW_HEADROOM_HOLDS_SRC, DURATION_NEW_NORMALIZES_NANOS_AND_CARRIES_INTO_SECS_HOLDS_SRC,
    VERIFY_DURATION_NEW_NORMALIZES_NANOS_AND_CARRIES_INTO_SECS_SRC,
};
pub use env_carriers::{
    ARGV_EXTRA_HEADROOM_HOLDS_SRC, ARGV_INCLUDES_PROGRAM_PATH_SRC,
    VAR_ERROR_DISTINGUISHES_NOT_PRESENT_FROM_NOT_UNICODE_SRC,
    VERIFY_ARGS_OS_REPORTS_AT_LEAST_THE_PROGRAM_PATH_SRC,
    VERIFY_ARGS_REPORTS_AT_LEAST_THE_PROGRAM_PATH_SRC,
    VERIFY_JOIN_PATHS_ERROR_REPORTS_AN_UNJOINABLE_PATH_SRC,
    VERIFY_SPLIT_PATHS_RECOVERS_PATHS_JOINED_BY_JOIN_PATHS_SRC,
    VERIFY_VAR_ERROR_DISTINGUISHES_NOT_PRESENT_FROM_NOT_UNICODE_SRC,
};
pub use hash::{
    HASH_MAP_INSERT_THEN_GET_RECOVERS_THE_VALUE_SRC,
    HASH_SET_INSERT_THEN_CONTAINS_REPORTS_MEMBERSHIP_SRC,
    VERIFY_DEFAULT_HASHER_IS_DETERMINISTIC_ACROSS_FRESH_INSTANCES_SRC,
    VERIFY_HASH_MAP_INSERT_THEN_GET_RECOVERS_THE_VALUE_SRC,
    VERIFY_HASH_SET_INSERT_THEN_CONTAINS_REPORTS_MEMBERSHIP_SRC,
    VERIFY_RANDOM_STATE_GIVES_THE_SAME_HASHER_SEED_ACROSS_CALLS_SRC,
};
pub use io_seek_from::{
    SEEK_FROM_ROUND_TRIPS_EACH_VARIANTS_OFFSET_SRC,
    VERIFY_SEEK_FROM_ROUND_TRIPS_EACH_VARIANTS_OFFSET_SRC,
};
pub use linked_list::{
    DRAINS_TWO_VALUES_IN_ORDER_AND_EMPTIES_SRC,
    LINKED_LIST_EXTRACT_IF_PARTITIONS_BY_THE_PREDICATE_HOLDS_SRC,
    LINKED_LIST_ITER_MUT_WRITES_THROUGH_HOLDS_SRC,
    LINKED_LIST_ITER_YIELDS_REFERENCES_IN_ORDER_HOLDS_SRC,
    VERIFY_LINKED_LIST_EXTRACT_IF_PARTITIONS_BY_THE_PREDICATE_SRC,
    VERIFY_LINKED_LIST_INTO_ITER_YIELDS_OWNED_VALUES_IN_ORDER_SRC,
    VERIFY_LINKED_LIST_IS_FIFO_THROUGH_BACK_AND_FRONT_SRC,
    VERIFY_LINKED_LIST_ITER_MUT_WRITES_THROUGH_SRC,
    VERIFY_LINKED_LIST_ITER_YIELDS_REFERENCES_IN_ORDER_SRC,
    YIELDS_TWO_VALUES_IN_ORDER_THEN_ENDS_SRC,
};
pub use mem_carrier::{
    MANUALLY_DROP_DEREFS_AND_INTO_INNER_ROUND_TRIP_HOLDS_SRC,
    VERIFY_MANUALLY_DROP_DEREFS_AND_INTO_INNER_ROUND_TRIP_SRC,
};
pub use net_shutdown::VERIFY_SHUTDOWN_WRITE_PREVENTS_FURTHER_WRITES_SRC;
pub use num::{
    FP_CATEGORY_MATCHES_THE_VALUE_IT_CLASSIFIES_HOLDS_SRC,
    INT_ERROR_KIND_CLASSIFIES_PARSE_FAILURES_HOLDS_SRC, NONZERO_I16_GET_ROUND_TRIPS_SRC,
    NONZERO_I16_NEW_SUCCEEDS_EXACTLY_WHEN_NONZERO_SRC,
    PARSE_FLOAT_ERROR_OCCURS_ONLY_FOR_UNPARSEABLE_INPUT_HOLDS_SRC,
    PARSE_INT_ERROR_REPORTS_THE_KIND_OF_THE_FAILURE_HOLDS_SRC, SATURATING_I32_ADD_CLAMPS_HOLDS_SRC,
    TRY_FROM_INT_ERROR_OCCURS_EXACTLY_WHEN_OUT_OF_RANGE_HOLDS_SRC,
    VERIFY_FP_CATEGORY_MATCHES_THE_VALUE_IT_CLASSIFIES_SRC,
    VERIFY_INT_ERROR_KIND_CLASSIFIES_PARSE_FAILURES_SRC, VERIFY_NONZERO_I16_ROUNDTRIPS_SRC,
    VERIFY_PARSE_FLOAT_ERROR_OCCURS_ONLY_FOR_UNPARSEABLE_INPUT_SRC,
    VERIFY_PARSE_INT_ERROR_REPORTS_THE_KIND_OF_THE_FAILURE_SRC,
    VERIFY_SATURATING_ADD_MATCHES_THE_INNER_SATURATING_ADD_SRC,
    VERIFY_TRY_FROM_INT_ERROR_OCCURS_EXACTLY_WHEN_OUT_OF_RANGE_SRC,
    VERIFY_WRAPPING_ADD_MATCHES_THE_INNER_WRAPPING_ADD_SRC, WRAPPING_I32_ADD_WRAPS_HOLDS_SRC,
};
pub use ops_range_and_bound::{
    BOUND_ROUND_TRIPS_ITS_ENDPOINT_HOLDS_SRC,
    CONTROL_FLOW_CONTINUE_AND_BREAK_ARE_DISJOINT_HOLDS_SRC,
    RANGE_TO_CONTAINS_MATCHES_BOUND_HOLDS_SRC, VERIFY_BOUND_ROUND_TRIPS_ITS_ENDPOINT_SRC,
    VERIFY_CONTROL_FLOW_CONTINUE_AND_BREAK_ARE_DISJOINT_SRC,
    VERIFY_RANGE_FULL_CONTAINS_EVERYTHING_SRC, VERIFY_RANGE_TO_CONTAINS_MATCHES_BOUND_SRC,
};
pub use option_and_result::{
    ITER_YIELDS_OK_VALUE_ONCE_THEN_ENDS_SRC, ITER_YIELDS_VALUE_ONCE_THEN_ENDS_SRC,
    OPTION_SOME_AND_NONE_ARE_DISJOINT_HOLDS_SRC, RESULT_OK_AND_ERR_ARE_DISJOINT_HOLDS_SRC,
    VERIFY_OPTION_ITER_MUT_WRITES_THROUGH_TO_THE_OPTION_SRC,
    VERIFY_OPTION_ITER_YIELDS_ZERO_OR_ONE_REFERENCE_SRC,
    VERIFY_OPTION_SOME_AND_NONE_ARE_DISJOINT_SRC,
    VERIFY_RESULT_ITER_MUT_WRITES_THROUGH_TO_THE_RESULT_SRC,
    VERIFY_RESULT_ITER_YIELDS_A_REFERENCE_TO_THE_OK_VALUE_SRC,
    VERIFY_RESULT_OK_AND_ERR_ARE_DISJOINT_SRC,
};
pub use os_str::{
    OS_STR_VALID_UTF8_CONTENT_ROUND_TRIPS_THROUGH_TO_STR_SRC,
    VERIFY_OS_STR_DISPLAY_RENDERS_VALID_UTF8_CONTENT_UNCHANGED_SRC,
    VERIFY_OS_STR_VALID_UTF8_CONTENT_ROUND_TRIPS_THROUGH_TO_STR_SRC,
    VERIFY_OS_STRING_PUSH_APPENDS_TO_THE_EXISTING_CONTENT_SRC,
};
pub use os_windows_carrier::{
    ENCODE_WIDE_ENCODES_A_BMP_CODE_POINT_AS_ONE_CODE_UNIT_HOLDS_SRC,
    ENCODE_WIDE_HEADROOM_HOLDS_SRC,
    VERIFY_ENCODE_WIDE_ENCODES_A_BMP_CODE_POINT_AS_ONE_CODE_UNIT_SRC,
    VERIFY_WINDOWS_HANDLE_AS_RAW_HANDLE_RECOVERS_THE_WRAPPED_VALUE_SRC,
    VERIFY_WINDOWS_HANDLE_OR_INVALID_REJECTS_ONLY_THE_SENTINEL_SRC,
    VERIFY_WINDOWS_SOCKET_AS_RAW_SOCKET_RECOVERS_THE_WRAPPED_VALUE_SRC,
    WINDOWS_HANDLE_AS_RAW_HANDLE_RECOVERS_THE_WRAPPED_VALUE_HOLDS_SRC,
    WINDOWS_HANDLE_OR_INVALID_REJECTS_ONLY_THE_SENTINEL_HOLDS_SRC,
    WINDOWS_SOCKET_AS_RAW_SOCKET_RECOVERS_THE_WRAPPED_VALUE_HOLDS_SRC,
};
pub use panic_assert_unwind_safe::{
    ASSERT_UNWIND_SAFE_DEREFS_TRANSPARENTLY_SRC, VERIFY_ASSERT_UNWIND_SAFE_DEREFS_TRANSPARENTLY_SRC,
};
pub use reference_carriers::{
    MUTABLE_REFERENCE_DEREFERENCES_TO_AND_UPDATES_THE_REFERENT_SRC,
    SHARED_REFERENCE_DEREFERENCES_TO_THE_REFERENT_SRC,
    VERIFY_MUTABLE_REFERENCE_DEREFERENCES_TO_AND_UPDATES_THE_REFERENT_SRC,
    VERIFY_SHARED_REFERENCE_DEREFERENCES_TO_THE_REFERENT_SRC,
};
pub use str_carriers::{
    ASCII_BYTE_HOLDS_SRC, STR_BYTE_LENGTH_AND_CONTENT_HOLDS_SRC,
    VERIFY_STR_BYTE_LENGTH_AND_CONTENT_SRC,
};
pub use string_carrier::{STRING_ROUNDTRIPS_AND_PRESERVES_LENGTH_SRC, VERIFY_STRING_ROUNDTRIP_SRC};
pub use sync_atomic::{
    VERIFY_ATOMIC_BOOL_LOAD_STORE_SRC, VERIFY_ATOMIC_I8_LOAD_STORE_SRC,
    VERIFY_ATOMIC_I16_LOAD_STORE_SRC, VERIFY_ATOMIC_I32_LOAD_STORE_SRC,
    VERIFY_ATOMIC_I64_LOAD_STORE_SRC, VERIFY_ATOMIC_ISIZE_LOAD_STORE_SRC,
    VERIFY_ATOMIC_PTR_LOAD_STORE_SRC, VERIFY_ATOMIC_U8_LOAD_STORE_SRC,
    VERIFY_ATOMIC_U16_LOAD_STORE_SRC, VERIFY_ATOMIC_U32_LOAD_STORE_SRC,
    VERIFY_ATOMIC_U64_LOAD_STORE_SRC, VERIFY_ATOMIC_USIZE_LOAD_STORE_SRC,
};
pub use task_carriers::{
    PENDING_NEVER_RESOLVES_HOLDS_SRC, POLL_FN_DISPATCHES_THROUGH_TO_ITS_CLOSURE_HOLDS_SRC,
    POLL_READY_AND_PENDING_ARE_DISJOINT_HOLDS_SRC,
    READY_RESOLVES_IMMEDIATELY_WITH_ITS_VALUE_HOLDS_SRC,
    RELAXED_ORDERING_STILL_MAKES_A_STORE_OBSERVABLE_HOLDS_SRC,
    VERIFY_CONTEXT_FROM_WAKER_EXPOSES_THE_SAME_WAKER_SRC, VERIFY_PENDING_NEVER_RESOLVES_SRC,
    VERIFY_POLL_FN_DISPATCHES_THROUGH_TO_ITS_CLOSURE_SRC,
    VERIFY_POLL_READY_AND_PENDING_ARE_DISJOINT_SRC,
    VERIFY_READY_RESOLVES_IMMEDIATELY_WITH_ITS_VALUE_SRC,
    VERIFY_RELAXED_ORDERING_STILL_MAKES_A_STORE_OBSERVABLE_SRC,
    VERIFY_WAKER_WAKE_BY_REF_INVOKES_THE_WAKE_IMPL_SRC,
    WAKER_WAKE_BY_REF_INVOKES_THE_WAKE_IMPL_HOLDS_SRC,
};
pub use tuple_fn_raw_pointer::{
    FN_POINTER_CALLS_THE_UNDERLYING_FUNCTION_SRC, TUPLE_FIELD_ACCESS_HOLDS_SRC,
    VERIFY_CONST_POINTER_CAST_PRESERVES_THE_ADDRESS_SRC,
    VERIFY_FN_POINTER_CALLS_THE_UNDERLYING_FUNCTION_SRC,
    VERIFY_MUT_POINTER_CAST_PRESERVES_THE_ADDRESS_SRC, VERIFY_TUPLE_FIELD_ACCESS_SRC,
};
pub use vec_deque::{
    TRY_RESERVE_REJECTS_AN_IMPOSSIBLE_CAPACITY_HOLDS_SRC,
    VEC_DEQUE_ITER_MUT_WRITES_THROUGH_HOLDS_SRC,
    VEC_DEQUE_ITER_YIELDS_REFERENCES_IN_ORDER_HOLDS_SRC,
    VEC_DEQUE_PUSHES_AND_POPS_FROM_BOTH_ENDS_HOLDS_SRC,
    VERIFY_TRY_RESERVE_REJECTS_AN_IMPOSSIBLE_CAPACITY_SRC,
    VERIFY_VEC_DEQUE_DRAIN_REMOVES_AND_YIELDS_IN_ORDER_SRC,
    VERIFY_VEC_DEQUE_INTO_ITER_YIELDS_OWNED_VALUES_IN_ORDER_SRC,
    VERIFY_VEC_DEQUE_ITER_MUT_WRITES_THROUGH_SRC,
    VERIFY_VEC_DEQUE_ITER_YIELDS_REFERENCES_IN_ORDER_SRC,
    VERIFY_VEC_DEQUE_PUSHES_AND_POPS_FROM_BOTH_ENDS_SRC,
};
