//! Verus specs for `amenable_time`'s genuinely-checkable temporal
//! contracts (`AMENABLE_TIME_PLAN.md` Phase 6). One file per contract,
//! each holding exactly the `verus! { ... }` spec function(s) its real
//! invariant needs — matching `rust_std`'s one-claim-per-carrier shape,
//! so `amenable_time::verus_witness` can `include_str!` a single file as
//! that contract's whole `claim`.

mod calendar_day_within_month_bounds_carrier;
mod calendar_month_carrier;
mod calendar_year_in_range_zero_to_nine_thousand_nine_hundred_ninety_nine_carrier;
mod centennial_year_divisible_by_one_hundred_carrier;
mod century_ordinal_in_range_zero_to_ninety_nine_carrier;
mod common_year_has_three_hundred_sixty_five_calendar_days_carrier;
mod decade_ordinal_in_range_zero_to_nine_hundred_ninety_nine_carrier;
mod gregorian_leap_year_carrier;
mod hour_in_range_zero_to_twenty_four_carrier;
mod interval_duration_is_non_negative_carrier;
mod interval_start_precedes_end_carrier;
mod leap_day_occurs_only_in_leap_year_carrier;
mod leap_year_has_three_hundred_sixty_six_calendar_days_carrier;
mod minute_in_range_zero_to_fifty_nine_carrier;
mod month_duration_in_range_twenty_eight_to_thirty_one_calendar_days_carrier;
mod ordinal_day_in_range_one_to_three_hundred_sixty_six_carrier;
mod second_in_range_zero_to_sixty_carrier;
mod utc_offset_hour_in_range_zero_to_twenty_three_carrier;
mod utc_offset_minute_in_range_zero_to_fifty_nine_carrier;
mod utc_timeline_ordering_applies_to_fixed_instants_carrier;
mod week_number_in_range_one_to_fifty_three_carrier;
mod weekday_in_range_one_to_seven_carrier;
mod year_duration_in_range_three_hundred_sixty_five_to_three_hundred_sixty_six_calendar_days_carrier;
pub use calendar_month_carrier::verify_calendar_month_in_range;
#[cfg(verus_keep_ghost)]
pub use calendar_month_carrier::calendar_month_is_enumerated;
pub use hour_in_range_zero_to_twenty_four_carrier::verify_hour_in_range_zero_to_twenty_four;
#[cfg(verus_keep_ghost)]
pub use hour_in_range_zero_to_twenty_four_carrier::hour_in_range_zero_to_twenty_four_holds;
pub use minute_in_range_zero_to_fifty_nine_carrier::verify_minute_in_range_zero_to_fifty_nine;
#[cfg(verus_keep_ghost)]
pub use minute_in_range_zero_to_fifty_nine_carrier::minute_in_range_zero_to_fifty_nine_holds;
pub use second_in_range_zero_to_sixty_carrier::verify_second_in_range_zero_to_sixty;
#[cfg(verus_keep_ghost)]
pub use second_in_range_zero_to_sixty_carrier::second_in_range_zero_to_sixty_holds;
pub use utc_offset_hour_in_range_zero_to_twenty_three_carrier::verify_utc_offset_hour_in_range_zero_to_twenty_three;
#[cfg(verus_keep_ghost)]
pub use utc_offset_hour_in_range_zero_to_twenty_three_carrier::utc_offset_hour_in_range_zero_to_twenty_three_holds;
pub use utc_offset_minute_in_range_zero_to_fifty_nine_carrier::verify_utc_offset_minute_in_range_zero_to_fifty_nine;
#[cfg(verus_keep_ghost)]
pub use utc_offset_minute_in_range_zero_to_fifty_nine_carrier::utc_offset_minute_in_range_zero_to_fifty_nine_holds;
pub use weekday_in_range_one_to_seven_carrier::verify_weekday_in_range_one_to_seven;
#[cfg(verus_keep_ghost)]
pub use weekday_in_range_one_to_seven_carrier::weekday_in_range_one_to_seven_holds;
pub use week_number_in_range_one_to_fifty_three_carrier::verify_week_number_in_range_one_to_fifty_three;
#[cfg(verus_keep_ghost)]
pub use week_number_in_range_one_to_fifty_three_carrier::week_number_in_range_one_to_fifty_three_holds;
pub use ordinal_day_in_range_one_to_three_hundred_sixty_six_carrier::verify_ordinal_day_in_range_one_to_three_hundred_sixty_six;
#[cfg(verus_keep_ghost)]
pub use ordinal_day_in_range_one_to_three_hundred_sixty_six_carrier::ordinal_day_in_range_one_to_three_hundred_sixty_six_holds;
pub use century_ordinal_in_range_zero_to_ninety_nine_carrier::verify_century_ordinal_in_range_zero_to_ninety_nine;
#[cfg(verus_keep_ghost)]
pub use century_ordinal_in_range_zero_to_ninety_nine_carrier::century_ordinal_in_range_zero_to_ninety_nine_holds;
pub use decade_ordinal_in_range_zero_to_nine_hundred_ninety_nine_carrier::verify_decade_ordinal_in_range_zero_to_nine_hundred_ninety_nine;
#[cfg(verus_keep_ghost)]
pub use decade_ordinal_in_range_zero_to_nine_hundred_ninety_nine_carrier::decade_ordinal_in_range_zero_to_nine_hundred_ninety_nine_holds;
pub use calendar_year_in_range_zero_to_nine_thousand_nine_hundred_ninety_nine_carrier::verify_calendar_year_in_range_zero_to_nine_thousand_nine_hundred_ninety_nine;
#[cfg(verus_keep_ghost)]
pub use calendar_year_in_range_zero_to_nine_thousand_nine_hundred_ninety_nine_carrier::calendar_year_in_range_zero_to_nine_thousand_nine_hundred_ninety_nine_holds;
pub use interval_start_precedes_end_carrier::verify_interval_start_precedes_end;
#[cfg(verus_keep_ghost)]
pub use interval_start_precedes_end_carrier::interval_start_precedes_end_holds;
pub use interval_duration_is_non_negative_carrier::verify_interval_duration_is_non_negative;
#[cfg(verus_keep_ghost)]
pub use interval_duration_is_non_negative_carrier::interval_duration_is_non_negative_holds;
pub use utc_timeline_ordering_applies_to_fixed_instants_carrier::verify_utc_timeline_ordering_applies_to_fixed_instants;
#[cfg(verus_keep_ghost)]
pub use utc_timeline_ordering_applies_to_fixed_instants_carrier::utc_timeline_ordering_applies_to_fixed_instants_holds;
pub use gregorian_leap_year_carrier::verify_gregorian_leap_year;
#[cfg(verus_keep_ghost)]
pub use gregorian_leap_year_carrier::gregorian_leap_year_holds;
pub use centennial_year_divisible_by_one_hundred_carrier::verify_centennial_year_divisible_by_one_hundred;
#[cfg(verus_keep_ghost)]
pub use centennial_year_divisible_by_one_hundred_carrier::centennial_year_divisible_by_one_hundred_holds;
pub use leap_year_has_three_hundred_sixty_six_calendar_days_carrier::verify_leap_year_has_three_hundred_sixty_six_calendar_days;
#[cfg(verus_keep_ghost)]
pub use leap_year_has_three_hundred_sixty_six_calendar_days_carrier::leap_year_has_three_hundred_sixty_six_calendar_days_holds;
pub use common_year_has_three_hundred_sixty_five_calendar_days_carrier::verify_common_year_has_three_hundred_sixty_five_calendar_days;
#[cfg(verus_keep_ghost)]
pub use common_year_has_three_hundred_sixty_five_calendar_days_carrier::common_year_has_three_hundred_sixty_five_calendar_days_holds;
pub use year_duration_in_range_three_hundred_sixty_five_to_three_hundred_sixty_six_calendar_days_carrier::verify_year_duration_in_range_three_hundred_sixty_five_to_three_hundred_sixty_six_calendar_days;
#[cfg(verus_keep_ghost)]
pub use year_duration_in_range_three_hundred_sixty_five_to_three_hundred_sixty_six_calendar_days_carrier::year_duration_in_range_three_hundred_sixty_five_to_three_hundred_sixty_six_calendar_days_holds;
pub use month_duration_in_range_twenty_eight_to_thirty_one_calendar_days_carrier::verify_month_duration_in_range_twenty_eight_to_thirty_one_calendar_days;
#[cfg(verus_keep_ghost)]
pub use month_duration_in_range_twenty_eight_to_thirty_one_calendar_days_carrier::month_duration_in_range_twenty_eight_to_thirty_one_calendar_days_holds;
pub use calendar_day_within_month_bounds_carrier::verify_calendar_day_within_month_bounds;
#[cfg(verus_keep_ghost)]
pub use calendar_day_within_month_bounds_carrier::calendar_day_within_month_bounds_holds;
pub use leap_day_occurs_only_in_leap_year_carrier::verify_leap_day_occurs_only_in_leap_year;
#[cfg(verus_keep_ghost)]
pub use leap_day_occurs_only_in_leap_year_carrier::leap_day_occurs_only_in_leap_year_holds;
#[cfg(verus_keep_ghost)]
pub use leap_year_has_three_hundred_sixty_six_calendar_days_carrier::days_in_year;
#[cfg(verus_keep_ghost)]
pub use month_duration_in_range_twenty_eight_to_thirty_one_calendar_days_carrier::{
    days_in_month, valid_calendar_day,
};
