//! Gallery case: can the `Ensures<V>`/spec-companion/`when_used_as_spec`
//! pattern `gallery::ensures_contract_bound` confirmed by hand
//! (`EnsuresGreen`) be generated by a `macro_rules!` macro instead —
//! the real Verus-side counterpart to `amenable_kani`'s `kani_ensures!`?
//!
//! ## Why this can't be a proc-macro crate like `amenable_derive`
//!
//! `EXCHANGE_PROOF_DERIVATION_PLAN.md`'s Step 7 generalized Kani's
//! version of this exact pattern into `#[amenable_derive::exchange(..)]`,
//! a `proc_macro_attribute` living in its own crate. That approach is not
//! available here, for a reason structural to this whole crate (see
//! `lib.rs`'s own doc comment): `verus --crate-type=lib` is invoked as a
//! bare compiler over a single file tree, never consulting `Cargo.toml`.
//! `amenable_verus`'s own `Cargo.toml` lists exactly two dependencies
//! (`verus_builtin_macros`, `vstd`) because those two are the only extern
//! crates the real `verus` binary itself knows to link in when invoked
//! bare — there is no mechanism for it to discover and link an arbitrary
//! third-party proc-macro crate like `amenable_derive`, regardless of what
//! `Cargo.toml` says (Cargo.toml is never read for that invocation at
//! all). A `#[amenable_derive::anything]` attribute placed in this crate
//! would resolve fine under ordinary `cargo check -p amenable_verus`
//! (real Cargo dependency resolution) and then fail to resolve at all
//! under the actual verification invocation — the one that matters.
//!
//! `macro_rules!` macros sidestep this entirely: they are not a separate
//! crate `verus` would need to know how to link — they are plain Rust
//! syntax, expanded by the ordinary Rust macro-expansion pass every
//! `rustc`-based tool (including Verus's own `rust_verify`, built on real
//! `rustc_private` internals) runs before any further processing. No
//! extern resolution is needed for the definition or the call site.
//!
//! ## Disposition
//!
//! **Confirmed working, but not on the first attempt.** `verus_ensures!`
//! (defined below, at plain module scope) expands to the identical shape
//! `gallery::ensures_contract_bound`'s `EnsuresGreen` case wrote by hand: a
//! `pub open spec fn` companion plus an `impl Ensures<V>` whose `ensures()`
//! carries `#[verifier::when_used_as_spec(..)]` pointing at it.
//! `EnsuresBlue` below is built entirely through the macro, not by hand,
//! and verifies clean alongside `EnsuresGreen`'s hand-written original in
//! the same crate.
//!
//! **What was tried and rejected.** The first, more obvious shape —
//! `macro_rules! verus_ensures { .. => { pub open spec fn .. impl Ensures<V>
//! for T { .. } } }`, invoked *inside* the surrounding `verus! { .. }`
//! block the way every other item in this gallery is declared — failed
//! immediately with a real, legible rejection: `` visibility `pub` is not
//! followed by an item `` / `` macro expansion ignores `open` and any
//! tokens following ``, plus a note that "the usage of `verus_ensures!` is
//! likely invalid in item context." Not a Verus-specific error at all —
//! ordinary `rustc` macro expansion validates a `macro_rules!` macro's
//! *output* against plain Rust item grammar before anything downstream
//! ever sees it, and `spec`/`open` are not plain Rust keywords; they only
//! mean anything through `verus! { .. }`'s own bespoke token-stream
//! pre-processing, which runs once, on its own literal input, and does not
//! reach inside an unexpanded nested macro invocation to find more such
//! syntax hiding there. This is a materially different failure from every
//! other "not inside `verus! {}`" rejection found earlier in this plan
//! (`Evidence`'s cyclic self-reference, `Sidecar`'s `ProofToken` bound) —
//! those were Verus *semantic* checks rejecting real, already-parsed code;
//! this is plain `rustc` refusing to parse the macro's output as Rust
//! *at all*, before Verus-specific processing is even reachable.
//!
//! **The real fix**: have `verus_ensures!`'s own expansion wrap its
//! content in a fresh, *nested* `verus_builtin_macros::verus! { .. }`
//! invocation of its own, and call the macro from *outside* any enclosing
//! `verus! {}` block (see `EnsuresBlue`'s call site, below the main block
//! this file's other items live in, not inside it). A `verus! { .. }`
//! invocation is, syntactically, just an ordinary proc-macro call as far
//! as plain `rustc` macro expansion is concerned — its `{ .. }` body is
//! opaque token soup the *invoked* macro owns interpretive rights over,
//! not something `rustc`'s item grammar tries to validate up front the
//! way it does for a `macro_rules!` macro's plain output. Multiple
//! `verus! {}` invocations coexisting in one file/module is itself
//! unremarkable (confirmed, not just assumed) — every item any of them
//! produces is an ordinary named item in the enclosing module afterward,
//! visible to every other item regardless of which `verus! {}` invocation
//! (or macro invocation of one) produced it, matching how ordinary Rust
//! items resolve across `impl` blocks generally.
//!
//! **Not assumed to work just because `macro_rules!` macros appear inside
//! `verus_code!` in Verus's own test suite** (`rust_verify_test/tests/
//! regression.rs`'s `fields_from_macros_not_treated_as_distinct_
//! identifiers`, `nested_items.rs`'s `test_macro_item`) — every real
//! example found there expands to plain *exec* statements/expressions
//! inside a function body, not top-level items (`spec fn`, `impl`) at
//! module scope carrying Verus-specific attributes; that gap between
//! "confirmed to work in a function body" and "needed to work at module
//! scope, generating an `impl`" is exactly what the rejection above
//! surfaced. Checked directly rather than assumed to generalize.
//!
//! **Verified non-vacuous**, same discipline as every other case: a real
//! bug (`result.is_err()` swapped in for `result.is_ok()` in the macro
//! invocation's own predicate) produced a real, precise `postcondition
//! not satisfied` failure at `EnsuresBlue::ensures(..)`'s own call site,
//! confirming the macro-generated spec companion is a real, checked
//! definition, not inert boilerplate — reverted and re-verified clean.

use verus_builtin_macros::verus;

use crate::{Ensures, Evidence, Witness};

use super::support::GalleryVerifier;

/// The real Verus-side counterpart to `amenable_kani::rust_std::macros::
/// kani_ensures!`: generates the mechanical `Ensures<$verifier>` wiring
/// (spec companion + exec body + `when_used_as_spec` bridge) this crate's
/// `gallery::ensures_contract_bound`/`gallery::stoplight_exchange` first
/// proved out by hand. Unlike `kani_ensures!`, takes an explicit
/// `$verifier` type: `amenable_kani` has one canonical `KaniVerifier`,
/// but every gallery case in this crate defines its own local
/// `GalleryVerifier` (see `gallery::evidence_self_referential_root`'s own
/// doc comment for why), so there is no single crate-wide default to
/// hardcode the way `kani_ensures!` hardcodes `crate::KaniVerifier`.
/// No `evidence`-id/registry argument (unlike `kani_ensures!`'s own
/// `$evidence:literal`) — `amenable_verus` has no `inventory`-backed
/// registry to feed at all yet (`VERUS_EXCHANGE_PROOF_DERIVATION_PLAN.md`'s
/// own open question), so there is nothing real to register today.
macro_rules! verus_ensures {
    ($ty:ty, $verifier:ty, $spec_fn:ident, $param_ty:ty, |$param:pat_param| $expr:expr) => {
        verus_builtin_macros::verus! {
            pub open spec fn $spec_fn($param: $param_ty) -> bool {
                $expr
            }

            impl Ensures<$verifier> for $ty {
                type Input = $param_ty;
                type Bound = bool;

                #[verifier::when_used_as_spec($spec_fn)]
                fn ensures($param: $param_ty) -> bool {
                    $expr
                }
            }
        }
    };
}

verus! {

pub struct EnsuresBlue;

impl Evidence for EnsuresBlue {
    type Basis = Self;
    type Audit = ();

    fn basis() -> Self::Basis {
        EnsuresBlue
    }

    fn audit(&self) -> Self::Audit {}

    fn is_root() -> bool {
        true
    }
}

impl Witness<GalleryVerifier> for EnsuresBlue {
    type SupportingEvidence = Self;
    type ProofArtifact = ();

    fn proof() -> Self::ProofArtifact {}
}

/// The real, load-bearing check: does a genuine `ensures(...)` clause
/// resolve `EnsuresBlue::ensures(..)` to the macro-generated spec
/// companion? See `gallery::ensures_contract_bound::make_green`'s own
/// doc comment for why this returns the bare success type and wraps it
/// in `Ok(..)` inside the `ensures(...)` clause itself, rather than
/// `Result<_, ()>` (a real, separate clippy lint under plain `cargo
/// clippy`, not a Verus concern).
pub fn make_blue() -> (result: EnsuresBlue)
    ensures
        EnsuresBlue::ensures(Ok(result)),
{
    EnsuresBlue
}

} // verus!

verus_ensures!(
    EnsuresBlue,
    GalleryVerifier,
    ensures_blue_ok_spec,
    Result<EnsuresBlue, ()>,
    |result| result.is_ok()
);
