//! Gallery case: the GAAP ledger worked example
//! (`amenable_kani::ledger`/`amenable_creusot::ledger`) under Verus --
//! `Ledger::validate`'s/`::commit`'s real bodies, captured verbatim by
//! `#[amenable_derive::exchange(..)]` the same way `gallery::
//! stoplight_exchange`'s three edges are, not hand-copied. Direct
//! continuation of `GAAP_LEDGER_PLAN.md`'s Step 4, redirected mid-flight:
//! the plan's own original Step 4 text described hand-mirroring
//! `stoplight_exchange.rs`'s *pre-codegen* shape (a real, now-outdated
//! plan of record) -- corrected before any of it was written: "by hand
//! is the wrong approach, use the derives." This file follows
//! `stoplight_exchange.rs`'s *current*, post-codegen shape instead: real
//! `verus_ensures!`/`crate::exchange_support::verus_exchange!` macros,
//! the latter's call sites generated by `amenable::
//! emit-verus-exchange-companions` from the same `amenable_core::
//! ExchangeEdgeRecord` registry Creusot's own companions read.
//!
//! **The first genuinely non-trivial Verus `ensures` clause in this
//! gallery.** Every `Stoplight` edge only ever proves `result.is_ok()`
//! (zero-field states, no branching that could fail); `Ledger::validate`
//! can fail for a real reason, and its postcondition has to say exactly
//! which one -- matching the real Kani biconditional
//! (`amenable_kani::ledger::Validated::validate_ensures`) and the real
//! Creusot predicate (`amenable_creusot::ledger::validated_holds`)
//! exactly, the same claim proven a third way.
//!
//! **A fresh, self-contained mirror, not a shared one.** Every gallery
//! case defines its own `GalleryVerifier`/evidence markers/tokens (see
//! `gallery::evidence_self_referential_root`'s own doc comment for why)
//! -- this file's `Pending`/`Validated`/`Committed` are a *different*,
//! locally-defined concrete type from `stoplight_exchange.rs`'s own
//! `Green`/`Yellow`/`Red`, even though the underlying pattern (root
//! claims, `Established`-shaped sidecar) is identical. `verus
//! --crate-type=lib` never resolves an ordinary Cargo dependency at all
//! (see this crate's own `lib.rs` doc comment) -- unlike `amenable_
//! creusot`, which really does depend on `amenable_gaap` and implements
//! `Witness<CreusotVerifier>` directly on the real `Validated`/
//! `Committed` types, there is no "real dependency, no mirror" option
//! for Verus, ever. This mirror simplifies `amenable_gaap::AccountId`'s
//! real `Uuid`-backed identity down to a bare `u64` (matching `amenable_
//! creusot::ledger`'s own sanitized-mirror choice, for the same reason:
//! the real claim only needs *some* comparable identity type) --
//! `TransferPayload::from()`/`::to()` return the bare `u64` directly
//! (not a wrapping `AccountId`), since the real captured body never
//! names `AccountId` as a type, only ever compares what those two
//! methods return.
//!
//! **Scope matches `amenable_creusot::ledger`'s own exactly**: `Pending
//! -> Validated` and `Validated -> Committed` only, not `reject`/
//! `rollback` (`Rejected<Pending>`/`Rejected<Validated>`) -- both are
//! legitimately trivial (`result.is_ok()`) on every backend already
//! proving them, and connecting them here would be real, not free, work
//! for no new proof content. Left for a future pass, matching `GAAP_
//! LEDGER_PLAN.md`'s own "one real example by hand first" discipline.
//!
//! ## Real findings along the way, none assumed
//!
//! **A real macro-hygiene gap, the first captured body to hit it.**
//! `crate::exchange_support::verus_exchange!`'s template hardcoded
//! `fn exchange(&self, ..)`, exactly like `$input_param` used to before
//! `gallery::exchange_macro_generated` found and fixed that class of bug
//! for parameter names -- but `self` was never fixed the same way, since
//! no captured body before `validate`'s own ever referenced `self`
//! inside its own text (every `Stoplight` edge's real body happens not
//! to). `self.check_sufficient_funds(..)` inside this file's own
//! generated `validate.rs` produced a real "self value is a keyword
//! only available in methods with a self parameter" error -- standard
//! mixed-site hygiene, just never previously triggered: `self` as
//! hardcoded in the macro *template* (`exchange_support.rs`) is a
//! different syntactic identifier from `self` as written in `$body`
//! (this file's own generated companion), even though both are the same
//! keyword. Fixed the identical way `$input_param` was: the receiver
//! name is now itself a macro argument (`$self_param:ident`), always
//! invoked with the literal token `self` by `amenable::
//! verus_exchange_export`'s own `render_companion` -- see that
//! function's own doc comment for the full account.
//!
//! **Two real Verus-translator gaps in the captured body itself,
//! neither previously exercised.** `.map_err(TransferError::
//! NegativeAmount)` (a bare tuple-variant constructor used as a
//! function value) and `.map_err(|(balance, required)| ..)` (a
//! destructuring closure parameter) each produced a real "does not yet
//! support" error, confirmed against the real toolchain. Fixed at the
//! source, in `amenable_kani::ledger` itself, not worked around here:
//! two small, real, `#[cfg]`-free helper methods (`Ledger::
//! negative_amount`/`::insufficient_funds`) replace both call sites --
//! see their own doc comments for why a closure wrapping the
//! constructor was tried and rejected too (a real, un-`#[allow]`-able
//! `clippy::redundant_closure` failure).
//!
//! **`Result::map_err`'s own `vstd` spec is opaque by design, not a
//! gap.** Once the translator errors above were fixed, `validate`'s own
//! postcondition still failed to prove at both `Err` exit points --
//! `vstd::std_specs::result`'s real `map_err` spec states its
//! postcondition purely in terms of `op.ensures(..)`, so a helper
//! function with no declared `ensures` of its own (as `negative_amount`/
//! `insufficient_funds` originally were, matching their real Kani
//! counterparts, which need none) leaves Verus knowing nothing at all
//! about the mapped result. Every accessor and constructor the captured
//! body chains through needed the same real `ensures` added for the
//! identical reason -- ordinary modular verification, not a translator
//! limitation: `Amount::value`, `TransferPayload::from`/`::to`/
//! `::amount`, `Sidecar::primary`, and `Transfer::new` all needed one
//! before `validate`'s own success-path postcondition could be proven
//! at its final `Ok(Transfer::new(..))` return.
//!
//! **`i128`, not `int` or `wrapping_*`, for `Committed`'s claim.** See
//! that `verus_ensures!` call's own comment for the full account: `as
//! int` fails because the macro's `$expr` is shared between a spec fn
//! and an exec fn; `wrapping_neg`/`wrapping_add` fail because `vstd`
//! carries no specification for either.
//!
//! **`GAAP_LEDGER_PLAN.md`'s Step 5, added later.** `Validated`'s/
//! `Committed`'s own claims originally hand-composed their arithmetic
//! directly; now they call through real, local `AmountPositive`/
//! `SufficientFunds`/`AccountsDistinct`/`BalancedEntries` mirror types'
//! own `Ensures<GalleryVerifier>` impls instead -- the same retrofit
//! already done on Kani (`amenable_kani::ledger`) and Creusot
//! (`amenable_creusot::ledger`'s own `_holds` predicates), closing the
//! identical gap here. A third real "no general patterns" hit building
//! this: `SufficientFunds`'s/`AccountsDistinct`'s own `verus_ensures!`
//! calls first used destructuring params (`|(balance, amount)| ..`),
//! rejected the same way `Ledger::insufficient_funds`'s own doc comment
//! already documents for a closure parameter -- fixed by indexing a
//! plain tuple parameter (`input.0`/`.1`) instead, matching that fix
//! exactly, just one call shape over: a bare parameter to a function
//! `verus_ensures!` itself generates, not a closure this file writes
//! directly.
//!
//! ## Verified non-vacuous
//!
//! `cargo run -p amenable --features verus -- emit-verus-exchange-
//! companions` then `verus --crate-type=lib crates/amenable_verus/src/
//! lib.rs`: **478 verified, 0 errors** (up from 458 before Step 5's four
//! new contract-type impls). A real, injected bug (`AmountPositive`'s
//! own claim loosened from `amount > 0` to `amount > 1_000_000`)
//! produced a precise, real `postcondition not satisfied` failure at
//! the exact generated `Ok(Transfer::new(..))` return, confirming the
//! claim is real and checked, not vacuous -- reverted and re-verified
//! clean afterward.

use verus_builtin_macros::verus;
#[allow(unused_imports)]
use vstd::prelude::*;

use crate::exchange_support::{verus_ensures, verus_sidecar};
use crate::{Establish, Evidence, ProofToken, Sidecar, Verifier, Witness};
// `#[cfg(verus_keep_ghost)]`-gated, matching `amenable_core::evidence`'s
// own precedent: `AmountPositive::ensures(..)` (etc., below) resolves
// fine under ordinary `cargo check`/clippy without this import (`Type::
// trait_fn()` path syntax doesn't require the trait in scope the way
// `.method()` calls do), but real `verus`'s own driver -- which
// unconditionally sets `--cfg verus_keep_ghost` -- needs it, confirmed
// against the real toolchain: a real "function or associated item
// `ensures` not found" error without it.
#[cfg(verus_keep_ghost)]
use crate::Ensures;

verus! {

pub struct GalleryVerifier;

impl Verifier for GalleryVerifier {
    type Metadata = GalleryVerifierMetadata;

    fn name() -> &'static str {
        "gallery"
    }
}

#[derive(Default)]
pub struct GalleryVerifierMetadata;

#[verifier::external]
impl crate::Provenance for GalleryVerifierMetadata {
    type MetadataIter = std::vec::IntoIter<crate::MetadataEntry>;

    fn metadata(&self) -> Self::MetadataIter {
        Vec::new().into_iter()
    }
}

/// Local mirrors of `amenable_gaap::contracts::{AmountPositive,
/// SufficientFunds, AccountsDistinct, BalancedEntries}` -- `verus
/// --crate-type=lib` resolves no extern crate at all (this crate's own
/// `lib.rs` doc comment explains why), so, matching every other type in
/// this file, these can't be the real types either. `GAAP_LEDGER_
/// PLAN.md`'s Step 5: these four back real `Ensures<GalleryVerifier>`
/// impls (below, past the `verus! {}` block, next to `Validated`'s/
/// `Committed`'s own `verus_ensures!` calls, which now call through
/// them instead of restating the arithmetic) -- the same real gap
/// closed on Kani and Creusot, previously open here too. `Evidence`/
/// `Witness<GalleryVerifier>` still needed even though nothing
/// establishes a token *from* any of these four: `Ensures<V>: Witness<
/// V>` is a hard supertrait bound, so an `Ensures` impl can't exist
/// without one, matching `Pending`'s own trivial `Witness` impl right
/// below for the identical structural reason.
pub struct AmountPositive;

impl Evidence for AmountPositive {
    type Basis = Self;
    type Audit = ();

    fn basis() -> Self::Basis {
        AmountPositive
    }

    fn audit(&self) {}

    fn is_root() -> bool {
        true
    }
}

impl Witness<GalleryVerifier> for AmountPositive {
    type SupportingEvidence = Self;
    type ProofArtifact = ();

    fn proof() -> Self::ProofArtifact {}
}

pub struct SufficientFunds;

impl Evidence for SufficientFunds {
    type Basis = Self;
    type Audit = ();

    fn basis() -> Self::Basis {
        SufficientFunds
    }

    fn audit(&self) {}

    fn is_root() -> bool {
        true
    }
}

impl Witness<GalleryVerifier> for SufficientFunds {
    type SupportingEvidence = Self;
    type ProofArtifact = ();

    fn proof() -> Self::ProofArtifact {}
}

pub struct AccountsDistinct;

impl Evidence for AccountsDistinct {
    type Basis = Self;
    type Audit = ();

    fn basis() -> Self::Basis {
        AccountsDistinct
    }

    fn audit(&self) {}

    fn is_root() -> bool {
        true
    }
}

impl Witness<GalleryVerifier> for AccountsDistinct {
    type SupportingEvidence = Self;
    type ProofArtifact = ();

    fn proof() -> Self::ProofArtifact {}
}

pub struct BalancedEntries;

impl Evidence for BalancedEntries {
    type Basis = Self;
    type Audit = ();

    fn basis() -> Self::Basis {
        BalancedEntries
    }

    fn audit(&self) {}

    fn is_root() -> bool {
        true
    }
}

impl Witness<GalleryVerifier> for BalancedEntries {
    type SupportingEvidence = Self;
    type ProofArtifact = ();

    fn proof() -> Self::ProofArtifact {}
}

/// The transfer is awaiting validation -- a root state claim, asserted
/// rather than derived, matching `amenable_gaap::Pending`'s own real
/// doc comment: every `Transfer` starts here, and starting here is
/// asserted by construction, not proven.
pub struct Pending;

impl Evidence for Pending {
    type Basis = Self;
    type Audit = ();

    fn basis() -> Self::Basis {
        Pending
    }

    fn audit(&self) {}

    fn is_root() -> bool {
        true
    }
}

/// Hand-written, matching `amenable_kani::ledger::Pending`'s own
/// `Witness<KaniVerifier>` impl exactly (see its own doc comment):
/// unlike `Validated`/`Committed`, which get their `Witness<
/// GalleryVerifier>` impl "for free" from `verus_exchange!` (each
/// targets one as its edge's own evidence), nothing in this worked
/// example's scope ever targets `Pending` -- a transfer only ever
/// starts there, never returns to it -- so nothing generates one.
/// Honestly trivial: there is no computation to prove about the fact
/// that a new transfer starts `Pending`.
impl Witness<GalleryVerifier> for Pending {
    type SupportingEvidence = Self;
    type ProofArtifact = ();

    fn proof() -> Self::ProofArtifact {}
}

/// The transfer has been validated -- see [`Pending`] for why this is a
/// root claim, not a derived one, even though in practice a transfer
/// only reaches `Validated` via a proven `Pending -> Validated`
/// exchange.
pub struct Validated;

impl Evidence for Validated {
    type Basis = Self;
    type Audit = ();

    fn basis() -> Self::Basis {
        Validated
    }

    fn audit(&self) {}

    fn is_root() -> bool {
        true
    }
}

/// The transfer has been committed -- see [`Pending`].
pub struct Committed;

impl Evidence for Committed {
    type Basis = Self;
    type Audit = ();

    fn basis() -> Self::Basis {
        Committed
    }

    fn audit(&self) {}

    fn is_root() -> bool {
        true
    }
}

// `PendingToken`/`ValidatedToken`/`CommittedToken` and their `ProofToken`/
// `Establish<_, GalleryVerifier>` impls used to be hand-written here --
// see `GAAP_LEDGER_PLAN.md`'s Step 8: they're now generated, `include!`d
// near the bottom of this file alongside `validate.rs`/`commit.rs` (see
// that `include!`'s own comment for exactly why it has to live *outside*
// this file's own `verus! { .. }` block, not in-line here).

/// Sanitized mirror of `amenable_gaap::Amount` -- the real captured body
/// calls `.amount().value()`, so this needs the same two-method chain,
/// not just a bare `i64`.
#[derive(Clone, Copy)]
pub struct Amount(pub i64);

impl Amount {
    /// `ensures`, same real reason as every other accessor in this
    /// module: ordinary modular verification only exposes what a
    /// function's own `ensures` promises to its callers, so without
    /// this, nothing downstream could learn `.value()`'s actual result
    /// from `self`'s own field.
    pub fn value(&self) -> (result: i64)
        ensures
            result == self.0,
    {
        self.0
    }
}

/// Sanitized mirror of `amenable_gaap::TransferPayload` -- see this
/// file's own doc comment for why `from`/`to` are bare `u64`, not a
/// wrapping `AccountId`. `Clone`, not `Copy`, even though nothing here
/// stops it from being `Copy`: the real `TransferPayload` genuinely
/// isn't (a `String`-backed `AccountId`), and the real captured body's
/// own `.clone()` call needs a `Clone` type to land on -- deriving
/// `Copy` here too would make that same, legitimate `.clone()` trip a
/// real, un-`#[allow]`-able `clippy::clone_on_copy` failure.
#[derive(Clone)]
pub struct TransferPayload {
    pub from: u64,
    pub to: u64,
    pub amount: Amount,
}

impl TransferPayload {
    /// `ensures` throughout this impl: same real reason as [`Amount::
    /// value`].
    pub fn from(&self) -> (result: u64)
        ensures
            result == self.from,
    {
        self.from
    }

    pub fn to(&self) -> (result: u64)
        ensures
            result == self.to,
    {
        self.to
    }

    pub fn amount(&self) -> (result: Amount)
        ensures
            result.0 == self.amount.0,
    {
        self.amount
    }
}

/// Matches the real `amenable_gaap::TransferPayload`'s own `Evidence`
/// impl -- required for `Sidecar::Primary: Evidence`, below. No
/// `#[derive(Default)]`/`Self::default()` here: a `derive`d impl expands
/// *outside* the `verus! {}` block's own processing (derive macros run
/// before Verus ever sees the tokens), so Verus treats it as an
/// "external" function no in-block body can call -- confirmed against
/// the real toolchain, not assumed. A literal struct constructor sidesteps
/// the question entirely.
impl Evidence for TransferPayload {
    type Basis = Self;
    type Audit = ();

    fn basis() -> Self::Basis {
        TransferPayload {
            from: 0,
            to: 0,
            amount: Amount(0),
        }
    }

    fn audit(&self) {}
}

/// Sanitized mirror of `amenable_kani::ledger::TransferError`.
#[derive(Debug, Clone, Copy)]
pub enum TransferError {
    NegativeAmount(i64),
    InsufficientFunds { balance: i64, required: i64 },
    SameAccount,
}

/// Sanitized mirror of `amenable_kani::ledger::Ledger` -- the real
/// captured `validate`/`commit` bodies below call `self.check_
/// sufficient_funds(..)`/`Self::check_amount_positive(..)`, so this
/// needs the same two helper methods, each carrying the real
/// `ensures` clause `amenable_kani::ledger::Ledger::check_amount_
/// positive`/`::check_sufficient_funds` separately prove on the Kani
/// side and `amenable_creusot::ledger::check_amount_positive`/
/// `::check_sufficient_funds` separately prove on the Creusot side --
/// a real, hand-written claim, not generated: `verus_exchange!`'s
/// generated `Exchange::exchange` body only ever gets to use what a
/// called function's own `ensures` promises, never its actual body
/// (ordinary modular verification), so without these, `validate`'s
/// own `ensures` (`validated_ensures_spec`, below) could not be
/// proven at all.
pub struct Ledger {
    pub balance: i64,
}

impl Ledger {
    pub fn new(balance: i64) -> Self {
        Self { balance }
    }

    fn check_amount_positive(amount: i64) -> (result: Result<(), i64>)
        ensures
            match result {
                Ok(()) => amount > 0,
                Err(bad) => bad == amount && amount <= 0,
            },
    {
        if amount <= 0 { Err(amount) } else { Ok(()) }
    }

    fn check_sufficient_funds(&self, amount: i64) -> (result: Result<(), (i64, i64)>)
        ensures
            match result {
                Ok(()) => self.balance >= amount,
                Err((balance, required)) => balance < required && balance == self.balance && required == amount,
            },
    {
        if self.balance < amount { Err((self.balance, amount)) } else { Ok(()) }
    }

    /// Matches `amenable_kani::ledger::Ledger::negative_amount`'s own
    /// doc comment: the real captured `validate` body below calls
    /// `Self::negative_amount` rather than the bare `TransferError::
    /// NegativeAmount` tuple-variant constructor, since Verus does not
    /// (yet) support "using a datatype constructor as a function value"
    /// (confirmed against the real toolchain). `ensures`, unlike the
    /// real Kani copy (plain `fn`, no Verus-specific syntax at all): this
    /// gets called through `Result::map_err`, whose own `vstd` spec
    /// states its postcondition purely in terms of `op.ensures(..)` --
    /// with no `ensures` declared here, Verus knows nothing at all about
    /// what `map_err`'s own result actually contains, and `validate`'s
    /// own postcondition could not be proven at its `Err` exit points
    /// (confirmed the hard way: a real `postcondition not satisfied`
    /// failure pointing at exactly this `?` exit, before this was added).
    fn negative_amount(bad: i64) -> (result: TransferError)
        ensures
            result == TransferError::NegativeAmount(bad),
    {
        TransferError::NegativeAmount(bad)
    }

    /// Matches `amenable_kani::ledger::Ledger::insufficient_funds`'s own
    /// doc comment: the real captured `validate` body calls `Self::
    /// insufficient_funds` rather than a destructuring closure (`|
    /// (balance, required)| ..`), since Verus does not (yet) support a
    /// general pattern in a closure parameter position either. `ensures`
    /// for the same real reason `negative_amount`'s own doc comment
    /// explains.
    fn insufficient_funds(bad: (i64, i64)) -> (result: TransferError)
        ensures
            result == (TransferError::InsufficientFunds { balance: bad.0, required: bad.1 }),
    {
        TransferError::InsufficientFunds {
            balance: bad.0,
            required: bad.1,
        }
    }
}

} // verus!

// `Transfer<S, Token>` -- generated by `verus_sidecar!`, the same
// derive-equivalent macro `stoplight_exchange::Established<T, Token>`
// now uses. `primary = TransferPayload` selects the `Transfer<S, Token>`
// shape (proposition `S` is a separate, phantom generic parameter; the
// primary payload is its own concrete type), matching `amenable_kani::
// ledger::Transfer<S, Token>`'s real shape -- see `verus_sidecar!`'s own
// doc comment for the two shapes it supports. The generated field is
// always named `primary` (not `payload`): the real captured `validate`/
// `commit` bodies below only ever reach it through the `Sidecar::
// primary()` *method*, never a raw field access, so the internal field
// name is free to be uniform across both shapes; this file's own spec
// predicates (`validated_ensures_spec`/`committed_ensures_spec`, below)
// read `.primary` directly.
verus_sidecar!(Transfer<S, Token>, GalleryVerifier, primary = TransferPayload);

// `GAAP_LEDGER_PLAN.md`'s Step 5: real, atomic `Ensures<GalleryVerifier>`
// impls for each contract type -- `Validated`'s/`Committed`'s own
// `verus_ensures!` calls, below, call through these instead of
// restating the arithmetic, matching the identical retrofit already
// done on Kani (`amenable_kani::ledger`) and Creusot (`amenable_creusot
// ::ledger`'s own `_holds` predicates). Each contract type's own
// `ensures()` states the real claim directly (`amount > 0`, etc.), not
// wrapped in a `Result` the way `Ledger::check_amount_positive`'s own
// Kani proof is -- there is no separate "isolated proof function" layer
// on this backend to mirror the way `check_amount_positive`/`_holds`
// pairs exist on Kani/Creusot; the `Ensures` impl itself *is* the
// claim, checked wherever it's called through.
verus_ensures!(
    AmountPositive,
    GalleryVerifier,
    amount_positive_ensures_spec,
    i64,
    |amount| amount > 0
);

// `input.0`/`.1`, not a destructuring `|(balance, amount)|` -- Verus
// does not (yet) support a general pattern in this parameter position
// either (confirmed against the real toolchain: the identical "only
// variables are supported here" error `Ledger::insufficient_funds`'s
// own doc comment already found for a closure parameter), so this
// parameter stays a plain tuple, indexed rather than destructured.
verus_ensures!(
    SufficientFunds,
    GalleryVerifier,
    sufficient_funds_ensures_spec,
    (i64, i64),
    |input| input.0 >= input.1
);

// `input.0`/`.1`, same real reason as `SufficientFunds`'s own call,
// above.
verus_ensures!(
    AccountsDistinct,
    GalleryVerifier,
    accounts_distinct_ensures_spec,
    (u64, u64),
    |input| input.0 != input.1
);

// `i128`-widened, matching `Committed`'s own claim below (see its own
// comment for the full account of why `int`/`wrapping_*` don't work
// here).
verus_ensures!(
    BalancedEntries,
    GalleryVerifier,
    balanced_entries_ensures_spec,
    i64,
    |amount| {
        let amount = amount as i128;
        (-amount) + amount == 0
    }
);

// The contract type carries the bound; the generated `ensures(...)`
// clause (via `verus_exchange!`, included below) calls through it rather
// than restating it -- see `stoplight_exchange.rs`'s own doc comment for
// why this is hand-written, not generated: generation only ever covers
// the mechanical wiring around a claim, never the claim's own content.
// Matches `amenable_kani::ledger::Validated::validate_ensures`'s exact
// match-arm shape (including the real claim's own asymmetry -- the `Ok`
// arm doesn't restate `SufficientFunds`, only `AmountPositive`/
// `AccountsDistinct`) and `amenable_creusot::ledger::validated_holds`'s
// own Pearlite version of the identical claim -- both now call through
// the same four contract types' own `Ensures<V>` impls too, above.
verus_ensures!(
    Validated,
    GalleryVerifier,
    validated_ensures_spec,
    Result<Transfer<Validated, ValidatedToken>, TransferError>,
    |result| match result {
        Ok(validated) =>
            AmountPositive::ensures(validated.primary.amount.0)
                && AccountsDistinct::ensures((validated.primary.from, validated.primary.to)),
        Err(TransferError::NegativeAmount(bad)) => !AmountPositive::ensures(bad),
        Err(TransferError::InsufficientFunds { balance, required }) => {
            !SufficientFunds::ensures((balance, required))
        }
        Err(TransferError::SameAccount) => true,
    }
);

// Matches `amenable_kani::ledger::Committed::commit_ensures`'s claim
// (`debit + credit == 0`) and `amenable_creusot::ledger::
// balanced_entries_holds`'s own Pearlite version -- both now call
// through the same `BalancedEntries::ensures(..)` this does, above. Its
// own `i128`-widened body is where the real "not `int`, not
// `wrapping_*`" account lives now; kept here as a pointer rather than
// duplicated: `int`/`nat` are ghost-only, so `as int` fails once
// `verus_ensures!`'s `$expr` is spliced into the exec `fn ensures(..)`
// half of the pair, not just the spec half; `wrapping_neg`/`wrapping_
// add` fail separately because `vstd` carries no specification for
// either.
verus_ensures!(
    Committed,
    GalleryVerifier,
    committed_ensures_spec,
    Result<Transfer<Committed, CommittedToken>, TransferError>,
    |result| match result {
        Ok(committed) => BalancedEntries::ensures(committed.primary.amount.0),
        Err(_) => false,
    }
);

// `PendingToken`/`ValidatedToken`/`CommittedToken` and their `ProofToken`/
// `Establish<_, GalleryVerifier>` impls -- generated by `amenable emit-
// verus-gaap-tokens` from `amenable_core::ProofTokenMintRecord`
// (`GAAP_LEDGER_PLAN.md`'s Step 8), not hand-written. Placed *before* the
// two edge companions below since both name these types in their own
// signatures (`Transfer<Validated, ValidatedToken>`, ...). Real, not
// decorative, that its own generated content wraps itself in a fresh
// `verus_builtin_macros::verus! { .. }` rather than relying on this
// file's own block above: `verus! { .. }` is a function-like proc-macro,
// so it only ever sees tokens written literally inside its own braces --
// an `include!` sitting *inside* someone else's `verus! { .. }` block
// hands it an opaque, unexpanded `include!(..)` call it can't see
// through, confirmed against the real toolchain (a real "cannot use type
// PendingToken which is ignored because it is either declared outside
// the verus! macro" error, from the exact hand-written content this
// generated file replaces, when first tried in-line). `include!` here,
// at plain module scope matching `validate.rs`/`commit.rs`'s own
// precedent, sidesteps that: ordinary Rust item visibility doesn't care
// about textual position within a module, so `Pending`/`Validated`/
// `Committed`/`GalleryVerifier` (declared inside this file's own
// hand-written `verus! { .. }` block, above) stay reachable from here
// regardless. Regenerate with `just generate-verus-gaap-tokens` after
// changing a real `amenable_gaap` token type; do not hand-edit.
include!("generated/ledger_tokens.rs");

// The two `Witness<GalleryVerifier>`/`Exchange<..>` impls -- generated by
// `amenable::emit-verus-exchange-companions` from `amenable_core::
// ExchangeEdgeRecord`, not hand-written or hand-copied. `include!`, not
// `mod`: shares this file's own scope directly (`Pending`/`Validated`/
// `Committed`/`Transfer`/`TransferError`/`Ledger`/`GalleryVerifier`
// above, already in scope), matching `stoplight_exchange.rs`'s identical
// reason. Regenerate with `just generate-verus-exchange` after changing
// a real Kani-side transition; do not hand-edit the included files.
include!("generated/ledger_exchange/validate.rs");
include!("generated/ledger_exchange/commit.rs");
