//! Gallery case: the GAAP ledger worked example
//! (`amenable_kani::ledger`/`amenable_creusot::ledger`) under Verus --
//! `Ledger::validate`'s/`::commit`'s real bodies, captured verbatim by
//! `#[amenable_derive::exchange(..)]` the same way `gallery::
//! stoplight_exchange`'s three edges are, not hand-copied. Direct
//! continuation of `GAAP_LEDGER_PLAN.md`'s Step 4, redirected mid-flight:
//! the plan's own original Step 4 text described hand-mirroring
//! `stoplight_exchange.rs`'s *pre-codegen* shape (a real, now-outdated
//! plan of record) -- corrected before any of it was written: "by hand
//! is the wrong approach, use the derives." This file follows
//! `stoplight_exchange.rs`'s *current*, post-codegen shape instead: real
//! `verus_ensures!`/`crate::exchange_support::verus_exchange!` macros,
//! the latter's call sites generated by `amenable::
//! emit-verus-exchange-companions` from the same `amenable_core::
//! ExchangeEdgeRecord` registry Creusot's own companions read.
//!
//! **The first genuinely non-trivial Verus `ensures` clause in this
//! gallery.** Every `Stoplight` edge only ever proves `result.is_ok()`
//! (zero-field states, no branching that could fail); `Ledger::validate`
//! can fail for a real reason, and its postcondition has to say exactly
//! which one -- matching the real Kani biconditional
//! (`amenable_kani::ledger::Validated::validate_ensures`) and the real
//! Creusot predicate (`amenable_creusot::ledger::validated_holds`)
//! exactly, the same claim proven a third way.
//!
//! **A fresh, self-contained mirror, not a shared one.** Every gallery
//! case defines its own `GalleryVerifier`/evidence markers/tokens (see
//! `gallery::evidence_self_referential_root`'s own doc comment for why)
//! -- this file's `Pending`/`Validated`/`Committed` are a *different*,
//! locally-defined concrete type from `stoplight_exchange.rs`'s own
//! `Green`/`Yellow`/`Red`, even though the underlying pattern (root
//! claims, `Established`-shaped sidecar) is identical. `verus
//! --crate-type=lib` never resolves an ordinary Cargo dependency at all
//! (see this crate's own `lib.rs` doc comment) -- unlike `amenable_
//! creusot`, which really does depend on `amenable_gaap` and implements
//! `Witness<CreusotVerifier>` directly on the real `Validated`/
//! `Committed` types, there is no "real dependency, no mirror" option
//! for Verus, ever. This mirror simplifies `amenable_gaap::AccountId`'s
//! real `Uuid`-backed identity down to a bare `u64` (matching `amenable_
//! creusot::ledger`'s own sanitized-mirror choice, for the same reason:
//! the real claim only needs *some* comparable identity type) --
//! `TransferPayload::from()`/`::to()` return the bare `u64` directly
//! (not a wrapping `AccountId`), since the real captured body never
//! names `AccountId` as a type, only ever compares what those two
//! methods return.
//!
//! **Scope matches `amenable_creusot::ledger`'s own exactly**: `Pending
//! -> Validated` and `Validated -> Committed` only, not `reject`/
//! `rollback` (`Rejected<Pending>`/`Rejected<Validated>`) -- both are
//! legitimately trivial (`result.is_ok()`) on every backend already
//! proving them, and connecting them here would be real, not free, work
//! for no new proof content. Left for a future pass, matching `GAAP_
//! LEDGER_PLAN.md`'s own "one real example by hand first" discipline.
//!
//! ## Real findings along the way, none assumed
//!
//! **A real macro-hygiene gap, the first captured body to hit it.**
//! `crate::exchange_support::verus_exchange!`'s template hardcoded
//! `fn exchange(&self, ..)`, exactly like `$input_param` used to before
//! `gallery::exchange_macro_generated` found and fixed that class of bug
//! for parameter names -- but `self` was never fixed the same way, since
//! no captured body before `validate`'s own ever referenced `self`
//! inside its own text (every `Stoplight` edge's real body happens not
//! to). `self.check_sufficient_funds(..)` inside this file's own
//! generated `validate.rs` produced a real "self value is a keyword
//! only available in methods with a self parameter" error -- standard
//! mixed-site hygiene, just never previously triggered: `self` as
//! hardcoded in the macro *template* (`exchange_support.rs`) is a
//! different syntactic identifier from `self` as written in `$body`
//! (this file's own generated companion), even though both are the same
//! keyword. Fixed the identical way `$input_param` was: the receiver
//! name is now itself a macro argument (`$self_param:ident`), always
//! invoked with the literal token `self` by `amenable::
//! verus_exchange_export`'s own `render_companion` -- see that
//! function's own doc comment for the full account.
//!
//! **Two real Verus-translator gaps in the captured body itself,
//! neither previously exercised.** `.map_err(TransferError::
//! NegativeAmount)` (a bare tuple-variant constructor used as a
//! function value) and `.map_err(|(balance, required)| ..)` (a
//! destructuring closure parameter) each produced a real "does not yet
//! support" error, confirmed against the real toolchain. Fixed at the
//! source, in `amenable_kani::ledger` itself, not worked around here:
//! two small, real, `#[cfg]`-free helper methods (`Ledger::
//! negative_amount`/`::insufficient_funds`) replace both call sites --
//! see their own doc comments for why a closure wrapping the
//! constructor was tried and rejected too (a real, un-`#[allow]`-able
//! `clippy::redundant_closure` failure).
//!
//! **`Result::map_err`'s own `vstd` spec is opaque by design, not a
//! gap.** Once the translator errors above were fixed, `validate`'s own
//! postcondition still failed to prove at both `Err` exit points --
//! `vstd::std_specs::result`'s real `map_err` spec states its
//! postcondition purely in terms of `op.ensures(..)`, so a helper
//! function with no declared `ensures` of its own (as `negative_amount`/
//! `insufficient_funds` originally were, matching their real Kani
//! counterparts, which need none) leaves Verus knowing nothing at all
//! about the mapped result. Every accessor and constructor the captured
//! body chains through needed the same real `ensures` added for the
//! identical reason -- ordinary modular verification, not a translator
//! limitation: `Amount::value`, `TransferPayload::from`/`::to`/
//! `::amount`, `Sidecar::primary`, and `Transfer::new` all needed one
//! before `validate`'s own success-path postcondition could be proven
//! at its final `Ok(Transfer::new(..))` return.
//!
//! **`i128`, not `int` or `wrapping_*`, for `Committed`'s claim.** See
//! that `verus_ensures!` call's own comment for the full account: `as
//! int` fails because the macro's `$expr` is shared between a spec fn
//! and an exec fn; `wrapping_neg`/`wrapping_add` fail because `vstd`
//! carries no specification for either.
//!
//! ## Verified non-vacuous
//!
//! `cargo run -p amenable --features verus -- emit-verus-exchange-
//! companions` then `verus --crate-type=lib crates/amenable_verus/src/
//! lib.rs`: **458 verified, 0 errors.** A real, injected bug (`Validated`'s
//! `Ok` arm loosened from `amount > 0` to `amount > 1_000_000`) produced
//! a precise, real `postcondition not satisfied` failure at the exact
//! generated `Ok(Transfer::new(..))` return, confirming the claim is
//! real and checked, not vacuous -- reverted and re-verified clean
//! afterward.

use verus_builtin_macros::verus;
#[allow(unused_imports)]
use vstd::prelude::*;

use crate::exchange_support::verus_ensures;
use crate::{Establish, Evidence, ProofToken, Sidecar, Verifier, Witness};

verus! {

pub struct GalleryVerifier;

impl Verifier for GalleryVerifier {
    type Metadata = GalleryVerifierMetadata;

    fn name() -> &'static str {
        "gallery"
    }
}

#[derive(Default)]
pub struct GalleryVerifierMetadata;

#[verifier::external]
impl crate::Provenance for GalleryVerifierMetadata {
    type MetadataIter = std::vec::IntoIter<crate::MetadataEntry>;

    fn metadata(&self) -> Self::MetadataIter {
        Vec::new().into_iter()
    }
}

/// The transfer is awaiting validation -- a root state claim, asserted
/// rather than derived, matching `amenable_gaap::Pending`'s own real
/// doc comment: every `Transfer` starts here, and starting here is
/// asserted by construction, not proven.
pub struct Pending;

impl Evidence for Pending {
    type Basis = Self;
    type Audit = ();

    fn basis() -> Self::Basis {
        Pending
    }

    fn audit(&self) {}

    fn is_root() -> bool {
        true
    }
}

/// Hand-written, matching `amenable_kani::ledger::Pending`'s own
/// `Witness<KaniVerifier>` impl exactly (see its own doc comment):
/// unlike `Validated`/`Committed`, which get their `Witness<
/// GalleryVerifier>` impl "for free" from `verus_exchange!` (each
/// targets one as its edge's own evidence), nothing in this worked
/// example's scope ever targets `Pending` -- a transfer only ever
/// starts there, never returns to it -- so nothing generates one.
/// Honestly trivial: there is no computation to prove about the fact
/// that a new transfer starts `Pending`.
impl Witness<GalleryVerifier> for Pending {
    type SupportingEvidence = Self;
    type ProofArtifact = ();

    fn proof() -> Self::ProofArtifact {}
}

/// The transfer has been validated -- see [`Pending`] for why this is a
/// root claim, not a derived one, even though in practice a transfer
/// only reaches `Validated` via a proven `Pending -> Validated`
/// exchange.
pub struct Validated;

impl Evidence for Validated {
    type Basis = Self;
    type Audit = ();

    fn basis() -> Self::Basis {
        Validated
    }

    fn audit(&self) {}

    fn is_root() -> bool {
        true
    }
}

/// The transfer has been committed -- see [`Pending`].
pub struct Committed;

impl Evidence for Committed {
    type Basis = Self;
    type Audit = ();

    fn basis() -> Self::Basis {
        Committed
    }

    fn audit(&self) {}

    fn is_root() -> bool {
        true
    }
}

#[derive(Clone, Copy)]
pub struct PendingToken;

impl ProofToken for PendingToken {
    type Proposition = Pending;
}

#[derive(Clone, Copy)]
pub struct ValidatedToken;

impl ProofToken for ValidatedToken {
    type Proposition = Validated;
}

#[derive(Clone, Copy)]
pub struct CommittedToken;

impl ProofToken for CommittedToken {
    type Proposition = Committed;
}

impl Establish<PendingToken, GalleryVerifier> for Validated {
    type Token = ValidatedToken;

    fn establish(_credential: PendingToken) -> Self::Token {
        ValidatedToken
    }
}

impl Establish<ValidatedToken, GalleryVerifier> for Committed {
    type Token = CommittedToken;

    fn establish(_credential: ValidatedToken) -> Self::Token {
        CommittedToken
    }
}

/// Sanitized mirror of `amenable_gaap::Amount` -- the real captured body
/// calls `.amount().value()`, so this needs the same two-method chain,
/// not just a bare `i64`.
#[derive(Clone, Copy)]
pub struct Amount(pub i64);

impl Amount {
    /// `ensures`, same real reason as every other accessor in this
    /// module: ordinary modular verification only exposes what a
    /// function's own `ensures` promises to its callers, so without
    /// this, nothing downstream could learn `.value()`'s actual result
    /// from `self`'s own field.
    pub fn value(&self) -> (result: i64)
        ensures
            result == self.0,
    {
        self.0
    }
}

/// Sanitized mirror of `amenable_gaap::TransferPayload` -- see this
/// file's own doc comment for why `from`/`to` are bare `u64`, not a
/// wrapping `AccountId`. `Clone`, not `Copy`, even though nothing here
/// stops it from being `Copy`: the real `TransferPayload` genuinely
/// isn't (a `String`-backed `AccountId`), and the real captured body's
/// own `.clone()` call needs a `Clone` type to land on -- deriving
/// `Copy` here too would make that same, legitimate `.clone()` trip a
/// real, un-`#[allow]`-able `clippy::clone_on_copy` failure.
#[derive(Clone)]
pub struct TransferPayload {
    pub from: u64,
    pub to: u64,
    pub amount: Amount,
}

impl TransferPayload {
    /// `ensures` throughout this impl: same real reason as [`Amount::
    /// value`].
    pub fn from(&self) -> (result: u64)
        ensures
            result == self.from,
    {
        self.from
    }

    pub fn to(&self) -> (result: u64)
        ensures
            result == self.to,
    {
        self.to
    }

    pub fn amount(&self) -> (result: Amount)
        ensures
            result.0 == self.amount.0,
    {
        self.amount
    }
}

/// Matches the real `amenable_gaap::TransferPayload`'s own `Evidence`
/// impl -- required for `Sidecar::Primary: Evidence`, below. No
/// `#[derive(Default)]`/`Self::default()` here: a `derive`d impl expands
/// *outside* the `verus! {}` block's own processing (derive macros run
/// before Verus ever sees the tokens), so Verus treats it as an
/// "external" function no in-block body can call -- confirmed against
/// the real toolchain, not assumed. A literal struct constructor sidesteps
/// the question entirely.
impl Evidence for TransferPayload {
    type Basis = Self;
    type Audit = ();

    fn basis() -> Self::Basis {
        TransferPayload {
            from: 0,
            to: 0,
            amount: Amount(0),
        }
    }

    fn audit(&self) {}
}

/// Sanitized mirror of `amenable_kani::ledger::TransferError`.
#[derive(Debug, Clone, Copy)]
pub enum TransferError {
    NegativeAmount(i64),
    InsufficientFunds { balance: i64, required: i64 },
    SameAccount,
}

/// Sanitized mirror of `amenable_kani::ledger::Transfer<S, Token>` --
/// genuinely generic and genuinely implements `Sidecar<GalleryVerifier>`,
/// matching `stoplight_exchange::Established<T, Token>`'s own shape.
/// Public fields throughout (unlike the real, privacy-gated `Transfer`):
/// this mirror carries no separate real-vs-mirror trust boundary to
/// protect, the same reason `stoplight_exchange::Established::new` is
/// plain `pub fn`, not `pub(crate)`.
pub struct Transfer<S, Token> {
    pub payload: TransferPayload,
    pub token: Token,
    pub _state: std::marker::PhantomData<S>,
}

impl<S, Token> Transfer<S, Token> {
    /// `ensures`: a plain struct-literal body is not, by itself, enough
    /// for a *caller* to know its result's field values -- ordinary
    /// modular verification only exposes what a function's own `ensures`
    /// promises, confirmed the hard way (`validate`'s own success-path
    /// postcondition could not be proven at its final `Ok(Transfer::new(
    /// ..))` return until this was added, even though the constructor's
    /// body is this simple).
    pub fn new(payload: TransferPayload, token: Token) -> (result: Self)
        ensures
            result.payload == payload,
    {
        Self {
            payload,
            token,
            _state: std::marker::PhantomData,
        }
    }
}

impl<S, Token> Sidecar<GalleryVerifier> for Transfer<S, Token>
where
    S: Evidence + Witness<GalleryVerifier>,
    Token: ProofToken<Proposition = S> + Copy,
{
    type Primary = TransferPayload;
    type Proposition = S;
    type SidecarToken = Token;

    /// `ensures`, same real reason as [`Amount::value`]: `validate`'s
    /// own captured body calls `input.primary().clone()`, and without
    /// this, nothing downstream could learn the returned reference
    /// actually points at `self.payload`.
    fn primary(&self) -> (result: &Self::Primary)
        ensures
            result == &self.payload,
    {
        &self.payload
    }

    fn sidecar(&self) -> Self::SidecarToken {
        self.token
    }
}

/// Sanitized mirror of `amenable_kani::ledger::Ledger` -- the real
/// captured `validate`/`commit` bodies below call `self.check_
/// sufficient_funds(..)`/`Self::check_amount_positive(..)`, so this
/// needs the same two helper methods, each carrying the real
/// `ensures` clause `amenable_kani::ledger::Ledger::check_amount_
/// positive`/`::check_sufficient_funds` separately prove on the Kani
/// side and `amenable_creusot::ledger::check_amount_positive`/
/// `::check_sufficient_funds` separately prove on the Creusot side --
/// a real, hand-written claim, not generated: `verus_exchange!`'s
/// generated `Exchange::exchange` body only ever gets to use what a
/// called function's own `ensures` promises, never its actual body
/// (ordinary modular verification), so without these, `validate`'s
/// own `ensures` (`validated_ensures_spec`, below) could not be
/// proven at all.
pub struct Ledger {
    pub balance: i64,
}

impl Ledger {
    pub fn new(balance: i64) -> Self {
        Self { balance }
    }

    fn check_amount_positive(amount: i64) -> (result: Result<(), i64>)
        ensures
            match result {
                Ok(()) => amount > 0,
                Err(bad) => bad == amount && amount <= 0,
            },
    {
        if amount <= 0 { Err(amount) } else { Ok(()) }
    }

    fn check_sufficient_funds(&self, amount: i64) -> (result: Result<(), (i64, i64)>)
        ensures
            match result {
                Ok(()) => self.balance >= amount,
                Err((balance, required)) => balance < required && balance == self.balance && required == amount,
            },
    {
        if self.balance < amount { Err((self.balance, amount)) } else { Ok(()) }
    }

    /// Matches `amenable_kani::ledger::Ledger::negative_amount`'s own
    /// doc comment: the real captured `validate` body below calls
    /// `Self::negative_amount` rather than the bare `TransferError::
    /// NegativeAmount` tuple-variant constructor, since Verus does not
    /// (yet) support "using a datatype constructor as a function value"
    /// (confirmed against the real toolchain). `ensures`, unlike the
    /// real Kani copy (plain `fn`, no Verus-specific syntax at all): this
    /// gets called through `Result::map_err`, whose own `vstd` spec
    /// states its postcondition purely in terms of `op.ensures(..)` --
    /// with no `ensures` declared here, Verus knows nothing at all about
    /// what `map_err`'s own result actually contains, and `validate`'s
    /// own postcondition could not be proven at its `Err` exit points
    /// (confirmed the hard way: a real `postcondition not satisfied`
    /// failure pointing at exactly this `?` exit, before this was added).
    fn negative_amount(bad: i64) -> (result: TransferError)
        ensures
            result == TransferError::NegativeAmount(bad),
    {
        TransferError::NegativeAmount(bad)
    }

    /// Matches `amenable_kani::ledger::Ledger::insufficient_funds`'s own
    /// doc comment: the real captured `validate` body calls `Self::
    /// insufficient_funds` rather than a destructuring closure (`|
    /// (balance, required)| ..`), since Verus does not (yet) support a
    /// general pattern in a closure parameter position either. `ensures`
    /// for the same real reason `negative_amount`'s own doc comment
    /// explains.
    fn insufficient_funds(bad: (i64, i64)) -> (result: TransferError)
        ensures
            result == (TransferError::InsufficientFunds { balance: bad.0, required: bad.1 }),
    {
        TransferError::InsufficientFunds {
            balance: bad.0,
            required: bad.1,
        }
    }
}

} // verus!

// The contract type carries the bound; the generated `ensures(...)`
// clause (via `verus_exchange!`, included below) calls through it rather
// than restating it -- see `stoplight_exchange.rs`'s own doc comment for
// why this is hand-written, not generated: generation only ever covers
// the mechanical wiring around a claim, never the claim's own content.
// Matches `amenable_kani::ledger::Validated::validate_ensures`'s exact
// match-arm shape (including the real claim's own asymmetry -- the `Ok`
// arm doesn't restate `SufficientFunds`, only `AmountPositive`/
// `AccountsDistinct`) and `amenable_creusot::ledger::validated_holds`'s
// own Pearlite version of the identical claim.
verus_ensures!(
    Validated,
    GalleryVerifier,
    validated_ensures_spec,
    Result<Transfer<Validated, ValidatedToken>, TransferError>,
    |result| match result {
        Ok(validated) =>
            validated.payload.amount.0 > 0 && validated.payload.from != validated.payload.to,
        Err(TransferError::NegativeAmount(bad)) => bad <= 0,
        Err(TransferError::InsufficientFunds { balance, required }) => balance < required,
        Err(TransferError::SameAccount) => true,
    }
);

// Matches `amenable_kani::ledger::Committed::commit_ensures`'s claim
// (`debit + credit == 0`) and `amenable_creusot::ledger::
// balanced_entries_holds`'s own Pearlite version. Widened to `i128`, not
// `int`: `verus_ensures!`'s own expansion splices `$expr` into *both* a
// spec fn (where `int`/`nat` are fine) and the exec `fn ensures(..)`
// body `#[verifier::when_used_as_spec]` pairs it with (where they are
// not -- confirmed the hard way: `as int` here produced a real "can only
// be used in ghost code" error pointing at the exec copy, not the spec
// one). `wrapping_neg`/`wrapping_add` were tried next and also rejected
// -- `vstd` carries no specification for either (confirmed against the
// real toolchain: "core::num::impl&%3::wrapping_neg is not supported"),
// so Verus can prove nothing about their result at all. `i128` sidesteps
// both problems while staying in ordinary exec/spec-shared arithmetic:
// unlike the real Kani/Creusot proofs, which each needed a genuine
// `amount > 0` precondition to keep a plain `i64` `-amount` from
// overflow-panicking at `i64::MIN` (Kani's `#[kani::requires]`,
// Creusot's own `#[requires(amount@ > 0)]` on `check_commit_balances`),
// widening `amount` to `i128` *before* negating never overflows for any
// `i64` input, `i64::MIN` included (`i128`'s range is vastly larger than
// `i64`'s) -- so this claim needs no precondition at all, genuinely
// stronger than either of its siblings, not merely a workaround.
verus_ensures!(
    Committed,
    GalleryVerifier,
    committed_ensures_spec,
    Result<Transfer<Committed, CommittedToken>, TransferError>,
    |result| match result {
        Ok(committed) => {
            let amount = committed.payload.amount.0 as i128;
            (-amount) + amount == 0
        }
        Err(_) => false,
    }
);

// The two `Witness<GalleryVerifier>`/`Exchange<..>` impls -- generated by
// `amenable::emit-verus-exchange-companions` from `amenable_core::
// ExchangeEdgeRecord`, not hand-written or hand-copied. `include!`, not
// `mod`: shares this file's own scope directly (`Pending`/`Validated`/
// `Committed`/`Transfer`/`TransferError`/`Ledger`/`GalleryVerifier`
// above, already in scope), matching `stoplight_exchange.rs`'s identical
// reason. Regenerate with `just generate-verus-exchange` after changing
// a real Kani-side transition; do not hand-edit the included files.
include!("generated/ledger_exchange/validate.rs");
include!("generated/ledger_exchange/commit.rs");
