#[allow(
    unused_imports,
    reason = "vstd::prelude::* is unused under plain rustc (verus! {} erases real spec content); needed only when the real verus toolchain parses this file directly"
)]
use vstd::prelude::*;

use crate::exchange_support::{verus_ensures, verus_sidecar};
use crate::{Establish, ProofToken, Sidecar};
// `#[cfg(verus_keep_ghost)]`-gated, matching `amenable_core::evidence`'s
// own precedent: `AmountPositive::ensures(..)` (etc., below) resolves
// fine under ordinary `cargo check`/clippy without this import (`Type::
// trait_fn()` path syntax doesn't require the trait in scope the way
// `.method()` calls do), but real `verus`'s own driver -- which
// unconditionally sets `--cfg verus_keep_ghost` -- needs it, confirmed
// against the real toolchain: a real "function or associated item
// `ensures` not found" error without it.
#[cfg(verus_keep_ghost)]
use crate::Ensures;

use super::evidence_and_tokens::{Committed, Pending, Rejected, Validated};
use super::transfer_and_ledger::{Ledger, TransferError, TransferPayload};
use super::verifier_and_bounds::{
    AccountsDistinct, AmountPositive, BalancedEntries, GalleryVerifier, SufficientFunds,
};

// `Ledger::validate`'s own real captured body (`generated/ledger_exchange/
// validate.rs`, below) calls `Self::check_amount_positive::<V>(amount)`/
// `self.check_sufficient_funds::<V>(amount)` with an explicit turbofish
// -- `GAAP_LEDGER_PLAN.md`'s Step 7 made `Ledger`'s real methods generic
// over `V: amenable_core::Verifier` (`check_amount_positive`/`::check_
// sufficient_funds` above match that shape, matching `amenable_creusot::
// ledger`'s own identical fix and identical reasoning), so this captured
// text needs *something* named `V` in scope to resolve at all. Unlike
// Creusot's mirror, `fn exchange` itself can't gain a matching generic
// parameter here -- `Exchange::exchange` is a fixed-arity trait method
// (`amenable_core::exchange::Exchange::exchange(&self, input) -> ...`,
// zero generics), and Rust rejects an impl adding one (confirmed against
// the real toolchain: E0049, "method `exchange` has 1 type parameter but
// its trait declaration has 0"). A plain alias sidesteps that instead:
// `V` doesn't need to be a real generic parameter anywhere for the
// turbofish to resolve, only a nameable type -- `check_amount_positive`/
// `check_sufficient_funds` stay genuinely generic (called via `::<V>`),
// bound here to the one concrete verifier this whole gallery module ever
// uses.
type V = GalleryVerifier;

// `Transfer<S, Token>` -- generated by `verus_sidecar!`, the same
// derive-equivalent macro `stoplight_exchange::Established<T, Token>`
// now uses. `primary = TransferPayload` selects the `Transfer<S, Token>`
// shape (proposition `S` is a separate, phantom generic parameter; the
// primary payload is its own concrete type), matching `amenable_kani::
// ledger::Transfer<S, Token>`'s real shape -- see `verus_sidecar!`'s own
// doc comment for the two shapes it supports. The generated field is
// always named `primary` (not `payload`): the real captured `validate`/
// `commit` bodies below only ever reach it through the `Sidecar::
// primary()` *method*, never a raw field access, so the internal field
// name is free to be uniform across both shapes; this file's own spec
// predicates (`validated_ensures_spec`/`committed_ensures_spec`, below)
// read `.primary` directly.
verus_sidecar!(Transfer<S, Token>, GalleryVerifier, primary = TransferPayload);

// `GAAP_LEDGER_PLAN.md`'s Step 5: real, atomic `Ensures<GalleryVerifier>`
// impls for each contract type -- `Validated`'s/`Committed`'s own
// `verus_ensures!` calls, below, call through these instead of
// restating the arithmetic, matching the identical retrofit already
// done on Kani (`amenable_kani::ledger`) and Creusot (`amenable_creusot
// ::ledger`'s own `_holds` predicates). Each contract type's own
// `ensures()` states the real claim directly (`amount > 0`, etc.), not
// wrapped in a `Result` the way `Ledger::check_amount_positive`'s own
// Kani proof is -- there is no separate "isolated proof function" layer
// on this backend to mirror the way `check_amount_positive`/`_holds`
// pairs exist on Kani/Creusot; the `Ensures` impl itself *is* the
// claim, checked wherever it's called through.
verus_ensures!(
    AmountPositive,
    GalleryVerifier,
    amount_positive_ensures_spec,
    i64,
    |amount| amount > 0
);

// `input.0`/`.1`, not a destructuring `|(balance, amount)|` -- Verus
// does not (yet) support a general pattern in this parameter position
// either (confirmed against the real toolchain: the identical "only
// variables are supported here" error `Ledger::insufficient_funds`'s
// own doc comment already found for a closure parameter), so this
// parameter stays a plain tuple, indexed rather than destructured.
verus_ensures!(
    SufficientFunds,
    GalleryVerifier,
    sufficient_funds_ensures_spec,
    (i64, i64),
    |input| input.0 >= input.1
);

// `input.0`/`.1`, same real reason as `SufficientFunds`'s own call,
// above.
verus_ensures!(
    AccountsDistinct,
    GalleryVerifier,
    accounts_distinct_ensures_spec,
    (u64, u64),
    |input| input.0 != input.1
);

// `i128`-widened, matching `Committed`'s own claim below (see its own
// comment for the full account of why `int`/`wrapping_*` don't work
// here).
verus_ensures!(
    BalancedEntries,
    GalleryVerifier,
    balanced_entries_ensures_spec,
    i64,
    |amount| {
        let amount = amount as i128;
        (-amount) + amount == 0
    }
);

// The contract type carries the bound; the generated `ensures(...)`
// clause (via `verus_exchange!`, included below) calls through it rather
// than restating it -- see `stoplight_exchange.rs`'s own doc comment for
// why this is hand-written, not generated: generation only ever covers
// the mechanical wiring around a claim, never the claim's own content.
// Matches `amenable_kani::ledger::Validated::validate_ensures`'s exact
// match-arm shape (including the real claim's own asymmetry -- the `Ok`
// arm doesn't restate `SufficientFunds`, only `AmountPositive`/
// `AccountsDistinct`) and `amenable_creusot::ledger::validated_holds`'s
// own Pearlite version of the identical claim -- both now call through
// the same four contract types' own `Ensures<V>` impls too, above.
verus_ensures!(
    Validated,
    GalleryVerifier,
    validated_ensures_spec,
    Result<Transfer<Validated, ValidatedToken>, TransferError>,
    |result| match result {
        Ok(validated) =>
            AmountPositive::ensures(validated.primary.amount.0)
                && AccountsDistinct::ensures((validated.primary.from, validated.primary.to)),
        Err(TransferError::NegativeAmount(bad)) => !AmountPositive::ensures(bad),
        Err(TransferError::InsufficientFunds { balance, required }) => {
            !SufficientFunds::ensures((balance, required))
        }
        Err(TransferError::SameAccount) => true,
    }
);

// Matches `amenable_kani::ledger::Committed::commit_ensures`'s claim
// (`debit + credit == 0`) and `amenable_creusot::ledger::
// balanced_entries_holds`'s own Pearlite version -- both now call
// through the same `BalancedEntries::ensures(..)` this does, above. Its
// own `i128`-widened body is where the real "not `int`, not
// `wrapping_*`" account lives now; kept here as a pointer rather than
// duplicated: `int`/`nat` are ghost-only, so `as int` fails once
// `verus_ensures!`'s `$expr` is spliced into the exec `fn ensures(..)`
// half of the pair, not just the spec half; `wrapping_neg`/`wrapping_
// add` fail separately because `vstd` carries no specification for
// either.
verus_ensures!(
    Committed,
    GalleryVerifier,
    committed_ensures_spec,
    Result<Transfer<Committed, CommittedToken>, TransferError>,
    |result| match result {
        Ok(committed) => BalancedEntries::ensures(committed.primary.amount.0),
        Err(_) => false,
    }
);

// `reject`'s/`rollback`'s own claims are legitimately trivial (`result.
// is_ok()`), matching every `Stoplight` edge's own shape and `amenable_
// kani::ledger::Rejected::reject_ensures`'s/`::rollback_ensures`'s own
// real Kani claim exactly -- unlike Creusot (`amenable_creusot::ledger`'s
// own `Rejected<Pending>`/`Rejected<Validated>` `Witness<CreusotVerifier>`
// impls carry no `Ensures` claim at all, defaulting `creusot_ensures` to
// a bare `"true"`), `verus_exchange!`'s own template routes every edge's
// postcondition through `Ensures<V>` unconditionally, with no such
// default -- so a real, checked (if simple) claim is required here, not
// optional. `GAAP_LEDGER_PLAN.md`'s Step 7, revisited: connected on
// Creusot/Verus for the first time.
verus_ensures!(
    Rejected<Pending>,
    GalleryVerifier,
    rejected_from_pending_ensures_spec,
    Result<Transfer<Rejected<Pending>, RejectedFromPendingToken>, TransferError>,
    |result| result.is_ok()
);

verus_ensures!(
    Rejected<Validated>,
    GalleryVerifier,
    rejected_from_validated_ensures_spec,
    Result<Transfer<Rejected<Validated>, RejectedFromValidatedToken>, TransferError>,
    |result| result.is_ok()
);

// `PendingToken`/`ValidatedToken`/`CommittedToken` and their `ProofToken`/
// `Establish<_, GalleryVerifier>` impls -- generated by `amenable emit-
// verus-gaap-tokens` from `amenable_core::ProofTokenMintRecord`
// (`GAAP_LEDGER_PLAN.md`'s Step 8), not hand-written. Placed *before* the
// two edge companions below since both name these types in their own
// signatures (`Transfer<Validated, ValidatedToken>`, ...). Real, not
// decorative, that its own generated content wraps itself in a fresh
// `verus_builtin_macros::verus! { .. }` rather than relying on this
// file's own block above: `verus! { .. }` is a function-like proc-macro,
// so it only ever sees tokens written literally inside its own braces --
// an `include!` sitting *inside* someone else's `verus! { .. }` block
// hands it an opaque, unexpanded `include!(..)` call it can't see
// through, confirmed against the real toolchain (a real "cannot use type
// PendingToken which is ignored because it is either declared outside
// the verus! macro" error, from the exact hand-written content this
// generated file replaces, when first tried in-line). `include!` here,
// at plain module scope matching `validate.rs`/`commit.rs`'s own
// precedent, sidesteps that: ordinary Rust item visibility doesn't care
// about textual position within a module, so `Pending`/`Validated`/
// `Committed`/`GalleryVerifier` (declared inside this file's own
// hand-written `verus! { .. }` block, above) stay reachable from here
// regardless. Regenerate with `just generate-verus-gaap-tokens` after
// changing a real `amenable_gaap` token type; do not hand-edit.
include!("../generated/ledger_tokens.rs");

// The four `Witness<GalleryVerifier>`/`Exchange<..>` impls -- generated
// by `amenable::emit-verus-exchange-companions` from `amenable_core::
// ExchangeEdgeRecord`, not hand-written or hand-copied. `include!`, not
// `mod`: shares this file's own scope directly (`Pending`/`Validated`/
// `Committed`/`Rejected`/`Transfer`/`TransferError`/`Ledger`/
// `GalleryVerifier` above, already in scope), matching `stoplight_
// exchange.rs`'s identical reason. Regenerate with `just generate-verus-
// exchange` after changing a real Kani-side transition; do not hand-edit
// the included files.
include!("../generated/ledger_exchange/validate.rs");
include!("../generated/ledger_exchange/commit.rs");
include!("../generated/ledger_exchange/reject.rs");
include!("../generated/ledger_exchange/rollback.rs");
