//! Gallery case: the GAAP ledger worked example
//! (`amenable_kani::ledger`/`amenable_creusot::ledger`) under Verus --
//! `Ledger::validate`'s/`::commit`'s real bodies, captured verbatim by
//! `#[amenable_derive::exchange(..)]` the same way `gallery::
//! stoplight_exchange`'s three edges are, not hand-copied. Direct
//! continuation of `GAAP_LEDGER_PLAN.md`'s Step 4, redirected mid-flight:
//! the plan's own original Step 4 text described hand-mirroring
//! `stoplight_exchange.rs`'s *pre-codegen* shape (a real, now-outdated
//! plan of record) -- corrected before any of it was written: "by hand
//! is the wrong approach, use the derives." This file follows
//! `stoplight_exchange.rs`'s *current*, post-codegen shape instead: real
//! `verus_ensures!`/`crate::exchange_support::verus_exchange!` macros,
//! the latter's call sites generated by `amenable::
//! emit-verus-exchange-companions` from the same `amenable_core::
//! ExchangeEdgeRecord` registry Creusot's own companions read.
//!
//! **The first genuinely non-trivial Verus `ensures` clause in this
//! gallery.** Every `Stoplight` edge only ever proves `result.is_ok()`
//! (zero-field states, no branching that could fail); `Ledger::validate`
//! can fail for a real reason, and its postcondition has to say exactly
//! which one -- matching the real Kani biconditional
//! (`amenable_kani::ledger::Validated::validate_ensures`) and the real
//! Creusot predicate (`amenable_creusot::ledger::validated_holds`)
//! exactly, the same claim proven a third way.
//!
//! **A fresh, self-contained mirror, not a shared one.** Every gallery
//! case defines its own `GalleryVerifier`/evidence markers/tokens (see
//! `gallery::evidence_self_referential_root`'s own doc comment for why)
//! -- this file's `Pending`/`Validated`/`Committed` are a *different*,
//! locally-defined concrete type from `stoplight_exchange.rs`'s own
//! `Green`/`Yellow`/`Red`, even though the underlying pattern (root
//! claims, `Established`-shaped sidecar) is identical. `verus
//! --crate-type=lib` never resolves an ordinary Cargo dependency at all
//! (see this crate's own `lib.rs` doc comment) -- unlike `amenable_
//! creusot`, which really does depend on `amenable_gaap` and implements
//! `Witness<CreusotVerifier>` directly on the real `Validated`/
//! `Committed` types, there is no "real dependency, no mirror" option
//! for Verus, ever. This mirror simplifies `amenable_gaap::AccountId`'s
//! real `Uuid`-backed identity down to a bare `u64` (matching `amenable_
//! creusot::ledger`'s own sanitized-mirror choice, for the same reason:
//! the real claim only needs *some* comparable identity type) --
//! `TransferPayload::from()`/`::to()` return the bare `u64` directly
//! (not a wrapping `AccountId`), since the real captured body never
//! names `AccountId` as a type, only ever compares what those two
//! methods return.
//!
//! **Scope matches `amenable_creusot::ledger`'s own exactly**: `Pending
//! -> Validated` and `Validated -> Committed` only, not `reject`/
//! `rollback` (`Rejected<Pending>`/`Rejected<Validated>`) -- both are
//! legitimately trivial (`result.is_ok()`) on every backend already
//! proving them, and connecting them here would be real, not free, work
//! for no new proof content. Left for a future pass, matching `GAAP_
//! LEDGER_PLAN.md`'s own "one real example by hand first" discipline.
//!
//! ## Real findings along the way, none assumed
//!
//! **A real macro-hygiene gap, the first captured body to hit it.**
//! `crate::exchange_support::verus_exchange!`'s template hardcoded
//! `fn exchange(&self, ..)`, exactly like `$input_param` used to before
//! `gallery::exchange_macro_generated` found and fixed that class of bug
//! for parameter names -- but `self` was never fixed the same way, since
//! no captured body before `validate`'s own ever referenced `self`
//! inside its own text (every `Stoplight` edge's real body happens not
//! to). `self.check_sufficient_funds(..)` inside this file's own
//! generated `validate.rs` produced a real "self value is a keyword
//! only available in methods with a self parameter" error -- standard
//! mixed-site hygiene, just never previously triggered: `self` as
//! hardcoded in the macro *template* (`exchange_support.rs`) is a
//! different syntactic identifier from `self` as written in `$body`
//! (this file's own generated companion), even though both are the same
//! keyword. Fixed the identical way `$input_param` was: the receiver
//! name is now itself a macro argument (`$self_param:ident`), always
//! invoked with the literal token `self` by `amenable::
//! verus_exchange_export`'s own `render_companion` -- see that
//! function's own doc comment for the full account.
//!
//! **Two real Verus-translator gaps in the captured body itself,
//! neither previously exercised.** `.map_err(TransferError::
//! NegativeAmount)` (a bare tuple-variant constructor used as a
//! function value) and `.map_err(|(balance, required)| ..)` (a
//! destructuring closure parameter) each produced a real "does not yet
//! support" error, confirmed against the real toolchain. Fixed at the
//! source, in `amenable_kani::ledger` itself, not worked around here:
//! two small, real, `#[cfg]`-free helper methods (`Ledger::
//! negative_amount`/`::insufficient_funds`) replace both call sites --
//! see their own doc comments for why a closure wrapping the
//! constructor was tried and rejected too (a real, un-`#[allow]`-able
//! `clippy::redundant_closure` failure).
//!
//! **`Result::map_err`'s own `vstd` spec is opaque by design, not a
//! gap.** Once the translator errors above were fixed, `validate`'s own
//! postcondition still failed to prove at both `Err` exit points --
//! `vstd::std_specs::result`'s real `map_err` spec states its
//! postcondition purely in terms of `op.ensures(..)`, so a helper
//! function with no declared `ensures` of its own (as `negative_amount`/
//! `insufficient_funds` originally were, matching their real Kani
//! counterparts, which need none) leaves Verus knowing nothing at all
//! about the mapped result. Every accessor and constructor the captured
//! body chains through needed the same real `ensures` added for the
//! identical reason -- ordinary modular verification, not a translator
//! limitation: `Amount::value`, `TransferPayload::from`/`::to`/
//! `::amount`, `Sidecar::primary`, and `Transfer::new` all needed one
//! before `validate`'s own success-path postcondition could be proven
//! at its final `Ok(Transfer::new(..))` return.
//!
//! **`i128`, not `int` or `wrapping_*`, for `Committed`'s claim.** See
//! that `verus_ensures!` call's own comment for the full account: `as
//! int` fails because the macro's `$expr` is shared between a spec fn
//! and an exec fn; `wrapping_neg`/`wrapping_add` fail because `vstd`
//! carries no specification for either.
//!
//! **`GAAP_LEDGER_PLAN.md`'s Step 5, added later.** `Validated`'s/
//! `Committed`'s own claims originally hand-composed their arithmetic
//! directly; now they call through real, local `AmountPositive`/
//! `SufficientFunds`/`AccountsDistinct`/`BalancedEntries` mirror types'
//! own `Ensures<GalleryVerifier>` impls instead -- the same retrofit
//! already done on Kani (`amenable_kani::ledger`) and Creusot
//! (`amenable_creusot::ledger`'s own `_holds` predicates), closing the
//! identical gap here. A third real "no general patterns" hit building
//! this: `SufficientFunds`'s/`AccountsDistinct`'s own `verus_ensures!`
//! calls first used destructuring params (`|(balance, amount)| ..`),
//! rejected the same way `Ledger::insufficient_funds`'s own doc comment
//! already documents for a closure parameter -- fixed by indexing a
//! plain tuple parameter (`input.0`/`.1`) instead, matching that fix
//! exactly, just one call shape over: a bare parameter to a function
//! `verus_ensures!` itself generates, not a closure this file writes
//! directly.
//!
//! ## Verified non-vacuous
//!
//! `cargo run -p amenable --features verus -- emit-verus-exchange-
//! companions` then `verus --crate-type=lib crates/amenable_verus/src/
//! lib.rs`: **478 verified, 0 errors** (up from 458 before Step 5's four
//! new contract-type impls). A real, injected bug (`AmountPositive`'s
//! own claim loosened from `amount > 0` to `amount > 1_000_000`)
//! produced a precise, real `postcondition not satisfied` failure at
//! the exact generated `Ok(Transfer::new(..))` return, confirming the
//! claim is real and checked, not vacuous -- reverted and re-verified
//! clean afterward.
//!
//! Split by the worked example's own narrative phases: [`verifier_and_bounds`]
//! (`GalleryVerifier`, `GalleryVerifierMetadata`, and the
//! `AmountPositive`/`SufficientFunds`/`AccountsDistinct`/`BalancedEntries`
//! contract-bound markers), [`evidence_and_tokens`] (`Pending`/`Validated`/
//! `Committed`/`Rejected<T>`), [`transfer_and_ledger`] (`Amount`,
//! `TransferPayload`, `TransferError`, `Ledger`), and [`exchange_wiring`]
//! (the `V` alias, `verus_sidecar!`, every `verus_ensures!` call, and the
//! `generated/*.rs` `include!`s -- all deliberately outside any
//! `verus! {}` block, see this module's own doc comment above for why).
//! Each of the first three files carries its own independent `verus! {}`
//! block rather than sharing one across files -- confirmed against the
//! real `verus` toolchain, not assumed: cross-block references (e.g.
//! `evidence_and_tokens`'s `Validated` naming `verifier_and_bounds`'s
//! `GalleryVerifier`) verify cleanly.

/// `Pending`/`Validated`/`Committed`/`Rejected<T>`.
pub mod evidence_and_tokens;
/// The `V` alias, `verus_sidecar!`, every `verus_ensures!` call, and the
/// `generated/*.rs` `include!`s.
pub mod exchange_wiring;
/// `Amount`, `TransferPayload`, `TransferError`, `Ledger`.
pub mod transfer_and_ledger;
/// The `AmountPositive`/`SufficientFunds`/`AccountsDistinct`/
/// `BalancedEntries` contract-bound markers (re-exports `GalleryVerifier`
/// from `gallery::support` for its own sibling files).
pub mod verifier_and_bounds;
