//! Companion `#[verifier::external_trait_specification]`s for
//! `amenable_core`'s `Verifier`/`Evidence`/`ProofToken`/`Witness<V>`
//! family, needed by any real (not merely diagnostic) `Sidecar<V>`-based
//! proof under Verus. Real, permanent infrastructure, not a gallery
//! case: `gallery::proof_token_external_trait_bound` is where this
//! exact fix was discovered and its rationale is fully documented (four
//! distinct, real reasons, each confirmed against actual Verus output —
//! see that module's own doc comment); this module is the same fix,
//! extracted so every future real `Exchange`-shaped proof doesn't have
//! to duplicate it.
//!
//! Also carries `verus_ensures!` — the Verus-side counterpart to
//! `amenable_kani::rust_std::macros::kani_ensures!`, discovered and fully
//! documented (including a real, rejected first attempt) in
//! `gallery::ensures_macro_generated`; extracted here for the identical
//! "future real proof shouldn't have to duplicate this" reason. And
//! `verus_exchange!` — the Verus-side counterpart to `#[amenable_derive
//! ::exchange(..)]` (`EXCHANGE_PROOF_DERIVATION_PLAN.md`'s Step 3/7),
//! discovered and fully documented (including a real macro-hygiene fix)
//! in `gallery::exchange_macro_generated`.

use verus_builtin_macros::verus;

use crate::{Evidence, ProofToken, Verifier, Witness};

verus! {

/// Companion specification for the real, mod-included `Verifier` trait --
/// see this module's own doc comment for why every one of these four
/// exists.
#[verifier::external_trait_specification]
pub trait ExVerifier: 'static {
    /// The real trait this specification stands in for.
    type ExternalTraitSpecificationFor: Verifier;
}

/// Companion specification for the real, mod-included `Evidence` trait.
#[verifier::external_trait_specification]
pub trait ExEvidence {
    /// The real trait this specification stands in for.
    type ExternalTraitSpecificationFor: Evidence;
}

/// Companion specification for the real, mod-included `ProofToken` trait.
#[verifier::external_trait_specification]
pub trait ExProofToken {
    /// The real trait this specification stands in for.
    type ExternalTraitSpecificationFor: ProofToken;
    /// Mirrors `ProofToken::Proposition`, bound on `Evidence` to match the
    /// real trait's own declaration exactly.
    type Proposition: Evidence;
}

/// Companion specification for the real, mod-included (accommodation-
/// mirrored) `Witness<V>` trait.
#[verifier::external_trait_specification]
pub trait ExWitness<V: Verifier> {
    /// The real trait this specification stands in for.
    type ExternalTraitSpecificationFor: Witness<V>;
    /// Mirrors `Witness::SupportingEvidence`.
    type SupportingEvidence: Evidence;
    /// Mirrors `Witness::ProofArtifact`.
    type ProofArtifact;
}

} // verus!

/// Generates the mechanical `Ensures<$verifier>` wiring (spec companion +
/// exec body + `#[verifier::when_used_as_spec]` bridge) `gallery::
/// ensures_contract_bound`/`gallery::stoplight_exchange` first proved out
/// by hand, and `gallery::ensures_macro_generated` confirmed this shape
/// for — see that module's own doc comment for the real, rejected first
/// attempt (a `macro_rules!` macro invoked *inside* the surrounding
/// `verus! {}` block fails: `spec`/`open` are not plain Rust syntax, and
/// ordinary `rustc` macro expansion validates output against plain Rust
/// item grammar before Verus-specific processing is ever reachable) and
/// the real fix (wrap the macro's own output in a *nested* `verus! {}`
/// invocation, called from outside any enclosing one).
///
/// No `evidence`-id/registry argument (unlike `kani_ensures!`'s own
/// `$evidence:literal`) — `amenable_verus` has no `inventory`-backed
/// registry to feed at all yet (`VERUS_EXCHANGE_PROOF_DERIVATION_PLAN.md`'s
/// own open question), so there is nothing real to register today. Takes
/// an explicit `$verifier` type, unlike `kani_ensures!`'s hardcoded
/// `crate::KaniVerifier`: `amenable_kani` has one canonical verifier
/// marker, but this crate has none — every gallery case defines its own
/// local `GalleryVerifier` (see `gallery::evidence_self_referential_root`'s
/// own doc comment for why).
macro_rules! verus_ensures {
    ($ty:ty, $verifier:ty, $spec_fn:ident, $param_ty:ty, |$param:pat_param| $expr:expr) => {
        verus_builtin_macros::verus! {
            /// `$ty`'s own `Ensures<$verifier>` claim, generated by
            /// `verus_ensures!`.
            pub open spec fn $spec_fn($param: $param_ty) -> bool {
                $expr
            }

            impl crate::Ensures<$verifier> for $ty {
                type Input = $param_ty;
                type Bound = bool;

                #[verifier::when_used_as_spec($spec_fn)]
                fn ensures($param: $param_ty) -> bool {
                    $expr
                }
            }
        }
    };
}

pub(crate) use verus_ensures;

/// Generates the mechanical `Witness<$verifier>` impl (always this exact
/// trivial shape under Verus — there is no separate harness/artifact to
/// report; the proof *is* the `ensures` clause the SMT solver checks, not
/// a captured harness the way Kani's `CalculationProof` is) and the
/// `Exchange<$input_ty, $output_ty, $verifier>` impl, wired to whatever
/// `Ensures<$verifier>` impl `$evidence` already carries (from a
/// preceding [`verus_ensures!`] call, exactly as `amenable_kani::
/// stoplight` keeps `kani_ensures!` adjacent to but separate from
/// `#[amenable_derive::exchange(..)]`). `$body` — the real transition
/// logic, and the only real content here — is spliced in verbatim, never
/// reconstructed.
///
/// `$input_param` (the generated method's parameter *name*, not just its
/// type) is a real, required argument, not a hardcoded `input` — found
/// the hard way in `gallery::exchange_macro_generated`: an identifier
/// written literally in the macro's own template is a different
/// syntactic identifier from anything the caller writes in `$body`, even
/// spelled identically (standard `macro_rules!` mixed-site hygiene), so
/// the parameter name has to come from the same call-site tokens as its
/// uses inside `$body` for both to refer to the same binding.
///
/// Invoked *outside* any enclosing `verus! {}` block, for the identical
/// structural reason [`verus_ensures!`] requires it (see that macro's
/// own doc comment): its expansion wraps its content in a fresh, nested
/// `verus! {}` invocation of its own, and a `macro_rules!` macro's plain
/// output can't itself contain `spec`/`open`/`ensures` syntax the way a
/// directly-authored `verus! {}` body can.
macro_rules! verus_exchange {
    ($self_ty:ty, $self_param:ident, $input_param:ident: $input_ty:ty, $output_ty:ty, $error_ty:ty, $evidence:ty, $verifier:ty, $body:block) => {
        verus_builtin_macros::verus! {
            impl crate::Witness<$verifier> for $evidence {
                type SupportingEvidence = Self;
                type ProofArtifact = ();

                fn proof() -> Self::ProofArtifact {}
            }

            impl crate::Exchange<$input_ty, $output_ty, $verifier> for $self_ty {
                type Error = $error_ty;

                fn exchange(&$self_param, $input_param: $input_ty) -> (result: ::std::result::Result<$output_ty, $error_ty>)
                    ensures
                        <$evidence as crate::Ensures<$verifier>>::ensures(result),
                $body
            }
        }
    };
}

pub(crate) use verus_exchange;

/// Generates the `Sidecar<$verifier>`-carrier shape every real `Exchange`
/// edge needs (`Established<T, Token>`-style, where the primary payload
/// *is* the proposition, and `Transfer<S, Token>`-style, where the
/// proposition is a separate, phantom generic parameter and the primary
/// payload is its own concrete type) -- the `macro_rules!` counterpart to
/// `amenable_derive::Sidecar`, which generates the identical impl for
/// `amenable_kani`'s and `amenable_creusot`'s own real/mirror carrier
/// types. A proc-macro derive can't reach here at all (`amenable_verus`
/// resolves no extern crate under `verus --crate-type=lib`, this crate's
/// own `lib.rs` doc comment explains why), so this generates the struct
/// *and* the impl together from one invocation, rather than attaching to
/// an already-declared struct the way a derive does.
///
/// `primary()`/`new()` both carry a real `ensures` clause tying their
/// result back to the stored/passed field -- not optional polish: a real
/// `Exchange` edge whose postcondition inspects payload data (`gallery::
/// ledger_exchange`'s own `Validated`/`Committed` claims) needs both
/// before anything downstream can be proven at all, confirmed the hard
/// way building that module (see its own doc comment).
macro_rules! verus_sidecar {
    ($name:ident<$t:ident, $token:ident>, $verifier:ty) => {
        verus_builtin_macros::verus! {
            /// Sidecar carrier: the primary payload doubles as its own
            /// `Sidecar` proposition. Generated by `verus_sidecar!`.
            pub struct $name<$t, $token> {
                /// The primary payload, which is also the proposition.
                pub primary: $t,
                /// The proof token witnessing `primary`.
                pub token: $token,
            }

            impl<$t, $token> $name<$t, $token> {
                /// `ensures`, same real reason every accessor in a
                /// `verus_sidecar!`-generated carrier carries one: ordinary
                /// modular verification only exposes what a function's own
                /// `ensures` promises to its callers.
                pub fn new(primary: $t, token: $token) -> (result: Self)
                    ensures
                        result.primary == primary,
                {
                    Self { primary, token }
                }
            }

            impl<$t, $token> crate::Sidecar<$verifier> for $name<$t, $token>
            where
                $t: crate::Evidence + crate::Witness<$verifier>,
                $token: crate::ProofToken<Proposition = $t> + Clone,
            {
                type Primary = $t;
                type Proposition = $t;
                type SidecarToken = $token;

                fn primary(&self) -> (result: &Self::Primary)
                    ensures
                        result == &self.primary,
                {
                    &self.primary
                }

                fn sidecar(&self) -> Self::SidecarToken {
                    self.token.clone()
                }
            }
        }
    };
    ($name:ident<$s:ident, $token:ident>, $verifier:ty, primary = $primary_ty:ty) => {
        verus_builtin_macros::verus! {
            /// Sidecar carrier: the `Sidecar` proposition (`$s`) is a
            /// separate, phantom generic parameter from the primary
            /// payload's own concrete type. Generated by `verus_sidecar!`.
            pub struct $name<$s, $token> {
                /// The primary payload, distinct from the proposition type.
                pub primary: $primary_ty,
                /// The proof token witnessing the proposition.
                pub token: $token,
                /// Carries the proposition type parameter -- never a real
                /// runtime value.
                pub _state: ::core::marker::PhantomData<$s>,
            }

            impl<$s, $token> $name<$s, $token> {
                /// `ensures`, same real reason every accessor in a
                /// `verus_sidecar!`-generated carrier carries one.
                pub fn new(primary: $primary_ty, token: $token) -> (result: Self)
                    ensures
                        result.primary == primary,
                {
                    Self {
                        primary,
                        token,
                        _state: ::core::marker::PhantomData,
                    }
                }
            }

            impl<$s, $token> crate::Sidecar<$verifier> for $name<$s, $token>
            where
                $s: crate::Evidence + crate::Witness<$verifier>,
                $token: crate::ProofToken<Proposition = $s> + Clone,
            {
                type Primary = $primary_ty;
                type Proposition = $s;
                type SidecarToken = $token;

                fn primary(&self) -> (result: &Self::Primary)
                    ensures
                        result == &self.primary,
                {
                    &self.primary
                }

                fn sidecar(&self) -> Self::SidecarToken {
                    self.token.clone()
                }
            }
        }
    };
}

pub(crate) use verus_sidecar;

/// `macro_rules!` counterpart to `amenable_derive::StateMachine`
/// (`docs/STATE_MACHINE_DERIVATION_PLAN.md`) — a proc-macro derive can
/// never reach here at all, the identical reason `verus_sidecar!` exists
/// rather than reusing `#[derive(amenable_derive::Sidecar)]`: `verus
/// --crate-type=lib` resolves no external crate under any circumstances,
/// proc-macro or otherwise.
///
/// Unlike the proc-macro derive, this can't look up a declared state's
/// carrier type by name at expansion time — `macro_rules!` has no such
/// capability, only pattern matching and repetition — so `edges` names
/// each carrier explicitly per edge rather than through a `states`
/// table the way the derive's own `state(..)`/`edge(from, to)` split
/// does. `states` stays a plain name list, since `states()`'s own
/// report needs no carrier information at all.
///
/// No `#[verifier::..]`/`ensures`/`requires` anywhere in the generated
/// output, and deliberately not wrapped in a nested `verus_builtin_macros
/// ::verus! { .. }` invocation the way `verus_ensures!`/`verus_exchange!`
/// /`verus_sidecar!` all are: everything generated here — the checker
/// function, the static assertions, `StateMachine`'s own three methods
/// — is plain, unannotated Rust, exactly matching what `#[derive(
/// amenable_derive::StateMachine)]` generates for the other two
/// backends. Plain Rust needs no Verus-specific macro treatment; the
/// nested-`verus!{}` trick exists only for output that itself contains
/// `spec`/`open`/`ensures`/named-return-value syntax, none of which
/// appears here.
///
/// The static assertion shape (a shared top-level generic checker
/// function plus a plain `const _: fn() = checker::<..>;` reference per
/// edge, not a closure wrapping a nested function definition) matches
/// `docs/STATE_MACHINE_DERIVATION_PLAN.md`'s own Step 4 correction for
/// Creusot -- carried over here directly rather than risking the same
/// class of translator trouble a second time, even though it was never
/// actually reproduced under Verus.
///
/// `audit_surface()` is honestly, permanently empty: `amenable_verus`
/// has no `inventory`-backed registry to query at all (the identical
/// real gap `verus_ensures!`'s own doc comment already states), so
/// there is nothing real to report from here, ever.
macro_rules! verus_state_machine {
    (
        $self_ty:ty,
        $verifier:ty,
        states: [ $($state_name:literal),+ $(,)? ],
        edges: [ $(($from:literal, $from_carrier:ty, $to:literal, $to_carrier:ty)),+ $(,)? ] $(,)?
    ) => {
        #[doc(hidden)]
        fn __verus_state_machine_edge_checker<In, Out, T>()
        where
            In: crate::Sidecar<$verifier>,
            Out: crate::Sidecar<$verifier>,
            T: crate::Exchange<In, Out, $verifier>,
        {
        }

        $(
            const _: fn() =
                __verus_state_machine_edge_checker::<$from_carrier, $to_carrier, $self_ty>;
        )+

        impl crate::StateMachine<$verifier> for $self_ty {
            fn states() -> &'static [&'static str] {
                &[$($state_name),+]
            }

            fn transitions() -> &'static [crate::Transition] {
                const TRANSITIONS: &[crate::Transition] =
                    &[$(crate::Transition::new($from, $to)),+];
                TRANSITIONS
            }

            fn audit_surface() -> ::std::vec::Vec<crate::TransitionAudit> {
                ::std::vec::Vec::new()
            }
        }
    };
}

pub(crate) use verus_state_machine;
