//! Verus proof content for Rust standard-library carriers, plus the
//! `amenable_core` constitutional trait family itself.
//!
//! This crate contains *only* what `verus --crate-type=lib
//! crates/amenable_verus/src/lib.rs` needs to check: real `verus! { ... }`
//! spec functions, nothing else. Unlike `amenable_creusot` (which still
//! depends on `amenable_core`/`amenable_derive`, since `cargo creusot`
//! resolves ordinary Cargo dependencies), Verus is invoked as a bare
//! compiler over a single file tree — it never sees `Cargo.toml`, so it
//! cannot resolve `amenable_core`, `inventory`, or any proc-macro crate at
//! all as an ordinary Cargo dependency. Confirmed empirically: pointing
//! `verus` at the old, pre-split version of this crate (which depended on
//! all three) failed immediately with unresolved-crate errors, not proof
//! errors.
//!
//! So this crate's own `Cargo.toml` has exactly two dependencies —
//! `verus_builtin_macros` and `vstd` — mirroring `elicitation_verus`'s own
//! real, working structure (confirmed by reading `~/repos/elicitation/
//! crates/elicitation_verus/src/*.rs`: every file there is equally
//! dependency-free). But a Cargo dependency isn't the only way to bring
//! real source into a single-file-tree `verus` compilation: `#[path]` mod
//! declarations below pull in `amenable_core`'s own trait-family files
//! *verbatim*, unmodified, as ordinary modules of *this* crate — no
//! cross-crate `--extern` resolution needed, since Verus never sees more
//! than one crate's worth of `mod`-linked files regardless. Confirmed real
//! and load-bearing, not merely compiling: `gallery::
//! evidence_self_referential_root` verifies the real, unmodified
//! `Evidence`/`Witness`/`ProofToken`/`Establish` trait family — including
//! a genuine self-referential root — end to end (`351 verified, 0
//! errors`). Two files are the exception: `witness.rs` (mixes the
//! `Witness<V>` trait's own definition with `inventory`-dependent
//! registry code) and, since the metadata-trait split, `provenance.rs` /
//! `roles.rs` (the real `Provenance: Metadata` supertrait pulls in
//! `amenable_core::metadata`'s `Arc<dyn ...>` / `Any` machinery). Each
//! gets a hand-trimmed mirror instead — `witness_accommodation` and
//! `provenance_accommodation` — carrying just the trait mechanics this
//! crate's proofs actually name. `metadata_entry.rs` (the frozen
//! `MetadataEntry` snapshot type, no `Arc`/`Any`) is still included
//! verbatim, for `cert.rs`.
//!
//! `char` and `String` are real Rust primitives/std types with genuine
//! `vstd` spec support (`char as u32` casts and `String`'s `View` impl
//! giving `s@`/`s@.len()` both verified empirically against a real Verus
//! install) — no shadow-struct workaround needed for either, unlike most
//! of `elicitation_verus`'s own std-adjacent proofs (their `strings.rs`
//! deliberately avoids storing a real `String` field at all, citing "Verus
//! doesn't have specs for it" — true for their `Contract` wrapper types'
//! needs at the time, but `elicitation_verus`'s own `gallery::level5`
//! demonstrates the real `s@.len()` pattern this crate uses directly).

// No `#![forbid(unsafe_code)]` here, unlike every other crate in this
// workspace: confirmed against the real toolchain, not assumed --
// `pub assume_specification [..] (..) -> (..) ..;` (58 real sites,
// necessary for every external function this crate states a claim
// about, e.g. `<char as FromStr>::from_str`) expands under Verus's own
// compiler into constructs `forbid(unsafe_code)` genuinely rejects
// ("declaration of an unsafe function" / "usage of an unsafe block"),
// even though no `unsafe` keyword appears anywhere in this file's own
// source text. Nothing in this crate's real source ever writes `unsafe`
// by hand -- this is Verus's own internal expansion of a real,
// necessary, trust-declaring construct, invisible to plain `cargo
// build`/clippy.
#![warn(missing_docs)]

/// `#[derive(amenable_derive::Witness)]`-projected witness fixtures,
/// regenerated by `just emit-verus-witnesses` -- never hand-edit.
///
/// `#[allow(missing_docs)]`: an enum-shaped export's generated `*Result`
/// type has data-carrying variants, so `verus! {}` synthesizes a hidden
/// per-field projection accessor method (for its own `result->Variant_N`
/// pattern syntax) whose span lands on the enum, not on any AST node the
/// generated source declares -- so `verus`'s own `missing_docs` pass
/// (invisible to plain `cargo build`/clippy) has nothing to attach `///`
/// to. Confirmed against the real toolchain: no variant- or field-level
/// doc comment clears it, and `verus!` rejects an inner attr. Whole
/// subtree is generated; the silence doesn't reach hand-written code.
#[allow(
    missing_docs,
    reason = "verus! {} synthesizes undocumentable field-projection accessors on \
              enum-shaped witnesses' generated *Result types; no source AST node to \
              attach a doc to (real-toolchain-confirmed). Generated subtree only."
)]
pub mod derived_witness;
mod exchange_support;
pub mod gallery;
mod provenance_accommodation;
pub mod rust_std;
pub mod time;
mod witness_accommodation;

// The real, unmodified `amenable_core` trait-family source, mod-included
// verbatim -- see this file's own doc comment above for why `#[path]`
// achieves this without any Cargo dependency at all. Named to match
// `amenable_core::lib`'s own flat mod/pub-use structure exactly (not
// nested under a submodule) because these real files use bare `crate::X`
// imports, expecting to be compiled at a crate root shaped like their
// own.
#[path = "../../amenable_core/src/cert.rs"]
mod amenable_core_cert;
#[path = "../../amenable_core/src/contract.rs"]
mod amenable_core_contract;
#[path = "../../amenable_core/src/evidence.rs"]
mod amenable_core_evidence;
#[path = "../../amenable_core/src/exchange.rs"]
mod amenable_core_exchange;
#[path = "../../amenable_core/src/metadata_entry.rs"]
mod amenable_core_metadata_entry;
#[path = "../../amenable_core/src/state_machine.rs"]
mod amenable_core_state_machine;
#[path = "../../amenable_core/src/verifier.rs"]
mod amenable_core_verifier;

pub use amenable_core_cert::{Certificate, Registry, RegistryReport};
pub use amenable_core_contract::{Ensures, Requires};
pub use amenable_core_evidence::Evidence;
pub use amenable_core_exchange::{Establish, Exchange, ProofToken, Sidecar};
pub use amenable_core_metadata_entry::MetadataEntry;
pub use amenable_core_state_machine::{StateMachine, Transition, TransitionAudit};
pub use amenable_core_verifier::Verifier;
pub use provenance_accommodation::{AsStandard, Provenance, Standard};
pub use witness_accommodation::Witness;
