//! Temporal contract types, grouped by normative source. The module
//! layout mirrors `elicit_temporal/src/contracts/` one-to-one so bulk
//! registration stays orderly (`docs/AMENABLE_TIME_PLAN.md`,
//! "Registration strategy").
//!
//! Citation-only structural contracts are
//! [`Standard`](amenable_core::Standard)s (this module). The composed /
//! provable `*Valid` aggregates become
//! [`Evidence`](amenable_core::Evidence) in `contracts::proof_composition`
//! (plan Phase 3).

mod conversion;
mod extended;
mod instant;
mod interval;
mod iso_8601;
mod precision;
mod rfc3339;
mod rfc9557;
mod serialization;
mod zone;

pub use conversion::{
    ConversionDropsNamedZoneIdentity, ConversionDropsSubsecondPrecision,
    ConversionPreservesRepresentedInstant, ConversionPreservesTemporalOrdering,
    ConversionRequiresExplicitAuthorityWhenLossy, ConversionSourceSemanticKindDeclared,
    ConversionTargetSemanticKindDeclared,
};
pub use instant::{
    LocalDateTimeMayBeAmbiguousAtZoneTransition, LocalDateTimeMayFallInZoneTransitionGap,
    LocalDateTimeRequiresZoneOrOffsetForInstant, OffsetDateTimeIdentifiesSingleInstant,
    TimestampHasExplicitUtcOffset, UtcTimelineOrderingAppliesToFixedInstants,
};
pub use interval::{
    CompleteIntervalCalendarDateMayBeSubstitutedByOrdinalDate,
    CompleteIntervalCalendarDateMayBeSubstitutedByWeekDate,
    CompleteIntervalDurationMaySubstituteWeekForm,
    CompleteIntervalLocalTimeMayBeSubstitutedByLocalTimeAndUtcDifference,
    CompleteIntervalLocalTimeMayBeSubstitutedByUtcOfDay,
    DurationAlternativeFormCarriesCompleteCalendarAndClockComponents,
    DurationAlternativeFormRequiresPartnerAgreement,
    DurationAlternativeFormUsesDateAndTimeComponentSlots,
    DurationTimeComponentsFollowTimeDesignator, DurationUsesPeriodDesignator,
    DurationWeekFormNotMixedWithCalendarOrClockUnits, DurationWeekFormUsesSingleWeekUnit,
    IntervalDurationIsNonNegative, IntervalEndOmittedHigherOrderComponentsInheritFromStart,
    IntervalStartPrecedesEnd,
    IntervalTrailingComponentInheritsZoneOrUtcFromLeadingComponentWhenOmitted,
    RecurringIntervalCarriesIntervalComponent, RecurringIntervalCountIsNonNegativeWhenBounded,
    RecurringIntervalOmittedCountDenotesUnboundedOccurrences,
    RecurringIntervalUsesCompleteTimeIntervalRepresentation,
    RecurringIntervalUsesOtherThanCompleteTimeIntervalRepresentation,
    RecurringIntervalUsesRepeatDesignator, TimeIntervalBoundaryOrDurationFormDeclared,
    TimeIntervalHasTwoComponents, TimeIntervalUsesSolidusSeparator,
};
pub use rfc3339::{
    Rfc3339ApplicationsMayAllowSpaceDateTimeSeparator,
    Rfc3339ClientsShouldTransformDatesForLocalityDisplay, Rfc3339FractionUsesDotSeparator,
    Rfc3339FractionalSecondsAreOnlyRarelyUsedOption, Rfc3339GeneratorsShouldUseUppercaseTAndZ,
    Rfc3339LeapSecondGenerationRequiresPriorAnnouncement,
    Rfc3339LexicalOrderingRequiresUniformFractionalSecondDigits,
    Rfc3339LexicalOrderingRequiresUniformUtcRelationshipEncoding, Rfc3339LocalOffsetNotUnknown,
    Rfc3339LocalityDisplayMayTranslateUtcToLocalTime, Rfc3339OffsetIsUtcOrNumeric,
    Rfc3339PositiveZeroOffsetDeclaresPreferredUtcReferencePoint,
    Rfc3339ProfileMakesMostFieldsAndPunctuationMandatory, Rfc3339RequiresUtcRelationship,
    Rfc3339TimestampExcludesRedundantWeekdayInformation,
    Rfc3339UnknownLocalOffsetUsesZuluDesignator, Rfc3339UnqualifiedLocalTimeForbidden,
    Rfc3339UsesExtendedCalendarDate, Rfc3339UsesFourDigitYear, Rfc3339UsesFullTime,
};
pub use rfc9557::{
    IxdtfCalendarAnnotationDeclaresPreferredPresentationCalendar, IxdtfCalendarAnnotationPresent,
    IxdtfCalendarKeyUsesUCa, IxdtfCalendarValueUsesUnicodeCalendarIdentifier,
    IxdtfCriticalFlagIsLeadingExclamationWhenPresent,
    IxdtfCriticalSuffixTagsRequireProcessingOrErrorHandling,
    IxdtfDuplicateElectiveSuffixUsesFirstOccurrence,
    IxdtfExperimentalSuffixKeysAreNotForInterchange, IxdtfExperimentalSuffixKeysCannotBeRegistered,
    IxdtfExperimentalSuffixKeysUseLeadingUnderscore,
    IxdtfExpertReviewAscertainsBasicSpecificationExists,
    IxdtfExpertReviewReservesConciseGenerallyApplicableKeys,
    IxdtfExpertsMayInitiateRegistrationToAvoidFutureCollisions, IxdtfGeneratorsMayOmitSuffixTags,
    IxdtfPermanentEntriesUseSpecificationRequiredPolicy,
    IxdtfPermanentRegisteredSuffixKeyRequiresFullSpecificationReference,
    IxdtfProvisionalEntriesUseExpertReviewPolicy,
    IxdtfProvisionalRegisteredSuffixKeyReferenceExpectedToImproveOverTime,
    IxdtfProvisionalRegisteredSuffixKeyRequiresReferenceInformation,
    IxdtfRecipientsMayIgnoreElectiveSuffixTags,
    IxdtfRecipientsMustRejectUnconfiguredExperimentalSuffixKeys,
    IxdtfRegisteredSuffixKeyCarriesChangeController, IxdtfRegisteredSuffixKeyCarriesDescription,
    IxdtfRegisteredSuffixKeyCarriesKeyIdentifier, IxdtfRegisteredSuffixKeyCarriesReference,
    IxdtfRegisteredSuffixKeyCarriesRegistrationStatus,
    IxdtfRegisteredSuffixKeyStatusIsProvisionalOrPermanent, IxdtfRegistryInitiallyContainsUCaEntry,
    IxdtfSuffixFollowsRfc3339Timestamp, IxdtfSuffixKeysAreLowercase,
    IxdtfSuffixTagsUseBracketedKeyValueForm,
    IxdtfSuffixValuesAreCaseSensitiveUnlessOtherwiseSpecified,
    IxdtfSuffixValuesUseHyphenDelimitedItems, IxdtfTimeZoneSuffixUsesBracketedNameOrOffset,
    IxdtfUCaRegistryEntryIsPermanent, IxdtfUCaRegistryEntryReferencesSectionFive,
    IxdtfUCaRegistryEntryUsesIetfChangeController,
    IxdtfUCaRegistryEntryUsesPreferredCalendarForPresentationDescription,
};
pub use serialization::{
    Iso8601BasicFormUsesCompactRepresentation, Iso8601ExtendedFormUsesSeparators,
    IxdtfSerializationCarriesNamedZoneAnnotation, SerializationCarriesExplicitUtcRelationship,
    SerializationProfileDeclared,
};
pub use zone::{
    CriticalTimeZoneSuffixInconsistencyRequiresAction,
    ElectiveTimeZoneSuffixInconsistencyMayBeHandled, NamedTimeZoneAnnotationPresent,
    NamedTimeZoneIdentifierExcludesDotSegments, NamedTimeZoneIdentifierIsCaseSensitive,
    NamedTimeZoneIsNotNumericOffsetAlias, NamedTimeZoneMeaningUsesCurrentTzdbRules,
    NamedTimeZoneRetainsCivilRuleIdentity, NamedTimeZoneUsesIanaIdentifier,
    NumericOffsetDoesNotIdentifyNamedZone, OffsetTimeZoneAnnotationPresent,
    OffsetTimeZoneMustNotBeSynthesizedFromTimestampOffset, OffsetTimeZoneRepeatsTimestampOffset,
    OffsetTimeZoneUseIsStronglyDiscouraged, UnknownNamedTimeZoneIdentifierTreatedAsInconsistency,
    ZoneOffsetResolvedForRepresentedInstant, ZoneTransitionAmbiguityDeclared,
    ZoneTransitionDisambiguationAuthorityDeclared, ZoneTransitionGapDeclared,
    ZoneTransitionGapHandlingAuthorityDeclared, ZuluTimeZoneSuffixAvoidsOffsetInconsistency,
};

pub use extended::{
    ApproximationQualificationDeclared, BeforeOrAfterQualificationIsLevelTwoOnly,
    BeforeOrOnDateUsesLeadingDoubleDotQualifier, BeforeYearOneValueUsesTrailingBSuffix,
    ComponentQualificationAppliesOnlyToMarkedComponent,
    ComponentQualificationUsesImmediateLeftPlacement,
    EnhancedIntervalLevelOnePermitsTerminalBoundaryQualification,
    EnhancedIntervalLevelTwoPermitsBeforeOrAfterBoundaryQualification,
    EnhancedIntervalLevelTwoPermitsInternalBoundaryQualification,
    EnhancedIntervalLevelTwoPermitsInternalBoundaryUnspecifiedDigits,
    ExponentialYearExponentIsPositiveInteger, ExponentialYearUsesPowerOfTenNotation,
    GroupQualificationAppliesToMarkedAndMoreSignificantComponents,
    GroupQualificationUsesImmediateRightPlacement,
    LetterPrefixedCalendarYearMagnitudeExceedsFourDigits,
    LetterPrefixedCalendarYearUsesLeadingYDesignator,
    LevelOneUnspecifiedDigitsOccupyRightmostPositions,
    LevelTwoUnspecifiedDigitsMayAppearWithinComponent, NegativeCalendarYearUsesLeadingMinusSign,
    OnOrAfterDateUsesTrailingDoubleDotQualifier, OpenIntervalBoundaryDeclared,
    QualificationScopeDeclared, SeasonCodeDeclaresNamedSeason, SeasonCodeDeclaresSeasonScope,
    SeasonalExpressionUsesSeasonCodeInMonthSlot, SeasonalExpressionUsesYearAndSeasonForm,
    SignificantDigitYearCountIsPositiveInteger, SignificantDigitYearUsesTrailingSSuffix,
    SubYearGroupingCodeDeclaresQuadrimester, SubYearGroupingCodeDeclaresQuarter,
    SubYearGroupingCodeDeclaresSemestral, SubYearGroupingExpressionUsesGroupingCodeInMonthSlot,
    SubYearGroupingExpressionUsesYearAndGroupingForm, TemporalChoiceSetUsesSquareBrackets,
    TemporalInclusiveSetUsesCurlyBraces, TemporalSetCarriesMultipleMembers,
    TemporalSetDeclaresAlternativeSemantics, TemporalSetDeclaresInclusiveMemberSemantics,
    TemporalSetForbidsInternalWhitespace, TemporalSetMemberSeparatorDeclared,
    TemporalSetOpenRangeUsesBoundaryDoubleDot, TemporalSetRangeNeighborhoodSharesPrecision,
    TemporalSetRangeUsesInclusiveDoubleDotSemantics, UncertaintyAndApproximationMayBeCombined,
    UncertaintyQualificationDeclared, UnknownIntervalBoundaryDeclared,
    UnspecifiedDigitUsesUppercaseXPlaceholder, UnspecifiedDigitsDeclareUnknownValue,
};
pub use iso_8601::{
    BasicFormatUsesMinimumComponentsForRequiredAccuracy, CalendarDateHasYearMonthDay,
    CalendarDateUsesGregorianCalendar,
    CalendarDayDurationMayBeModifiedByLeapSecondsOrLocalTimeShifts,
    CalendarDayIsIntervalOfSingleCalendarDateAdvance, CalendarDayWithinMonthBounds,
    CalendarMonthInRangeOneToTwelve, CalendarMonthIsNamedIntervalWithinCalendarYear,
    CalendarWeekIsSevenDayIntervalBeginningOnMonday, CalendarWeekNumberUsesFirstThursdayRule,
    CalendarWeekStartsOnMonday, CalendarYearInRangeZeroToNineThousandNineHundredNinetyNine,
    CalendarYearIsIntervalOfSuccessiveCalendarMonths,
    CalendarYearThrough1582RequiresMutualAgreement, CentennialYearDivisibleByOneHundred,
    CenturyOrdinalInRangeZeroToNinetyNine, ColonSeparatesTimeComponents,
    CombinedDateTimeDateComponentMustNotUseReducedAccuracy,
    CombinedDateTimePermitsCalendarDateComponent, CombinedDateTimePermitsOrdinalDateComponent,
    CombinedDateTimePermitsWeekDateComponent,
    CombinedDateTimeUsesSingleFormatAcrossDateAndTimeComponents,
    CombinedDateTimeUsesTimeDesignator, CommonYearHasThreeHundredSixtyFiveCalendarDays,
    CompleteRepresentationCarriesAllRequiredComponents, DateIdentifiesPositionWithinCalendar,
    DateTimeFormatRepresentationDescribesRepresentationFamily,
    DateTimeFormatRepresentationsForbiddenInTelexRepertoire,
    DateTimeRepresentationIdentifiesPointIntervalOrRecurrence,
    DayDurationMaySpanSameTimeOfDayOnAdjacentCalendarDays, DayEqualsTwentyFourHours,
    DecadeOrdinalInRangeZeroToNineHundredNinetyNine,
    DecimalRepresentationUsesLowestOrderComponentFraction,
    DurationEqualsDifferenceBetweenIntervalEndpoints,
    EndOfDayTwentyFourHourAllowedOnlyWithinIntervalOrRecurrence,
    EndOfDayTwentyFourHourForbiddenForSingleTimePoint,
    ExpandedRepresentationRequiresAdditionalAgreement, FixedWidthComponentsRequireLeadingZeros,
    FormatRepresentationUsesPlaceholderCharactersForDigitsAndSigns,
    FractionAppliesToLowestOrderComponent, FractionUsesDecimalSign,
    GregorianLeapYearUsesDivisibleByFourAndFourHundredException, HourEqualsSixtyMinutes,
    HourInRangeZeroToTwentyFour, HyphenSeparatesDateComponents, InstantIsPointOnTimeAxis,
    LeapDayOccursOnlyInLeapYear, LeapSecondOccursOnlyAtUtcBoundary,
    LeapYearHasThreeHundredSixtySixCalendarDays, LiteralFormatCharactersCopyIntoRepresentations,
    LocalTimeHasHourMinuteSecond, LocalTimeRequiresTimeDesignatorWhenContextAmbiguous,
    LocalTimeScaleMayBeStandardOrNonUtcBased, LocalTimeUsesLocallyApplicableTimeScale,
    MinuteEqualsSixtySeconds, MinuteInRangeZeroToFiftyNine,
    MonthDurationInRangeTwentyEightToThirtyOneCalendarDays,
    MonthDurationMayRequireAgreedEndingCalendarDay,
    MonthMayBeConsideredThirtyCalendarDaysInCertainApplications,
    NominalDayDurationMayDifferFromExactElapsedTime, NominalDurationDependsOnCalendarContext,
    NominalMonthDurationDependsOnCalendarContext,
    NominalWeekDurationIsDistinctFromExactElapsedTime, NominalYearDurationDependsOnCalendarContext,
    OrdinalDateHasYearAndDayOfYear, OrdinalDayInRangeOneToThreeHundredSixtySix,
    OrdinalDayOfYearUsesThreeDigits, ProlepticGregorianDatesBefore1583RequireMutualAgreement,
    ReducedAccuracyLocalTimeUsesHourMinuteRepresentation,
    ReducedAccuracyLocalTimeUsesHourOnlyRepresentation,
    ReducedAccuracyRepresentationOmitsLowerOrderComponents,
    ReducedAccuracyWeekDateOmitsWeekdayComponent, ReducedCalendarDateHasYearComponent,
    ReducedCalendarDateOmitsLowerOrderDigitsFromExtremeRight,
    ReducedCalendarDateUsesYearMonthRepresentation, ReducedCalendarDateUsesYearOnlyRepresentation,
    SecondInRangeZeroToSixty, SecondIsBaseUnitForExpressingDuration, SecondIsSiBaseUnitOfTime,
    SpaceForbiddenUnlessExplicitlyPermitted, StandardTimeDerivedFromUtcByLocalShift,
    StandardTimeOfDayUsesStandardTimeScale, TimeAxisOrdersTimePointsByTemporalPosition,
    TimeIsMarkOnSpecifiedTimeScale, TimeOfDayOccursWithinCalendarDay,
    TimeScaleAssociatesTimePointsWithOrderedMeasure, TimeShiftIsConstantDurationBetweenTimeScales,
    TwentyFourHourRequiresZeroMinuteSecondAndFraction, TwentyFourHourReservedForEndOfDay,
    UnderlineFallbackPrecedesQualifiedFormatCharacter,
    UnderlinedFormatPlaceholderRepresentsZeroOrMoreDigits, UtcDesignatorIsUppercaseZ,
    UtcDifferenceAppendedImmediatelyWithoutSpace, UtcDifferenceExpressionIsNotSelfStanding,
    UtcDifferenceMinutesOmittedOnlyForIntegralHourOffsets,
    UtcDifferenceSignEncodesDirectionRelativeToUtc, UtcIsReferenceTimeScale,
    UtcOfDayIdentifiesTimeWithinUtcCalendarDay, UtcOfDayUsesTrailingZuluDesignatorImmediately,
    UtcOffsetCarriesSignHourAndOptionalMinute, UtcOffsetHourInRangeZeroToTwentyThree,
    UtcOffsetMinuteInRangeZeroToFiftyNine, WeekDateHasWeekYearWeekAndWeekday,
    WeekDateUsesWeekDesignator, WeekDurationMaySpanSameTimeOfDayInNextCalendarWeek,
    WeekNumberInRangeOneToFiftyThree, WeekdayInRangeOneToSeven,
    YearDurationInRangeThreeHundredSixtyFiveToThreeHundredSixtySixCalendarDays,
    YearDurationMayRequireAgreedEndingCalendarDate,
};
pub use precision::{
    FractionalSecondDigitsAreContiguous, FractionalSecondPrecisionDeclared,
    PrecisionReductionDeclared, RoundingModeDeclared, SubsecondDigitsPreserved,
};
