//! Emit derived Creusot `Exchange`-edge companions from the real registry.
//!
//! Generates one `amenable_derive::harness! { creusot, .. }` block plus its
//! `ProofRecord` registration per real `Exchange` edge -- the same per-edge
//! content `amenable_creusot::stoplight` used to hand-write and hand-keep-
//! in-sync against `amenable_kani::stoplight`'s real body (via
//! `stoplight_mirror_consistency_test.rs`). Reads `amenable_core::
//! ExchangeEdgeRecord`, registered by `#[amenable_derive::exchange(..)]`
//! from whichever crate owns the real edge (currently always
//! `amenable_kani`) -- the same `inventory`-registry-then-generate pattern
//! `verus_export`/`emit-verus-witnesses` already uses for the witness-
//! composition system, applied here to `Exchange` edges. `inventory` never
//! appears in the generated output at all -- only in this ordinary,
//! never-translated `amenable` binary, which is what makes this safe for a
//! whole-crate-translator backend like Creusot (see `ExchangeEdgeRecord`'s
//! own doc comment).
//!
//! Deliberately narrow: generates only the per-edge `harness!`/
//! `ProofRecord` content, not the surrounding state/token/sidecar type
//! definitions (`Green`/`Yellow`/... `Established<T, Token>`), which stay
//! hand-written, stable, one-time accommodation-model infrastructure in
//! `amenable_creusot/src/stoplight.rs` -- low drift risk (they rarely
//! change), unlike the transition bodies this replaces hand-copying of.
//! Written via `include!`, not a `mod`, so the generated file shares
//! `stoplight.rs`'s own scope directly -- no `use super::*;`/explicit
//! imports needed for `Green`/`Yellow`/`Established`/etc.
//!
//! The `#[requires(true)]`/`#[ensures(true)]` contract is hardcoded for
//! now: every real edge in the tree today has a legitimately trivial claim
//! (see `EXCHANGE_PROOF_DERIVATION_PLAN.md`'s own open question). A
//! genuinely non-trivial Pearlite predicate will need its own real
//! mechanism (a `creusot_ensures!`-registered fragment, analogous to
//! `kani_ensures!`/`verus_ensures!`) once one actually exists -- not
//! designed speculatively here.

use std::{
    fs,
    path::{Path, PathBuf},
};

use amenable_core::ExchangeEdgeRecord;

use crate::{AmenableError, AmenableResult};

/// Write one generated Creusot companion file per real `Exchange` edge
/// registered via `amenable_core::ExchangeEdgeRecord`, under `root` (e.g.
/// `amenable_creusot/src/generated/`). Sorted by method name so
/// regeneration is deterministic and diffs stay minimal.
///
/// Filtered to `self_ty == "Stoplight"`: this generator's whole model
/// (a free function whose body is `include!`d into a scope that already
/// has matching-named mirror types, and a hardcoded trivial `#[ensures(
/// true)]`) is specific to `Stoplight`'s own accommodation-model shape.
/// `amenable_kani::ledger`'s edges (`validate`/`commit`/`reject`/
/// `rollback`) also register an `ExchangeEdgeRecord` via the same
/// `#[amenable_derive::exchange(..)]` macro, but nothing consumes their
/// companions yet -- `Ledger`/`Transfer<S, Token>` still only exist in
/// `amenable_kani`, which `amenable_creusot` cannot depend on, and their
/// real claims are proven directly against `amenable_gaap`'s real
/// `Validated`/`Committed` types instead (see `amenable_creusot::
/// ledger`'s own doc comment). Without this filter, `just generate-
/// creusot` silently wrote four `.rs` files nothing `include!`s and
/// nothing could compile if it did (the real body references `Self::
/// check_amount_positive`/`TransferError`/etc., which don't exist in
/// any mirror namespace) -- confirmed directly, not assumed, before
/// this filter was added.
pub fn write_creusot_exchange_companions(root: &Path) -> AmenableResult<Vec<PathBuf>> {
    fs::create_dir_all(root).map_err(|error| AmenableError::io(root, error))?;

    let mut records: Vec<&ExchangeEdgeRecord> = inventory::iter::<ExchangeEdgeRecord>()
        .filter(|record| tidy_stringified_type(record.self_ty) == "Stoplight")
        .collect();
    records.sort_by_key(|record| record.method_name);

    let mut written = Vec::with_capacity(records.len());
    for record in records {
        let path = root.join(format!("{}.rs", record.method_name));
        let source = render_companion(record);
        fs::write(&path, source).map_err(|error| AmenableError::io(&path, error))?;
        written.push(path);
    }

    Ok(written)
}

fn render_companion(record: &ExchangeEdgeRecord) -> String {
    let const_name = format!("VERIFY_{}_EXCHANGE_SRC", record.method_name.to_uppercase());
    let evidence_path = format!("amenable_creusot::stoplight::{}", record.method_name);

    format!(
        "// AUTO-GENERATED by `amenable emit-creusot-companions` -- do not\n\
         // hand-edit; regenerate with `just generate-creusot`.\n\
         // Source: `{self_ty}::{method_name}`'s real body, captured verbatim\n\
         // by `#[amenable_derive::exchange(..)]` and registered via\n\
         // `amenable_core::ExchangeEdgeRecord` -- see `amenable::\n\
         // creusot_export`'s own doc comment. Plain `//`, not `//!`: this\n\
         // file is `include!`d mid-file into `stoplight.rs`'s own scope,\n\
         // not its own module -- an inner doc comment there is a real\n\
         // compile error (E0753, confirmed against a real build), not\n\
         // just a style choice.\n\
         \n\
         amenable_derive::harness! {{\n\
         \x20\x20\x20\x20creusot, {const_name}, {{\n\
         \x20\x20\x20\x20\x20\x20\x20\x20#[requires(true)]\n\
         \x20\x20\x20\x20\x20\x20\x20\x20#[ensures(true)]\n\
         \x20\x20\x20\x20\x20\x20\x20\x20fn {method_name}(input: {input_ty}) -> Result<{output_ty}, {error_ty}> {{\n\
         {body}\n\
         \x20\x20\x20\x20\x20\x20\x20\x20}}\n\
         \x20\x20\x20\x20}}\n\
         }}\n\
         \n\
         #[cfg(not(creusot))]\n\
         ::inventory::submit! {{\n\
         \x20\x20\x20\x20::amenable_core::ProofRecord {{\n\
         \x20\x20\x20\x20\x20\x20\x20\x20evidence: \"{evidence_path}\",\n\
         \x20\x20\x20\x20\x20\x20\x20\x20verifier: \"creusot\",\n\
         \x20\x20\x20\x20\x20\x20\x20\x20describe: || {const_name}.to_owned(),\n\
         \x20\x20\x20\x20}}\n\
         }}\n",
        self_ty = tidy_stringified_type(record.self_ty),
        method_name = record.method_name,
        input_ty = tidy_stringified_type(record.input_ty),
        output_ty = tidy_stringified_type(record.output_ty),
        error_ty = tidy_stringified_type(record.error_ty),
        body = indent_body(record.body),
    )
}

/// `stringify!(#ty)` (used to capture `ExchangeEdgeRecord`'s type fields
/// at macro-expansion time, in `amenable_derive::exchange`) joins tokens
/// with a single space each, so `Established<Green, GreenToken>` comes
/// back as `"Established < Green , GreenToken >"` -- valid Rust, but
/// `rustfmt` never sees it: it doesn't reformat inside an opaque macro
/// invocation's own token tree by default, confirmed directly (`rustfmt`
/// run on a real generated file left `harness! { .. }`'s contents
/// untouched). Fixed here, not by relying on a later `cargo fmt` pass:
/// strip the space `stringify!` inserts immediately before/after `<` and
/// immediately before `,`/`>` -- the only spacing artifacts generic-type
/// syntax actually produces, so this is a narrow, well-defined text fix,
/// not a general Rust formatter. Confirmed against a real generated file
/// through two passes, not assumed correct on the first attempt: an
/// earlier version only stripped the space *after* `<`, leaving
/// `Established <Green, GreenToken>`'s space *before* `<` untouched.
fn tidy_stringified_type(stringified: &str) -> String {
    let mut tidied = String::with_capacity(stringified.len());
    let mut chars = stringified.chars().peekable();

    while let Some(ch) = chars.next() {
        match ch {
            ' ' if chars.peek() == Some(&'<') => {}
            '<' => {
                tidied.push(ch);
                while chars.peek() == Some(&' ') {
                    chars.next();
                }
            }
            ' ' if matches!(chars.peek(), Some(',') | Some('>')) => {}
            _ => tidied.push(ch),
        }
    }

    tidied
}

/// Re-indent a captured method body's own lines to sit correctly nested
/// inside the generated `harness! { .. { fn .. { <body> } } }` shape.
/// Two real, confirmed passes, not one: `rustfmt` doesn't reformat
/// inside `harness! { .. }`'s own opaque macro invocation (confirmed
/// directly against a real generated file), so this has to get the
/// whitespace right itself, not defer to a later `cargo fmt` pass that
/// never actually reaches this text.
///
/// 1. **Dedent.** The captured text is `Span::source_text()` on the
///    method's own `{ .. }` block, then `.trim()`-stripped of its outer
///    braces (`amenable_derive::exchange`'s own `trim_braces`, mirroring
///    `harness!`'s identical helper) -- `.trim()` only touches the very
///    start/end of the *whole* string, so the first line loses its
///    original indentation (right after the opening `{`) while every
///    other line keeps its real, original column from `amenable_kani::
///    stoplight.rs`. Confirmed as a real bug, not assumed: a first,
///    naive version that only re-indented uniformly (no dedent pass)
///    produced visibly double-indented non-first lines in a real
///    generated file. Fixed by finding the minimum indentation among
///    the non-first, non-empty lines and stripping exactly that much
///    from all of them, before re-indenting everything uniformly.
/// 2. **Re-indent.** Once every line starts at a shared, zero baseline,
///    prefix each non-empty line with the real target indentation for
///    this generated shape (12 spaces: inside `harness! { .. { fn .. {`
///    's own three nesting levels).
fn indent_body(body: &str) -> String {
    let lines: Vec<&str> = body.lines().collect();
    let dedent_width = lines
        .iter()
        .skip(1)
        .filter(|line| !line.trim().is_empty())
        .map(|line| line.len() - line.trim_start().len())
        .min()
        .unwrap_or(0);

    lines
        .iter()
        .enumerate()
        .map(|(index, line)| {
            if line.trim().is_empty() {
                return String::new();
            }
            let dedented = if index == 0 {
                *line
            } else {
                &line[dedent_width.min(line.len())..]
            };
            format!("            {dedented}")
        })
        .collect::<Vec<_>>()
        .join("\n")
}
