//! Verus accommodation models for `amenable_ext`'s third-party carriers,
//! one module per target crate — the `amenable_verus` counterpart of
//! `rust_std`, for types outside the Rust standard library.

pub mod jiff;

pub use jiff::{
    AmbiguousTimestampModel, AmbiguousZonedModel, DstModel, EraModel, ErrorClassModel,
    FractionalUnitModel, MeridiemModel, PiecesModel, PiecesNumericOffsetModel, PiecesOffsetModel,
    TimeZoneAnnotationKindModel, TimeZoneAnnotationModel, TimeZoneAnnotationNameModel,
    TimeZoneDatabaseModel, TimeZoneModel, TimeZoneOffsetInfoModel, UnitModel,
    resolve_always_offset_seconds, resolve_always_time_zone_seconds,
    verify_civil_date_new_year_month_day_round_trips_model,
    verify_civil_era_year_classifies_bce_and_ce_correctly_model,
    verify_civil_iso_week_date_new_year_week_weekday_round_trips_model,
    verify_civil_time_new_hour_minute_second_subsec_round_trips_model,
    verify_civil_time_series_next_yields_start_then_advances_by_period,
    verify_civil_weekday_monday_one_offset_round_trips_model,
    verify_civil_weekdays_forward_next_yields_start_then_its_successor,
    verify_civil_weekdays_reverse_next_yields_start_then_its_predecessor,
    verify_date_series_next_yields_start_then_advances_by_period,
    verify_date_time_series_next_yields_start_then_advances_by_period,
    verify_error_classification_predicates_are_mutually_exclusive,
    verify_fmt_friendly_fractional_unit_from_matches_documented_mapping_model,
    verify_fmt_std_fmt_write_write_str_model, verify_fmt_std_io_write_write_str_model,
    verify_fmt_strtime_meridiem_from_time_matches_hour_threshold_model,
    verify_fmt_temporal_pieces_numeric_offset_from_and_with_negative_zero_model,
    verify_fmt_temporal_pieces_offset_zulu_and_from_offset_round_trip_model,
    verify_fmt_temporal_pieces_with_date_with_time_round_trip_model,
    verify_fmt_temporal_time_zone_annotation_from_name_and_from_offset_model,
    verify_fmt_temporal_time_zone_annotation_kind_from_name_and_from_offset_model,
    verify_fmt_temporal_time_zone_annotation_name_from_str_round_trips_model,
    verify_offset_from_seconds_model_round_trips,
    verify_signed_duration_new_model_normalizes_nanos_and_carries_into_secs,
    verify_span_fieldwise_negation_model_negates_every_unit_getter,
    verify_timestamp_series_next_yields_start_then_advances_by_period,
    verify_tz_ambiguous_timestamp_from_fixed_time_zone_is_always_unambiguous_model,
    verify_tz_ambiguous_zoned_from_fixed_time_zone_is_always_unambiguous_model,
    verify_tz_dst_from_bool_round_trips_model,
    verify_tz_offset_conflict_always_offset_and_always_time_zone_model,
    verify_tz_time_zone_database_none_is_definitively_empty_model,
    verify_tz_time_zone_offset_info_from_fixed_time_zone_model,
    verify_tz_time_zone_unknown_and_fixed_round_trip_model,
    verify_unit_ordering_matches_discriminant_order_model,
    verify_zoned_series_next_yields_start_then_advances_by_period_under_utc,
};

#[cfg(verus_keep_ghost)]
pub use jiff::{
    ambiguous_timestamp_from_fixed_offset_seconds_holds,
    ambiguous_zoned_from_fixed_offset_seconds_holds, civil_date_fields_in_range,
    civil_date_new_model_round_trip_holds, civil_era_year_classifies_bce_and_ce_correctly,
    civil_era_year_in_range, civil_iso_week_date_new_model_round_trip_holds,
    civil_iso_week_date_week_in_range, civil_iso_week_date_year_in_range,
    civil_time_fields_in_range, civil_time_new_model_round_trip_holds,
    civil_time_series_next_yields_start_then_advances_by_period_holds,
    civil_time_series_period_nanos_in_range, civil_time_series_start_nanos_in_range,
    civil_weekday_monday_one_offset_model_round_trip_holds,
    civil_weekdays_forward_next_yields_start_then_its_successor_holds,
    civil_weekdays_forward_start_offset_in_range,
    civil_weekdays_reverse_next_yields_start_then_its_predecessor_holds,
    civil_weekdays_reverse_start_offset_in_range,
    date_series_next_yields_start_then_advances_by_period_holds, date_series_period_days_in_range,
    date_series_start_days_in_range,
    date_time_series_next_yields_start_then_advances_by_period_holds,
    date_time_series_period_days_in_range, date_time_series_start_days_in_range,
    dst_from_bool_holds, dst_is_dst_holds, dst_is_std_holds,
    error_classification_predicates_are_mutually_exclusive, fmt_std_fmt_write_appends_str,
    fmt_std_io_write_appends_bytes, fractional_unit_model_conversion_holds, meridiem_hour_in_range,
    meridiem_model_from_hour_holds, offset_conflict_always_offset_holds,
    offset_conflict_always_time_zone_holds, offset_from_seconds_model_round_trip_holds,
    offset_seconds_in_range, pieces_from_date_holds, pieces_offset_from_offset_seconds_holds,
    pieces_offset_to_numeric_seconds_holds, pieces_offset_zulu_holds, pieces_with_date_holds,
    pieces_with_time_holds, pno_from_offset_seconds_holds, pno_offset_seconds_in_range,
    pno_with_negative_zero_holds, signed_duration_new_model_normalizes,
    signed_duration_new_secs_headroom_holds, span_fieldwise_negation_model_holds,
    time_zone_database_none_holds, time_zone_fixed_holds,
    time_zone_offset_info_from_fixed_offset_seconds_holds, time_zone_unknown_holds,
    timestamp_series_next_yields_start_then_advances_by_period_holds,
    timestamp_series_period_seconds_in_range, timestamp_series_start_seconds_in_range,
    tz_annotation_from_name_holds, tz_annotation_from_offset_seconds_holds,
    tz_annotation_kind_from_name_holds, tz_annotation_kind_from_offset_seconds_holds,
    tz_annotation_name_as_str_holds, tz_annotation_name_from_name_holds, unit_model_discriminant,
    unit_model_discriminant_exec_matches, unit_model_ordering_holds,
    weekday_monday_one_offset_in_range, weekday_offset_in_range,
    zoned_series_next_yields_start_then_advances_by_period_under_utc_holds,
    zoned_series_period_seconds_in_range, zoned_series_start_seconds_in_range,
};
