[package]
name = "amenable_std"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true

description = "RustStdType: interface and concrete registrations for Rust standard-library types"
keywords = ["formal-verification", "proof", "std", "provenance"]
categories = ["development-tools", "rust-patterns"]

[dependencies]
amenable_core = { workspace = true }
amenable_derive = { workspace = true }
